### PR TITLE
Fix multiple query error being classified as an internal error

### LINKED ISSUE #6621: Bug: Multiple statements in a query should not be an internal error
## Describe the bug

Running multiple statements in a query returns "Internal Error"

```bash
sql> select "review_id", "review_date", "customer_id", "review_headline", "review_body" from spice.public.realtime_reviews where lower("review_body") like '%disappointed%' or lower("review_body") like '%frustrated%' or lower("review_body") like '%unhappy%' or lower("review_body") like '%not happy%' or lower("review_body") like '%regret%' or lower("review_body") like '%poor%' or lower("review_body") like '%bad%' or lower("review_body") like '%does not work%' or lower("review_body") like '%broke%' or lower("review_body") like '%broken%' or lower("review_body") like '%defective%' order by "review_date" desc limit 10;SELECT *
FROM vector_search(realtime_reviews, 'disappointed customer negative sentiment', 10)
WHERE review_body ILIKE '%disappointed%' OR review_headline ILIKE '%disappointed%'
ORDER BY score DESC;
Internal Error: An unexpected internal error occurred. Execute '.error' for details.
sql> .error
An internal error occurred.
This feature is not implemented: The context currently only supports a single SQL statement
sql> 
```

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by Advayp**
## 📝 Summary
- See title
- Necessary as it improves UX and fixes a bug
image

## 🔗 Related

- Closes #6621

### CODE REVIEW

**Review by sgrebnov — DISMISSED** [review]

**Review by kczimm — DISMISSED** [review]

File: crates/runtime/src/flight/mod.rs [hunk 1]
```diff
@@ -330,8 +330,10 @@ fn handle_datafusion_error(e: DataFusionError) -> Status {
                 Status::internal("Several DataFusion errors occurred, but no details available")
             }
         }
+        DataFusionError::NotImplemented(message) => {
+            Status::invalid_argument(format!("Feature not implemented: {message}"))
```
Comment (lukekim) [inline crates/runtime/src/flight/mod.rs]: Do we need the `Feature not implemented`? What's some examples of the messages that come through? Might be nice to have some examples in a comment.

Comment (lukekim) [reply crates/runtime/src/flight/mod.rs]: Also, feature not implemented is an internal message to DF consumers, not friendly for end users. Should be something like `X is not supported: `

Comment (Advayp) [reply crates/runtime/src/flight/mod.rs]: > Do we need the `Feature not implemented`? What's some examples of the messages that come through? Might be nice to have some examples in a comment.

@lukekim, They vary, some include in the message itself saying an action is unsupported, like:
```
Unsupported ast node Function { lateral: true, name: ObjectName([Identifier(Ident { value: "unnest", quote_style: None, span: Span(Location(6,20)..Location(6,26)) })]), args: [Unnamed(Expr(Identifier(Ident { value: "review_comments", quote_style: None, span: Span(Location(6,27)..Location(6,42)) })))], alias: Some(TableAlias { name: Ident { value: "comment", quote_style: None, span: Span(Location(6,47)..Location(6,54)) }, columns: [] }) } in create_relation
```
Some are less clear about where the issue lies, like:
```
The context currently only supports a single SQL statement
```

I think we should prepend it with `Unsupported Query.`, just to be clear about where the error lies.

**Review by lukekim — APPROVED** [review]
