### PR TITLE
sqlite: friendly error message for unsupported types

### LINKED ISSUE #878: Errors when a data backend does not support a type are unclear and inconsistent
**Describe the bug**
We should have consistent and clear error messages when a data backend does not support a data type. We should also clearly distinguish between a lack of support in our code and a true limitation of the backend store. The error should also link to documentation on backends and supported types.

**To Reproduce**

Run `spice run` with the following datasets:

```
- from: spice.ai/eth.recent_transactions
  name: eth_recent_transactions
  acceleration:
    enabled: true
    refresh_mode: full
    refresh_interval: 10s
    engine: duckdb

- from: spice.ai/eth.recent_transactions
  name: eth_recent_transactions
  acceleration:
    enabled: true
    refresh_mode: full
    refresh_interval: 10s
    engine: sqlite
```

Observe the inconsistent and nasty error messages:

```
thread '<unnamed>' panicked at /Users/mitch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.7/src/backend/sqlite/table.rs:181:41:
not implemented: Array is not available in Sqlite.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
Nested list is not supported yet.
thread 'tokio-runtime-worker' panicked at /Users/mitch/.cargo/git/checkouts/duckdb-rs-7cfb8083041eafcf/4e1cf06/src/vtab/arrow.rs:381:13:
not yet implemented
fatal runtime error: Rust panics must be rethrown
os: process already finished
```

### PR DESCRIPTION
**Pull request by sgrebnov**
sqlite: friendly error message for unsupported types. Fixes https://github.com/spiceai/spiceai/issues/878

image

### CODE REVIEW

File: crates/runtime/src/databackend/sqlite.rs [hunk 1]
```diff
@@ -75,7 +78,20 @@ impl DataPublisher for SqliteBackend {
     fn add_data(&self, _dataset: Arc<Dataset>, data_update: DataUpdate) -> AddDataResult {
         let pool = Arc::clone(&self.pool);
         let name = self.name.clone();
+
         Box::pin(async move {
+            if let Some(batch) = data_update.data.first() {
+                for field in batch.schema().fields() {
+                    if field.data_type().is_nested() {
+                        let field_name = self.name.clone() + "." + field.name();
```
Comment (phillipleblanc) [inline crates/runtime/src/databackend/sqlite.rs]: use `format!()` to create the field_name

Comment (sgrebnov) [reply crates/runtime/src/databackend/sqlite.rs]: Updated

**Review by phillipleblanc — APPROVED** [review]
