### PR TITLE
Stable data for AddDataRequest

### LINKED ISSUE #345: Go test failing (getAddDataRequest)
There seems to be a problem with the `go test spiced & spice` action, the test can fail without any actual change in the related code.

The bug occured in my PR for the python linting : https://github.com/spiceai/spiceai/runs/3972036943?check_suite_focus=true .

The relevant output is at line 30 : 

```
=== RUN   TestObservations/getAddDataRequest()
    snapshotter.go:20: snapshot not equal:
        --- Previous
        +++ Current
        @@ -1,10 +1,10 @@
         time,event_stream_duration,event_stream_guest_count,event_stream_ticket_price,event_stream_event_type-dinner,event_stream_event_type-party,event_stream_event_type-dance,event_stream_event_type-concert,event_stream_event_type-football_game,event_stream_target_audience-employees,event_stream_target_audience-investors,event_stream_target_audience-cohort_a,event_stream_tagA,event_stream_tagB,event_stream_tagC
        -1610057400,10,10,15,1,0,0,0,0,0,1,0,1,1,1
        -1610057800,20,11,30,0,1,0,0,0,1,0,0,1,0,0
        -1610058200,30,12,45,0,0,1,0,0,1,0,0,1,0,1
        -1610058600,40,13,60,0,0,0,1,0,0,0,1,0,0,1
        -1610059000,50,14,75,0,0,0,0,1,0,1,0,0,1,1
        -1610059400,60,15,90,0,0,1,0,0,1,0,0,0,0,0
        -1610059800,70,16,105,0,0,0,1,0,0,0,1,0,0,0
        -1610060200,80,17,120,0,0,0,0,1,0,1,0,1,0,1
        +1610057400,10,10,15,0,1,0,1,0,0,0,0,1,1,1
        +1610057800,20,11,30,1,0,0,0,1,0,0,0,1,0,0
        +1610058200,30,12,45,1,0,0,0,0,1,0,0,1,0,1
        +1610058600,40,13,60,0,0,1,0,0,0,1,0,0,0,1
        +1610059000,50,14,75,0,1,0,0,0,0,0,1,0,1,1
        +1610059400,60,15,90,1,0,0,0,0,1,0,0,0,0,0
        +1610059800,70,16,105,0,0,1,0,0,0,1,0,0,0,0
        +1610060200,80,17,120,0,1,0,0,0,0,0,1,1,0,1
         
        
--- FAIL: TestObservations (0.02s)
    --- PASS: TestObservations/getData()_-_All_headers_with_preview (0.01s)
    --- PASS: TestObservations/getData()_-_Select_headers_with_preview (0.00s)
    --- PASS: TestObservations/getData()_-_With_tags (0.00s)
    --- PASS: TestObservations/getData()_-_With_categories (0.00s)
    --- FAIL: TestObservations/getAddDataRequest() (0.00s)
```

### PR DESCRIPTION
**Pull request by lukekim**
Fixes #345

This change sets stable ordering for all data used in addDataRequest, so that it's always consistent when sent to the AI engine and for use in tests.

Also improves performance in the addDataRequest path by moving several lists to one-time initialization instead of in getters.

### CODE REVIEW

File: pkg/aiengine/data_test.go [hunk 1]
```diff
@@ -68,16 +68,28 @@ func testGetAddDataRequestFunc() func(*testing.T) {
...
 		assert.Equal(t, "event-categories", addDataRequest.Pod)
 
-		snapshotter.SnapshotT(t, addDataRequest.CsvData)
+		csvData := strings.TrimSpace(addDataRequest.CsvData)
+
+		csvLines := strings.Split(csvData, "\n")
+		if assert.Len(t, csvLines, len(newObservations)+1, "number of csv lines does not match observations") {
+			for _, csvLine := range csvLines {
+				csvFields := strings.Split(csvLine, ",")
+				if !assert.Len(t, csvFields, 15, "number of fields does not match state") {
```
Comment (Corentin-pro) [inline pkg/aiengine/data_test.go:86]: I was wondering why 15 here, I looked at `event_stream_categories` in the `test/assets/data` both csv and json and couldn't find this number of fields. What am I missing? (I was looking at the posibility to avoid hardcoded number.)

Comment (lukekim) [reply pkg/aiengine/data_test.go:86]: This calculation is (being one-hot-encoded):
time + number of measurements + number of categories * number of category values + number of tags * number of tag values.

It could be calculated, but I tend to not mind hardcoded values for tests if it is from static data, because the calculation can also be wrong.

**Review by Corentin-pro — APPROVED** [review]
This is indeed quiet a PR, I tried as much as possible to see al the changed code, I feel the core change is in `dataspace.go` with the sorting. I am wondering about time series : will we need specific order later? Could english date format made a problem somewhere (I can see a `Value` list being sorted)?

Those question are not relevant today anyway. Everything looks OK to me.

**Comment by lukekim** [comment]
@Corentin-pro I don't think we need a specific order. As long as the order is always consistent when it's sent to the AI engine and when used in tests, we should be good. This is true for Values, so long as they are always in consistent order, it doesn't matter what order they are in.

This might be different to sorting data in the dashboard or CLI, for user facing data, where locale is important to consider.
