### PR TITLE
Use custom dialect rule for flight federated request

### LINKED ISSUE #1765: BUG: unparse result of "CAST (a AS DATETIME)" not working for dremio connector as DATETIME is not a valid type in dremio
run tpc-h query 1 in runtime bench, an error will pop up caused by this.

tpch 1,3,4,5,6,7,8,10,14,20 are impacted by this.

### LINKED ISSUE #1768: BUG: unparsed interval does not work for dremio connector as the dialect doesn't support `interval '1 month'` etc
This affects the following benchmark queries:
    `tpch_q4`

related to #1580

### PR DESCRIPTION
**Pull request by y-f-u**
## 🗣 Description

Use custom dialect rule for spice.ai federated request.

## 🔨 Related Issues

fixes #1765 
fixes #1768 

Results of new bench test

```
+--------------------------------------+---------------+---------------+----------------+--------+-----------------+-----------------+------------+----------------+----------------------+
| run_id                               | started_at    | finished_at   | query_name     | status | min_duration_ms | max_duration_ms | iterations | commit_sha     | branch_name          |
+--------------------------------------+---------------+---------------+----------------+--------+-----------------+-----------------+------------+----------------+----------------------+
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023544945 | 1721023552447 | tpch_q1        | passed | 1396            | 1693            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023552447 | 1721023564223 | tpch_q2        | passed | 1727            | 2765            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023564223 | 1721023578653 | tpch_q3        | passed | 1503            | 4399            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023578653 | 1721023589293 | tpch_q5        | passed | 1399            | 2598            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023589293 | 1721023599055 | tpch_q6        | passed | 1267            | 3395            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023599055 | 1721023607334 | tpch_q7        | passed | 1416            | 1897            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023607334 | 1721023621562 | tpch_q10       | passed | 1741            | 4370            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023621563 | 1721023631154 | tpch_q11       | passed | 1140            | 3613            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023631154 | 1721023637644 | tpch_q12       | passed | 1126            | 1744            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023637645 | 1721023647576 | tpch_q14       | passed | 1229            | 3068            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023647576 | 1721023664134 | tpch_q17       | passed | 2706            | 5070            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023664134 | 1721023673704 | tpch_q18       | passed | 1741            | 2397            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023673704 | 1721023684627 | tpch_q19       | passed | 1543            | 3972            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023684627 | 1721023715060 | tpch_q21       | passed | 4682            | 10875           | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023715060 | 1721023720692 | tpch_simple_q1 | passed | 989             | 1203            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023720692 | 1721023728525 | tpch_simple_q2 | passed | 1222            | 2586            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023728525 | 1721023735029 | tpch_simple_q4 | passed | 1125            | 1894            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
| 811c6565-537a-4fd8-ba38-249297d6ef85 | 1721023735029 | 1721023741684 | tpch_simple_q5 | passed | 1126            | 1796            | 5          | f1517b8d-dirty | custom-scalar-to-sql |
+--------------------------------------+---------------+---------------+----------------+--------+-----------------+-----------------+------------+----------------+----------------------+
```

### CODE REVIEW

File: crates/data_components/src/flight/federation.rs [hunk 1]
```diff
@@ -45,6 +46,71 @@ impl FlightTable {
     }
 }
 
+struct SpiceAIDialect {}
```
Comment (lukekim) [inline crates/data_components/src/flight/federation.rs]:
```suggestion
struct SpiceCloudPlatformDialect {}
```

File: crates/data_components/src/flight/federation.rs [hunk 2]
```diff
@@ -56,7 +56,13 @@ impl SQLExecutor for FlightTable {
...
 
     fn dialect(&self) -> Arc<dyn Dialect> {
-        Arc::new(DefaultDialect {})
+        Arc::new(
+            CustomDialectBuilder::new()
+                .with_identifier_quote_style('"')
+                .with_use_timestamp_for_date64(true)
+                .with_interval_style(IntervalStyle::SQLStandard)
+                .build(),
+        )
```
Comment (phillipleblanc) [inline crates/data_components/src/flight/federation.rs]: Have the FlightTable accept a dialect from the constructor

**Review by sgrebnov — APPROVED** [review]
