### PR TITLE
fix: Ensure vector search UDTF respects the supplied projection

### LINKED ISSUE #6815: test `models::search::test_multi_column_search` is disabled
## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### LINKED ISSUE #6816: test `models::search::test_multi_column_w_existing_embedding` is disabled
## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### LINKED ISSUE #6817: test `models::search::test_search_with_cache` is disabled
## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### LINKED ISSUE #6844: `vector_search` UDTF error: Expected and actual number of fields mismatch
## Describe the bug

_A clear and concise description of what the bug is._

When attempting to use the `vector_search` UDTF to perform a search, the following error occurs:

```console
sql> select c_custkey from vector_search(customer, 'customer');
Internal Error: Unexpected internal error. Use '.error' for details.
sql> .error
An internal error occurred.
Schema mismatch: Expected and actual number of fields in the query result don't match: expected 1, received 2
```

## To Reproduce

_Steps to reproduce the behavior:_

1. Setup a TPCH customer dataset with embeddings
2. Perform a search query as `select c_custkey from vector_search(customer, 'customer');`
3. See error

## Expected behavior

_A clear and concise description of what you expected to happen._

The vector search should complete successfully.

### PR DESCRIPTION
**Pull request by peasee**
## 📝 Summary

* Ensures that the supplied projection into the `vector_search` UDTF is respected, including removing the score column from the projection.
  * To accomplish this, we need to wrap the projection with score calculation into a subquery, otherwise DataFusion will eagerly drop the column because it is unused in the final projection. The query would then fail, because we still need to sort on `score` even if it is not projected.
* Re-enables some disabled search tests

## 🔗 Related

* Closes #6844
* Closes #6816
* Closes #6815

### CODE REVIEW

File: crates/runtime/src/embeddings/udtf.rs [hunk 1]
```diff
@@ -551,6 +564,13 @@ impl TableProvider for VectorSearchUDTFProvider {
...
 
-        state.create_physical_plan(&sort).await
+        // wrap the score calculation in a subquery before final projection, to avoid collapsing away the score calculation.
+        let score_subquery =
+            LogicalPlan::SubqueryAlias(SubqueryAlias::try_new(Arc::new(sort), "tbl")?);
+
+        let final_proj =
+            LogicalPlan::Projection(Projection::try_new(final_expr, Arc::new(score_subquery))?);
+
+        state.create_physical_plan(&final_proj).await
```
Comment (phillipleblanc) [inline crates/runtime/src/embeddings/udtf.rs:574]: Why do we need to do the score calculation in a sub-query? That doesn't make sense to me.

Comment (phillipleblanc) [reply crates/runtime/src/embeddings/udtf.rs:574]: Talked with William offline.

> this is what is looks like with my change:
> SELECT "name" FROM (SELECT "name", (1.0 - array_cosine_distance([... lots of floats ...]::FLOAT[1536], "path_embedding")) AS "score" FROM "docs" ORDER BY "score" DESC NULLS LAST) AS "tbl"
> If you don't wrap it in a subquery, before the final projection you'd have:
>  
> SELECT "name", (1.0 - array_cosine_distance([... lots of floats ...]::FLOAT[1536], "path_embedding")) AS "score" FROM "docs" ORDER BY "score" DESC NULLS LAST
> The final projection is just name, so the SELECT turns into:
> Plain Text
> SELECT "name" FROM "docs" ORDER BY "score" DESC NULLS LAST

Doing this without a subquery should mean rewriting the expression to go into the ORDER BY clause directly, but putting it into a subquery allows us to keep the computation in the projection node and choose whether we want to expose it.

**Review by phillipleblanc — APPROVED** [review]
