### PR TITLE
Validate lag_exceeds_shard_retention_behavior param in DynamoDB

### LINKED ISSUE #9356: DynamoDB: invalid lag_exceeds_shard_retention_behavior is silently accepted
## Describe the bug

`lag_exceeds_shard_retention_behavior` on the DynamoDB connector appears to silently accept invalid values and fall back to the default behavior (`error`) instead of failing fast with a configuration error.

I used `lag_exceeds_shard_retention_behavior: ready_sometimes` (invalid), and runtime startup did not report any parameter validation error.

## To Reproduce

1. Create a DynamoDB table with streams enabled.
2. Use a Spicepod dataset with an invalid value for `lag_exceeds_shard_retention_behavior`.
3. Run `spice run`.
4. Observe that the dataset registers and runtime does not report invalid config for this parameter.

Example Spicepod (minimal repro):

```yaml
version: v1
kind: Spicepod
name: v1111-dynamodb-lag-invalid

datasets:
  - from: dynamodb:orders-v1111-focus
    name: orders_stream_invalid
    params:
      dynamodb_aws_region: ${env:AWS_REGION}
      dynamodb_aws_auth: key
      dynamodb_aws_access_key_id: ${env:AWS_ACCESS_KEY_ID}
      dynamodb_aws_secret_access_key: ${env:AWS_SECRET_ACCESS_KEY}
      ready_lag: 1h
      lag_exceeds_shard_retention_behavior: ready_sometimes
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
      refresh_mode: changes
      on_conflict:
        id: upsert
```

## Expected behavior

Invalid enum values for `lag_exceeds_shard_retention_behavior` should fail startup / dataset initialization with a clear error, e.g.:

`Invalid lag_exceeds_shard_retention_behavior: 'ready_sometimes'. Valid values: error, ready_before_load, ready_after_load`

### Spicepod

(see repro snippet above)

### Output of `describe table`

N/A for this repro.

### Output of `explain query`

```bash
+---------------------+----------------------------------------------------------------------------------------+
| plan_type           | plan                                                                                   |
+---------------------+----------------------------------------------------------------------------------------+
| logical_plan        | Projection: count(Int64(1)) AS count(*)                                                |
|                     |   Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]                                    |
|                     |     TableScan: orders_stream_invalid projection=[]                                     |
| physical_plan_error | External error: Acceleration not ready; loading initial data for orders_stream_invalid |
+---------------------+----------------------------------------------------------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice 1.11.1`
- spiced version: `v1.11.1-build.18370b08a+models.metal`
- OS info: `Darwin 25.2.0 arm64`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [x] No

**If possible, run `spiced` with DEBUG log level**

Ran with standard log level for this report.

## Screenshots

N/A

## Additional context

Observed runtime snippet (no validation error for invalid value):

```text
INFO runtime::init::dataset: Dataset orders_stream_invalid registered (dynamodb:orders-v1111-focus), acceleration (duckdb:file, changes), results cache enabled.
```

I think this may be due to parse errors being swallowed and defaulting in `dynamodb.rs`:

- `LagExceedsShardRetentionBehavior::from_str(v).ok()`
- `.unwrap_or_default()`

which appears to ignore invalid parameter values and use default behavior silently.

### PR DESCRIPTION
**Pull request by ewgenius**
## 📝 Summary

closes #9356 

Return an error if the parameter value is invalid, instead of silently falling back to the default. Error message includes valid values and dataset context.

This pull request refines how the `lag_exceeds_shard_retention_behavior` parameter is handled in the `DynamoDB` data connector. The new implementation improves error handling and validation by explicitly matching on the parameter's presence and providing clear error messages for invalid values.

**Parameter handling and error reporting improvements:**

* Updated the extraction of `lag_exceeds_shard_retention_behavior` to use a `match` statement, providing explicit error messages if the value is invalid and defaulting gracefully when absent. This enhances configuration validation and debugging for users.

### CODE REVIEW

File: crates/runtime/src/dataconnector/dynamodb.rs [hunk 1]
```diff
@@ -412,13 +412,26 @@ impl DataConnector for DynamoDB {
...
-            .unwrap_or_default();
+        {
+            ExposedParamLookup::Present(value_str) => {
+                match LagExceedsShardRetentionBehavior::from_str(value_str) {
+                    Ok(behavior) => behavior,
+                    Err(e) => {
+                        tracing::error!(
+                            dataset = %dataset.name,
+                            error = %e,
+                            "Failed to parse 'lag_exceeds_shard_retention_behavior' parameter"
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/dynamodb.rs]: This should still fall back to the default behavior of `LagExceedsShardRetentionBehavior::default()`, which is `error`, and this should be logged as a warning - not an error. The message should also include what the default behavior will be.

**Review by Jeadie — APPROVED** [review]

**Review by sgrebnov — APPROVED** [review]
