### PR TITLE
fix: Expose ODBC task errors if error is before data stream begins

### LINKED ISSUE #1920: Bug: Athena ODBC TPCH Q4 schema channel closed error
**Describe the bug**

When running TPCH Q4 in AWS Athena as an ODBC data connector, the query fails with a REPL and `spiced` error:

```
error: Execution error: Unable to query arrow: Internal communication channel error: Schema channel closed unexpectedly; code: QueryExecutionErro
```

**To Reproduce**

1. Configure AWS Athena as an ODBC connector with TPCH tables and data
2. Execute TPCH Q4

**Expected behavior**

The query should execute and return results, as it does in the Athena console.

**Spicepod**
```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: odbc:tpch.customer
  name: customer
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.orders
  name: orders
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.nation
  name: nation
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.region
  name: region
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.supplier
  name: supplier
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.part
  name: part
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.partsupp
  name: partsupp
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.lineitem
  name: lineitem
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
```

**spice, spiced, OS info**
- spice version: `v0.15.2-alpha-rc.10ffdb8c`
- spiced version: `v0.15.2-alpha-rc.10ffdb8c`
- OS info: `Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux`

**Have you tried this on the latest `trunk` branch?**

Yes

**Context**

The query succeeds as expected when using acceleration (Arrow).

### PR DESCRIPTION
**Pull request by peasee**
## 🗣 Description

In ODBC connections, if the worker task fails before the data stream begins the only returned error is a generic "Schema channel closed unexpectedly."

This update makes it so when the schema channel is lost, we expect the task to have finished and errored - because there is no other situation where the schema channel would have been lost.

## 🔨 Related Issues

* Closes #1920 
* Also affects any other ODBC driver in a query that experienced an error before the data stream began.
* Other issues will need to be raised as a result of the errors that were being hidden.

### CODE REVIEW

File: crates/db_connection_pool/src/dbconnection/odbcconn.rs [hunk 1]
```diff
@@ -197,13 +197,11 @@ where
...
-        let schema = match schema_rx.recv().await {
-            Some(s) => Ok::<_, GenericError>(s),
-            None => Err(Error::ChannelError {
-                message: "Schema channel closed unexpectedly".to_string(),
-            }
-            .into()),
-        }?;
+        let Some(schema) = schema_rx.recv().await else {
+            // if the channel drops, the task errored
+            let err = join_handle.await?.expect_err("Task should have errored");
```
Comment (phillipleblanc) [inline crates/db_connection_pool/src/dbconnection/odbcconn.rs]: Is it appropriate to panic here if for some reason it didn't error?

**Review by phillipleblanc — APPROVED** [review]
