### PR TITLE
fix: Correctly prefix missing required parameters

### LINKED ISSUE #2081: Bug: Databricks gives poor error UX for misconfigured spicepod
**Describe the bug**

When using a misconfigured spicepod for databricks that omits the `token` parameter, the CLI provides a warning advising the user to add the parameter:

```
WARN runtime: customer Invalid configuration for databricks. Missing required parameter: token
```

However, the parameter is not `token`, it is `databricks_token`. This results in an additional error after a user adds the `token` parameter:

```
WARN runtime::dataconnector: Ignoring parameter token: must be prefixed with `databricks_` for databricks
```

This results in a poor UX.

**To Reproduce**

1. Configure a Databricks connection without any `*token` parameter
2. Observe warning advising to add `token` parameter
3. Add parameter
4. Observe warning advising that `token` must be prefixed with `databricks_`

**Expected behavior**

The first warning should advise the user to add the `databricks_token` parameter, not the `token` parameter.

**Spicepod**
```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: databricks:samples.tpch.customer
  name: customer
  params:
    databricks_endpoint: adb-4473752745667967.7.azuredatabricks.net
    mode: spark_connect
```

**Have you tried this on the latest `trunk` branch?**

Yes

### PR DESCRIPTION
**Pull request by peasee**
## 🗣 Description

* Ensures that missing required parameters correctly have a prefix applied (if they use one).

## 🔨 Related Issues

* Closes #2081

### CODE REVIEW

**Review by lukekim — APPROVED** [review]

File: crates/runtime/src/dataconnector.rs [hunk 1]
```diff
@@ -463,9 +463,15 @@ impl Parameters {
             }
 
             if parameter.required && missing {
+                let param = if parameter.r#type.is_prefixed() {
+                    format!("{full_prefix}{}", parameter.name)
+                } else {
+                    parameter.name.to_string()
+                };
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector.rs:470]: This could user the `user_param` method

**Review by phillipleblanc — APPROVED** [review]
