### PR TITLE
Validate Github Connector resource existence before building the github connector graphql table

### LINKED ISSUE #3444: Bug: Github Data Connector does NOT error or warn when source repo does not exist
## Describe the bug

If  repo source  is misspelled/incorrect (does not exist) the data connector reports NO errors and just loads 0 rows:

```console
2024-11-11T17:56:15.654886Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset datafusion_pulls
2024-11-11T17:56:16.057679Z  INFO runtime::accelerated_table::refresh_task: Loaded 0 rows for dataset datafusion_pulls in 402ms.
```

## To Reproduce

```
- from: github:github.com/apache/datafusion12123sdfsdf/pulls
    name: datafusion_pulls
    params:
      github_token: ${secrets:GITHUB_TOKEN}
      github_query_mode: search
    time_column: updated_at
    acceleration:
      enabled: true
      refresh_sql: |
        SELECT * FROM datafusion_pulls where updated_at > '2024-10-01'
```

### PR DESCRIPTION
**Pull request by Sevenannn**
## 📝 Summary

When creating the graphql table provider for github connectors, send an health check query to validate the table exists before building the graphql table.

Add an optional field `health_check_query` to the GraphQLTableProviderBuilder. When it is provide, send the health check query to validate the table exists before sending the query for fetching data

This addresses the issue where the non-exist table cannot be caught by using search queries, which leads to the hardship in determining whether it's the table non-exist or it's the table really empty.

For Invalid Config
```yaml
  - from: github:github.com/apache/datafusion/pulls
    name: datafusion_pulls
    params:
      github_token: ${secrets:GITHUB_TOKEN}
      github_query_mode: search
    time_column: updated_at
    acceleration:
      enabled: true
      refresh_sql: |
        SELECT * FROM datafusion_pulls where updated_at > '2024-10-01'
```

User Error
```
2025-05-01T23:55:51.169134Z  WARN runtime::init::dataset: Failed to load the dataset datafusion_pulls (github).
The API returned a 'NOT_FOUND' error.
Verify the requsted resource exists and is accessible.
Could not resolve to a Repository with the name 'apache/datafusion123'.
```

## 🔗 Related

- Close: https://github.com/spiceai/spiceai/issues/3444

### CODE REVIEW

File: crates/data_components/src/graphql/provider.rs [hunk 1]
```diff
@@ -69,7 +69,11 @@ impl GraphQLTableProviderBuilder {
         self
     }
 
-    pub async fn build(self, query_string: &str) -> Result<GraphQLTableProvider> {
+    pub async fn build(
+        self,
+        query_string: &str,
+        inspection_query: Option<GraphQLQuery>,
```
Comment (phillipleblanc) [inline crates/data_components/src/graphql/provider.rs]: Add this to the builder itself, i.e. `GraphQLTableProviderBuilder::new(..).with_inspection_query().build()`.

File: crates/data_components/src/graphql/provider.rs [hunk 2]
```diff
@@ -88,6 +92,21 @@ impl GraphQLTableProviderBuilder {
             )
             .await?;
 
+        if result.records.is_empty() {
+            if let Some(mut inspection_query) = inspection_query {
```
Comment (phillipleblanc) [inline crates/data_components/src/graphql/provider.rs]: I wouldn't call this an inspection query, maybe `health_check_query`?

File: crates/data_components/src/graphql/provider.rs [hunk 3]
```diff
@@ -88,6 +92,21 @@ impl GraphQLTableProviderBuilder {
             )
             .await?;
 
+        if result.records.is_empty() {
```
Comment (phillipleblanc) [inline crates/data_components/src/graphql/provider.rs]: If we have a health check query, we should just use that directly instead of trying the other query first.

File: crates/runtime/src/dataconnector/github/mod.rs [hunk 4]
```diff
@@ -158,9 +160,32 @@ impl Github {
...
+            r#"{{
+            repositoryCheck: repository(owner: "{owner}", name: "{repo}") {{
+                id
+                nameWithOwner
+            }}
+        }}"#,
+        );
+
+        let query_arc = Arc::from(inspection_query_string);
+        let mut inspection_query = GraphQLQuery::try_from(query_arc).map_err(|e| {
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/github/mod.rs]: There isn't a way to specify the json pointer directly on here? i.e. GraphQLQuery::try_from(query_arc).map_err(..).with_json_pointer()?

Comment (phillipleblanc) [reply crates/runtime/src/dataconnector/github/mod.rs]: If not we should add it.

**Review by phillipleblanc — APPROVED** [review]
