### PR TITLE
Fix issue in limit clause for the Github Data connector

### LINKED ISSUE #6017: `.acceleration.refresh_sql` ignores  `LIMIT n` for Github connector
## Describe the bug
The underlying GraphQL pagination is not working for the github connector. When the LIMIT > pagination size (github defaults to 100), the connector incorrectly early exits. 

## To Reproduce
```yaml
datasets:
  - from: github:github.com/spiceai/spiceai/pulls
    name: spiceai.issues
    params:
      github_token: ${secrets:GITHUB_TOKEN}
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM spiceai.issues limit 202
```
Notice
```shell
2025-05-28T01:51:11.396805Z  INFO runtime::accelerated_table::refresh_task: Loaded 100 rows (491.41 kiB) for dataset spiceai.issues in 2s 841ms.
```

### PR DESCRIPTION
**Pull request by Advayp**
## 📝 Summary
- Fixes an issue where any `LIMIT` over the maximum Github pagination size is effectively ignored and reduced to that max pagination size. 

## 🔗 Related

- Closes #6017

## Output
`spicepod.yaml`:
```yaml
datasets:
  - from: github:github.com/spiceai/spiceai/pulls
    name: spiceai.issues
    params:
      github_token: ${secrets:GITHUB_TOKEN}
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM spiceai.issues limit 202
```

Before:
```
2025-05-28T01:51:11.396805Z  INFO runtime::accelerated_table::refresh_task: Loaded 100 rows (491.41 kiB) for dataset spiceai.issues in 2s 841ms.
```

After:
```
2025-07-14T19:03:20.751068Z  INFO runtime::accelerated_table::refresh_task: Loaded 202 rows (973.83 kiB) for dataset spiceai.issues in 13s 304ms.
```

### CODE REVIEW

**Review by Sevenannn — DISMISSED** [review]

File: crates/data_components/src/graphql/client.rs [hunk 1]
```diff
@@ -703,6 +703,7 @@ impl GraphQLQuery {
 
 pub(crate) struct GraphQLQueryResult {
     pub(crate) records: Vec<RecordBatch>,
+    #[allow(dead_code)] // May be needed at a later time, so ignore the warning for now
     record_count: usize,
```
Comment (peasee) [inline crates/data_components/src/graphql/client.rs]: If record count is unused, prefer prefixing it with `_` instead of allowing dead code:

`_record_count`

File: crates/runtime/tests/github/mod.rs [hunk 2]
```diff
@@ -28,6 +28,119 @@ use crate::{
     configure_test_datafusion, init_tracing, run_query_and_check_results,
     utils::test_request_context,
 };
+use tracing_subscriber::{EnvFilter, Registry, fmt, layer::SubscriberExt};
+
+// To ensure pagination with limits works correctly, capture the logs and store it in a buffer.
+// This must be thread-local to prevent contamination between snapshots.
+thread_local! {
+    static LOG_BUFFER: RefCell<String> = const {RefCell::new(String::new()) }
+}
```
Comment (peasee) [inline crates/runtime/tests/github/mod.rs]: this seems like an overly complicated test. given github uses the graphql connector, could we not just mock a graphql service with a known number of items and apply limits onto the results? it also avoids any potential key rate limiting with github, because these tests run on every PR.

example mock: https://github.com/spiceai/spiceai/blob/trunk/crates/runtime/tests/graphql/mod.rs#L67

**Review by peasee — APPROVED** [review]
