### PR TITLE
Better spark data connector error

### LINKED ISSUE #1468: Improve Spark connection error
**Describe the bug**

I see the following error when running Spice with Spark dataset that unable to connect to Spark

>2024-05-22T01:03:34.057228Z  WARN runtime: Tonic Transport error: transport error

**To Reproduce**
1. Create the following Spicepod
```yaml
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
  - from: spark:nyc_taxi_trip
    name: nyc_taxi_trip
    params:
      spark_remote: sc://does-no-exist:15002
```
1. Run Spice
1. See warning

>Spice.ai runtime starting...
2024-05-22T01:05:30.831888Z  INFO spiced: Metrics listening on 127.0.0.1:9000
2024-05-22T01:05:30.984759Z  WARN runtime: Tonic Transport error: transport error
2024-05-22T01:05:46.069022Z  WARN runtime: Tonic Transport error: transport error
2024-05-22T01:06:01.154857Z  WARN runtime: Tonic Transport error: transport error

**Expected behavior**
The warning points that Spark connector is unable to connect to Spark server

### PR DESCRIPTION
**Pull request by Sevenannn**
* Validate Spark connect endpoint before connection
* Use DataConnector Error to give better error context for spark data connector error

Before:
image
image
image
image

After:
image
image
image
image

- close https://github.com/spiceai/spiceai/issues/1468

### CODE REVIEW

File: crates/runtime/src/dataconnector/spark.rs [hunk 1]
```diff
@@ -88,8 +90,24 @@ impl DataConnectorFactory for Spark {
         params: Arc<Option<HashMap<String, String>>>,
     ) -> Pin<Box<dyn Future<Output = super::NewDataConnectorResult> + Send>> {
         Box::pin(async move {
-            let spark_connector = Spark::new(Arc::new(secret), params).await?;
-            Ok(Arc::new(spark_connector) as Arc<dyn DataConnector>)
+            match Spark::new(Arc::new(secret), params).await {
+                Ok(spark_connector) => Ok(Arc::new(spark_connector) as Arc<dyn DataConnector>),
+                Err(e) => match e {
+                    Error::UnableToConstructSparkConnect { source } => {
+                        Err(DataConnectorError::UnableToConnectInternal {
```
Comment (y-f-u) [inline crates/runtime/src/dataconnector/spark.rs:108]: is this supposed to be configure error, and the below one to be internal?

Comment (Sevenannn) [reply crates/runtime/src/dataconnector/spark.rs:108]: This is supposed to be an internal error. Because before where UnableToConstructSparkConnect emitted all configurations are validated, and those errors relevant to invalid configurations are covered in _ =>  case

Comment (Sevenannn) [reply crates/runtime/src/dataconnector/spark.rs:108]: I get what you mean. let me update something

**Review by y-f-u — APPROVED** [review]

**Review by lukekim — APPROVED** [review]
