### PR TITLE
fix: google embeddings fail to load

### LINKED ISSUE #8823: Google embeddings fail to load
## Describe the bug

spicepod

```yaml
version: v1
kind: Spicepod
name: google-models

datasets:
  - from: github:github.com/spiceai/spiceai/issues
    name: spiceai.issues
    params:
      github_token: ${secrets:GITHUB_TOKEN}
    acceleration:
      enabled: true
      refresh_sql: select * from spiceai.issues limit 10
    columns:
      - name: body
        embeddings:
          - from: gemini_embeddings
            row_id:
              - id
            chunking:
              enabled: true
              target_chunk_size: 250
              overlap_size: 32
      - name: title
        embeddings:
          - from: gemini_embeddings

embeddings:
  - from: google:text-embedding-004
    name: gemini_embeddings
    params:
      google_api_key: ${ secrets:GEMINI_API_KEY }
```

```console
2026-01-07T01:02:19.825474Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset spiceai.issues
2026-01-07T01:02:20.817965Z  WARN runtime::accelerated_table::refresh_task: Failed to load data for dataset spiceai.issues (github): Failed to get data from the connector. External error: External error: Failed to create embedding. Google embedding error: API error: API request failed with status 400: {
  "error": {
    "code": 400,
    "message": "* BatchEmbedContentsRequest.requests: requests must not be empty\n",
    "status": "INVALID_ARGUMENT"
  }
}
. Ensure the dataset configuration is valid, and try again.
```

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## 📝 Summary

Return empty vec of embedding for empty input, skip api request (same as already being done for bedrock embedding)

## 🔗 Related

Closes #8823

### CODE REVIEW

**Comment by Jeadie** [comment]
Please retarget this to `trunk`

**Comment by Jeadie** [comment]
It does not appear that this PR relates to #8823?

File: crates/llms/src/google/embed.rs [hunk 1]
```diff
@@ -50,6 +50,11 @@ impl Embed for EmbedGoogle {
             }
         };
 
+        if texts.is_empty() {
+            tracing::debug!("Embedding input is empty, returning empty vector");
+            return Ok(vec![]);
+        }
+
```
Comment (AyushAgrawal-A2) [inline crates/llms/src/google/embed.rs:57]: @Jeadie 
This fixes the google embeddings error reported in issue 8823.
I have added the same check in model2vec as well.
Empty text inputs should not be sent for embedding.

**Review by Jeadie — APPROVED** [review]
