### PR TITLE
Make DynamoDB connectivity errors more specific and actionable

### LINKED ISSUE #6290: Bug: Make DynamoDB connector connection error more specific and actionable
## Describe the bug

There is the same error in multiple different cases when unable to connect to DynamoDB table. The connection error must be more specific and actionable

>2025-06-20T19:04:09.617794Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
service error

1. invalid table name (does not exist)
1. invalid credentials, for example expired dynamodb_aws_session_token param
1. dynamodb_aws_session_token was not provided/missing

## To Reproduce

Try using invalid table name, expired session token, invalid access key.

```yaml
datasets:
- from: dynamodb:sales_transactions
  name: sales_transactions
  params:
      dynamodb_aws_region: ${secrets:SPICE_AWS_REGION}
      dynamodb_aws_access_key_id: ${secrets:SPICE_AWS_ACCESS_KEY_ID}
      dynamodb_aws_secret_access_key: ${secrets:SPICE_AWS_SECRET_ACCESS_KEY}
      dynamodb_aws_session_token: ${secrets:SPICE_AWS_SESSION_TOKEN}
```

>2025-06-20T19:04:09.617794Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
service error

### PR DESCRIPTION
**Pull request by sgrebnov**
## 📝 Summary

**Before**

>2025-06-21T01:23:39.320832Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
service error

>2025-06-21T01:24:20.953444Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
dispatch failure

**After**

>2025-06-21T01:20:10.869384Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
Failed to fetch table information.
Error: The security token included in the request is invalid.
Verify configuration and try again.
For details, visit https://spiceai.org/docs/components/data-connectors/dynamodb

>2025-06-21T01:50:41.444866Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
Failed to fetch table information.
Error: Connection error. This may indicate an invalid region setting, connectivity, or access issue.
Details: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })), connection: Unknown }
Verify configuration and try again.
For details, visit https://spiceai.org/docs/components/data-connectors/dynamodb

Error: Requested resource not found: Table: sales_transactions2 not found
Error: The security token included in the request is invalid.
Error: The security token included in the request is expired

## 🔗 Related

Closes  https://github.com/spiceai/spiceai/issues/6290

### CODE REVIEW

File: crates/data_components/src/dynamodb/provider.rs [hunk 1]
```diff
@@ -99,6 +98,31 @@ impl DynamoDBTableProvider {
...
+                    // Error metadata message (if present) contains a specific error message
+                    if let Some(err_msg) = err.meta().message() {
+                        return err_msg.into();
+                    }
+                }
+
+                // If a connection error occurs, provide detailed information available via Debug format.
+                // This happens when the request failed during dispatch. An HTTP response was not received, thus no error code or message is available.
+                if let Some(conn_error) = source.downcast_ref::<aws_sdk_dynamodb::error::ConnectorError>() {
+                    return format!("The request failed during dispatch (response was not received). This might indicate an invalid region setting or another connectivity problem.\n{conn_error:?}").into();
```
Comment (Sevenannn) [inline crates/data_components/src/dynamodb/provider.rs]: should we do a format print `{conn_error}` instead of the debug print `{conn_error:?}` here to make the error more consistent? Debug print has nested `{}` and is not very user friendly

Comment (sgrebnov) [reply crates/data_components/src/dynamodb/provider.rs]: Yeah, there is a note why Debug is used. Display provide only error type w/o any information on the actual error

> If a connection error occurs, provide detailed information available via Debug format.

**Review by Sevenannn — APPROVED** [review]

File: crates/data_components/src/dynamodb/provider.rs [hunk 2]
```diff
@@ -99,6 +98,33 @@ impl DynamoDBTableProvider {
             .table_name(table_name.to_string())
             .send()
             .await
+            .map_err(|err| {
+                // Convert the SdkError to a more user-friendly error
+                let source = match err.into_source() {
```
Comment (Jeadie) [inline crates/data_components/src/dynamodb/provider.rs:103]:
```suggestion
                let source = err.into_source().map_err(Into::into)?;
```
nit: This is cleaner (if it works?).

**Review by Jeadie — APPROVED** [review]

File: crates/data_components/src/dynamodb/provider.rs (hunk 2 above)
Comment (sgrebnov) [reply crates/data_components/src/dynamodb/provider.rs:103]: Yeah - this will be a great simplification for the syntax, unfortunately this it can't be used like this here(
