### PR TITLE
fix: Expose GitHub ratelimit errors

### LINKED ISSUE #3257: GitHub GraphQL does not report rate limit errors

### PR DESCRIPTION
**Pull request by peasee**
## 🗣 Description

* Changes `GraphQLOptimizer` to `GraphQLContext`, because it's a useful carrier of other GraphQL related configuration.
* Adds `error_checker` to the `GraphQLContext`, allowing consumers to middle-man the headers and response to return custom errors
* Implements `error_checker` for GitHub, checking for errors relating to rate limits.

This ensures rate limit errors are actually made visible, instead of generic `403 Forbidden` errors.

## 🔨 Related Issues

* Closes #3257

### CODE REVIEW

File: crates/data_components/src/graphql/provider.rs [hunk 1]
```diff
@@ -56,7 +56,7 @@ impl GraphQLTableProviderBuilder {
     }
 
     #[must_use]
-    pub fn with_optimizer(mut self, optimizer: Arc<dyn GraphQLOptimizer>) -> Self {
+    pub fn with_optimizer(mut self, optimizer: Arc<dyn GraphQLContext>) -> Self {
```
Comment (phillipleblanc) [inline crates/data_components/src/graphql/provider.rs]: Change to context everywhere vs optimizer

**Review by phillipleblanc — APPROVED** [review]

**Review by sgrebnov — APPROVED** [review]

**Comment by Jeadie** [comment]
Is it possible to use the rate limiting errors from the client to rate limit the provider so that a `.scan(` can be successful? or is it not worth it if all GH datasets aren't using the same underlying client connection?

**Comment by peasee** [comment]
> Is it possible to use the rate limiting errors from the client to rate limit the provider so that a `.scan(` can be successful? or is it not worth it if all GH datasets aren't using the same underlying client connection?

This PR is not interested in retrying rate limits. Rate limit retries will be addressed in https://github.com/spiceai/spiceai/issues/2916
