### PR TITLE
Fix model nsql integration tests

### LINKED ISSUE #6328: `models::hf::nsql::huggingface_test_nsql` integration test skipped
## Describe the bug

The `models::hf::nsql::huggingface_test_nsql` is failing due to the model incorrectly generating invalid SQL for the NSQL request and was skipped.

The model adds a extra ` (backtick) character to the SQL query it generates, which cannot be parsed. All attempts fail. It is unknown what triggered this, perhaps an update to the model on hugging face?

## To Reproduce

Run this test:

`cargo test -p runtime --test integration_models --features models,metal -- huggingface_test_nsql --nocapture`

```text
2025-06-29T07:57:04.889440Z  INFO runtime::init::dataset: Dataset taxi_trips registered (s3://spiceai-demo-datasets/taxi_trips/2024/), acceleration (arrow), results cache enabled.
2025-06-29T07:57:04.891103Z DEBUG runtime::accelerated_table::refresh: Starting scheduled refresh
2025-06-29T07:57:04.891221Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset taxi_trips
2025-06-29T07:57:04.908717Z  INFO object_store::aws::builder: Using Instance credential provider
2025-06-29T07:57:08.618318Z TRACE runtime::accelerated_table::refresh_task: [refresh] Received 10 rows for dataset: taxi_trips
2025-06-29T07:57:08.618519Z  INFO runtime::accelerated_table::refresh_task: Loaded 10 rows (18.43 kiB) for dataset taxi_trips in 3s 727ms.
2025-06-29T07:57:08.618572Z DEBUG runtime::accelerated_table::refresh_task_runner: Refresh task successfully completed for dataset taxi_trips
2025-06-29T07:57:08.618886Z DEBUG runtime::accelerated_table::refresh: Received refresh task completion callback: Ok(())
2025-06-29T07:57:08.619354Z DEBUG runtime::init::scheduler: Dataset 'taxi_trips' has no refresh cron specified, skipping schedule creation
2025-06-29T07:57:08.697600Z  INFO integration_models::models::nsql: Running test cases hf_with_model
2025-06-29T07:57:08.698388Z  INFO runtime: All components are loaded. Spice runtime is ready!
2025-06-29T07:57:08.701564Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:08.701649Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:12.659541Z DEBUG runtime::http::v1::nsql: Running query:
```
SELECT COUNT(*) AS total_records FROM "spice".public.taxi_trips
2025-06-29T07:57:12.660486Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:12.660549Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:12.660606Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:12.660741Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:12.660789Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:12.660954Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:12.660996Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:16.608321Z DEBUG runtime::http::v1::nsql: Running query:
```sql
SELECT COUNT(*) AS total_records 
FROM "spice".public.taxi_trips
2025-06-29T07:57:16.608713Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:16.608736Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:16.608762Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:16.608834Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:16.608861Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:16.609020Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:16.609059Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:20.806456Z DEBUG runtime::http::v1::nsql: Running query:
```sql
SELECT COUNT(*) AS "total_records" 
FROM "spice".public.taxi_trips
2025-06-29T07:57:20.806751Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:20.806778Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:20.806804Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:20.806876Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:20.806905Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:20.807068Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:20.807107Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:24.925998Z DEBUG runtime::http::v1::nsql: Running query:
```sql
SELECT COUNT(*) AS "total_records"
FROM "spice".public.taxi_trips
```
2025-06-29T07:57:24.926296Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:24.926323Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:24.926348Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:24.926457Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:24.926528Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:24.926737Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:24.926803Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:28.450389Z DEBUG runtime::http::v1::nsql: Running query:
`SELECT COUNT(*) AS total_records FROM "spice".public.taxi_trips`
2025-06-29T07:57:28.450677Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:28.450700Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:28.450725Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:28.450797Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:28.450826Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:28.450996Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:28.451038Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:32.291449Z DEBUG runtime::http::v1::nsql: Running query:
`SELECT COUNT(*) AS "total_records" FROM "spice".public.taxi_trips`
2025-06-29T07:57:32.291722Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:32.291748Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:32.291773Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:32.291846Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:32.291875Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:32.292047Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:32.292206Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:36.308883Z DEBUG runtime::http::v1::nsql: Running query:
`SELECT COUNT(*) AS "total_records" FROM "spice".public.taxi_trips`
2025-06-29T07:57:36.309280Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:36.309324Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:36.309377Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:36.309487Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:36.309524Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:36.309705Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:36.309747Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:40.156162Z DEBUG runtime::http::v1::nsql: Running query:
`SELECT COUNT(*) AS "total_records" FROM "spice".public.taxi_trips`
2025-06-29T07:57:40.156496Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:40.156524Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:40.156553Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:40.156917Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:40.157041Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:40.157447Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:40.157503Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:44.184601Z DEBUG runtime::http::v1::nsql: Running query:
```sql
SELECT COUNT(*) AS total_records 
FROM "spice".public.taxi_trips
2025-06-29T07:57:44.184883Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:44.184907Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:44.184933Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:44.185009Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:44.185039Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:44.185221Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:44.185264Z TRACE llms::chat::mistral: Request sent!
test models::hf::nsql::huggingface_test_nsql has been running for over 60 seconds
2025-06-29T07:57:48.244344Z DEBUG runtime::http::v1::nsql: Running query:
```sql
SELECT COUNT(*) AS total_records
FROM "spice".public.taxi_trips
2025-06-29T07:57:48.244631Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:48.244656Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:48.244734Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:48.244866Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:48.244917Z DEBUG runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"). Retrying...
2025-06-29T07:57:48.245121Z TRACE llms::chat::mistral: Sending request to pipeline
2025-06-29T07:57:48.245167Z TRACE llms::chat::mistral: Request sent!
2025-06-29T07:57:51.798837Z DEBUG runtime::http::v1::nsql: Running query:
`SELECT COUNT(*) AS total_records FROM "spice".public.taxi_trips:`
2025-06-29T07:57:51.799140Z DEBUG runtime::datafusion::error: Finding root of DataFusionError: SQL(ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"), None)
2025-06-29T07:57:51.799167Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1"); code: SyntaxError
2025-06-29T07:57:51.799192Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:51.799266Z ERROR task_history: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:51.799304Z ERROR runtime::http::v1::nsql: Error executing query: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
2025-06-29T07:57:51.800139Z ERROR integration_models::models::nsql: run_nsql_test error: HTTP error: 400 Bad Request - Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: ` at Line: 1, Column: 1")
```

### PR DESCRIPTION
**Pull request by Sevenannn**
## 📝 Summary

In nsql requests the model is not guaranteed to generate a valid sql, and the integration tests should only test whether the expected tool calls are made and if a sql query is generated (not necessarily valid).

Update the tests to only check if expected tool calls and sql query is generated, and remove all logic / snapshots that would fail the test based if the model generates a invalid sql.

## 🔗 Related

- Close: https://github.com/spiceai/spiceai/issues/6328

### CODE REVIEW

**Review by kczimm — DISMISSED** [review]

**Review by sgrebnov — DISMISSED** [review]

File: crates/runtime/tests/models/hf.rs [hunk 1]
```diff
@@ -59,7 +59,6 @@ mod nsql {
     use super::*;
 
     // Tracking issue: https://github.com/spiceai/spiceai/issues/6328
```
Comment (phillipleblanc) [inline crates/runtime/tests/models/hf.rs]:
```suggestion
```

**Review by sgrebnov — APPROVED** [review]

**Review by phillipleblanc — APPROVED** [review]
