### PR TITLE
fix: validate time column and time format when constructing accelerated table refresh

### LINKED ISSUE #1917: validate time_format on time_column when initializing the accelerated datasets

### PR DESCRIPTION
**Pull request by y-f-u**
## 🗣 Description

This introduces two more formats: `timestamp` and `timestampz`. Also changed the default time_format to timestamp.

Error messages:
``` 
2024-07-10T10:22:08.548273Z  WARN runtime: Unable to attach data connector s3: time_column 'tpep_pickup_datetime' in dataset taxi.trips has data type 'Timestamp(Microsecond, None)', but time_format is configured as 'ISO8601'
```

```
2024-07-10T10:19:01.076100Z  WARN runtime: Unable to attach data connector s3: time_column "tpep_pickup_datetime1" is not found in dataset taxi.trips
```

## 🔨 Related Issues

fixes #1917 

## 🤔 Concerns

BREAKING change: time_format default changed from unix_seconds to timestamp. Any spicepod utilise the default time_format value for unix_timestamp based column, will see a warning of mismatch time format.

### CODE REVIEW

File: crates/runtime/src/accelerated_table/refresh.rs [hunk 1]
```diff
@@ -76,6 +95,98 @@ impl Refresh {
         self.refresh_retry_max_attempts = max_attempts;
         self
     }
+
+    pub(crate) fn validate_time_format(
```
Comment (digadeesh) [inline crates/runtime/src/accelerated_table/refresh.rs:99]: Can we write a test for this?

File: crates/runtime/src/accelerated_table/refresh.rs [hunk 2]
```diff
@@ -34,6 +36,23 @@ use tokio::time::sleep;
...
+pub enum Error {
+    #[snafu(display(r#"time_column '{time_column}' in dataset {table_name} has data type '{actual_time_format}', but time_format is configured as '{expected_time_format}'"#))]
+    TimeFormatMismatch {
+        table_name: String,
+        time_column: String,
+        expected_time_format: String,
+        actual_time_format: String,
+    },
+
+    #[snafu(display(r#"time_column '{time_column}' is not found in dataset {table_name}"#))]
```
Comment (lukekim) [inline crates/runtime/src/accelerated_table/refresh.rs]:
```suggestion
    #[snafu(display(r#"time_column '{time_column}' was not found in dataset {table_name}"#))]
```

**Review by phillipleblanc — APPROVED** [review]
