### PR TITLE
Run extended tests on PRs against release branch, update glue_iceberg_integration_test_catalog test

### LINKED ISSUE #6202: Integration test `glue_iceberg_integration_test_catalog` is failing
Reported in 1.4.0 release

### PR DESCRIPTION
**Pull request by Sevenannn**
## 📝 Summary

Run extended tests on PRs against release branch apart from on pushes to release branch, so that any failure in extended tests can be captured during release preparation.

Bump the timeout in glue_iceberg_integration_test_catalog to ensure it can finish.

## 🔗 Related

- Close: https://github.com/spiceai/spiceai/issues/6202

## 👀 Notes for Reviewers

The iceberg include parameter is not working, all schemas & tables are loading even when include is specified.
This test could potentially be updated to use the self hosted iceberg endpoint if we don't want to test iceberg glue specifically.

### CODE REVIEW

File: crates/runtime/tests/iceberg/catalog/mod.rs [hunk 1]
```diff
@@ -46,7 +46,6 @@ async fn glue_iceberg_integration_test_catalog() -> Result<(), anyhow::Error> {
             let mut db_catalog =
                 Catalog::new(format!("iceberg:https://glue.ap-northeast-2.amazonaws.com/iceberg/v1/catalogs/{account_id}/namespaces"), "ice_glue".to_string());
```
Comment (Jeadie) [inline crates/runtime/tests/iceberg/catalog/mod.rs]:
```suggestion
            // `params.include` not supported: https://github.com/spiceai/spiceai/issues/5314
            // db_catalog.include = vec!["testdb_001.*".to_string(), "testdb_002.*".to_string()];
```

Comment (Jeadie) [reply crates/runtime/tests/iceberg/catalog/mod.rs]: i.e don't remove, comment out and link to bug ticket.

File: crates/runtime/tests/iceberg/catalog/mod.rs [hunk 2]
```diff
@@ -63,7 +62,7 @@ async fn glue_iceberg_integration_test_catalog() -> Result<(), anyhow::Error> {
             let cloned_rt = Arc::new(rt.clone());
 
             tokio::select! {
-                () = tokio::time::sleep(std::time::Duration::from_secs(120)) => {
+                () = tokio::time::sleep(std::time::Duration::from_secs(600)) => {
```
Comment (Jeadie) [inline crates/runtime/tests/iceberg/catalog/mod.rs:67]: Same here.

**Review by Jeadie — APPROVED** [review]
