### PR TITLE
Handle errors in vector ingestion pipeline

### LINKED ISSUE #6509: If indexing returns an error, the acceleration attempt is aborted
Currently if indexing fails, the acceleration will continue leading to a situation where we can't be sure the indexing has completely properly when the acceleration finishes.

Wire up errors such that if an indexing job fails, it causes the acceleration load to fail as well.

### PR DESCRIPTION
**Pull request by phillipleblanc**
## 📝 Summary

If the vectors ingestion pipeline has an error (i.e. error computing the embedding, or an error writing to the vector store) then the acceleration attempt should also return an error, which will prompt a retry at the acceleration layer.

This PR also modifies the signature of `compute_index` to return a `Vec<RecordBatch>` in preparation for #6518

## 🔗 Related

- Closes #6509

### CODE REVIEW

File: crates/runtime-datafusion-index/src/lib.rs [hunk 1]
```diff
@@ -30,7 +31,11 @@ pub trait Index: Debug + Send + Sync + 'static {
     /// Columns that are required for the index to be computed.
     fn required_columns(&self) -> Vec<String>;
 
-    async fn compute_index(&self, _batches: Vec<RecordBatch>) {}
+    /// Compute the index - if the index data is represented in the batch itself (i.e. a vector
+    /// "*_embedding" column) then modify the provided batches to include the computed column.
+    async fn compute_index(&self, batches: Vec<RecordBatch>) -> Result<Vec<RecordBatch>> {
```
Comment (phillipleblanc) [inline crates/runtime-datafusion-index/src/lib.rs:36]: This currently isn't being consumed anywhere - it will be in the next PR that addresses #6518

File: crates/runtime/src/embeddings/index/s3.rs [hunk 2]
```diff
@@ -184,53 +221,57 @@ pub async fn write(index: &S3VectorIndex, cfg: &IndexEmbeddingConfig, record: &R
...
+            len: values.len(),
+        }
+        .fail();
     }
 
     // Currently, we only support when there is one primary key column.
     if primary_keys.len() > 1 {
         tracing::debug!("primary_keys.len() > 1");
-        return;
+        return Ok(());
```
Comment (sgrebnov) [inline crates/runtime/src/embeddings/index/s3.rs:246]: Should invalid/unsupported primary keys configurations treated as errors as well?

**Review by sgrebnov — APPROVED** [review]

File: crates/runtime/src/embeddings/index/s3.rs (hunk 2 above)
Comment (phillipleblanc) [reply crates/runtime/src/embeddings/index/s3.rs:246]: Jack is working on adding multiple primary keys in https://github.com/spiceai/spiceai/pull/6775
