### PR TITLE
RRF: Rank and recency boosting

### LINKED ISSUE #7058: Enhancement: RRF UDTF (+ rank boosting + recency boosting)
## Goal-State/What/Result

Expose a helper UDTF for RRF queries. Currently, `trunk` has an RRF implementation that supports this:
```sql
SELECT id, title, content, fused_score
FROM rrf(
  vector_search(documents, 'machine learning algorithms'),
  text_search(documents, 'neural networks deep learning', content),
  id,    -- optional join key for optimal performance
  60.0   -- optional smoothing factor
);
```

---

#### Expand

With current support, add ability to:
- Support per-subquery boosting
- Support recency ranking

#### Option 1

Define boost parameters in Spicepod:

```yaml
datasets:
  - from: file://wiki_a2.parquet
    name: wiki_a
    acceleration:
      enabled: true
    columns:
     - name: text
       full_text_search:
          enabled: true
          rank_boost: 10
          recency_boost: 1
          recency_boost_column: foo
          row_id:
            - id
       vector_search:
          rank_boost: 5
          recency_boost: 20
          recency_boost_column: foo
       embeddings:
         - from: potion_2m
```

Pros: Easy to configure
Cons: Cannot decide on boosting parameters at invocation time (what if boost specification is contingent on input query, for the same index?)

#### Option 2

Use structs in invocation with named parameters

```sql
SELECT id, title, content, fused_score
FROM rrf(
        named_struct('query', vector_search(documents, 'machine learning algorithms'), 'rank_boost', 10, 'recency_boost', 20, 'recency_column', created_at),
        text_search(documents, 'neural networks deep learning', content),
        id,    -- optional join key for optimal performance
        60.0   -- optional smoothing factor
     );
```

Pros: per invocation query customization
Cons: Need some changes to invoke `named_struct` in the UDF to materialize arguments

This works:

```sql
sql> select named_struct('a', 5, 'b', 10);
+------------------------------------------------------+
| named_struct(Utf8("a"),Int64(5),Utf8("b"),Int64(10)) |
+------------------------------------------------------+
| {a: 5, b: 10}                                        |
+------------------------------------------------------+
```

This does not (yet):

```sql
sql> SELECT id, title, content, fused_score
FROM rrf(
    named_struct('query', vector_search(documents, 'machine learning algorithms'), 'boost', 10),
    text_search(documents, 'neural networks deep learning', content),
    id,    -- optional join key for optimal performance
    60.0   -- optional smoothing factor
 );
Query Error: Table function 'named_struct' not found
```

#### Option 3

Ordered parameter lists after queries, positional:

```sql
SELECT id, title, content, fused_score
FROM rrf(
    vector_search(documents, 'machine learning algorithms'),
    text_search(documents, 'neural networks deep learning', content),
    id,     -- optional join key for optimal performance
    60.0    -- optional smoothing factor,
    [10, 5] -- rank boosting args,
    [1, 20] -- recency boosting args
 );
```

Pros: Same as 2
Cons: Positionally dependent DDL is confusing for users

#### Option 4

Named argument expressions in the subquery search calls (via @lukekim):

```sql
SELECT id, title, content, fused_score
FROM rrf(
        vector_search(documents, 'machine learning algorithms', rank_boost => 10, recency_boost => 20, recency_column => created_at)),
        text_search(documents, 'neural networks deep learning', content),
        id,    -- optional join key for optimal performance
        60.0   -- optional smoothing factor
     );
```

Pros: Same as 2 with easier syntax + instantly know which call a boost belongs to
Cons: Relies on Scalar UDF hack (so RRF will have to lift these args out of the subquery calls, and will be the only usage of them, where otherwise they won't exist for `vector_search` and `text_search`).

---

Option 4 seems to be clearest + provide the most flexibility. Option 1 is clear and easy to use but requires review of search-related Spicepod semantics.

## Why/Purpose

- Ease of use vs manually fusing subqueries + declaring score computations.

## By When

**Issue/Spec written and reviewed:** _Target Date_
**Done-Done:** _Target Date_

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Release Notes / PRFAQ
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Telemetry / Metrics / Task History
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## QA Plan

- Test queries against several federated providers to avoid column resolution bugs
- Test reranking + reordering of search subqueries

#### New Reciprocal Rank Fusion (RRF) UDTF

Added support for Reciprocal Rank Fusion (RRF) as a user-defined table function, enabling sophisticated hybrid search
capabilities that combine multiple search methods for improved relevance ranking.

Features:
- Multi-search fusion: Combine results from vector_search, text_search, and other search UDTFs in a single query
- Performance conscious: Optional user-specified join key for better performance
- Automatic joining: Falls back to on-the-fly JOIN key computation when no explicit key is provided

Usage:
```sql
SELECT id, title, content, fused_score
FROM rrf(
  vector_search(documents, 'machine learning algorithms'),
  text_search(documents, 'neural networks deep learning', content),
  id,    -- optional join key for optimal performance
  60.0   -- optional smoothing factor
)
WHERE fused_score > 0.01
ORDER BY fused_score DESC;
```

### PR DESCRIPTION
**Pull request by mach-kernel**
## 📝 Summary

Let's do a quick tour of the new functionality:

#### Named arguments only

With our recent DataFusion patch, we can now rely on named arguments instead of positional ones:

```sql
SELECT id, title, fused_score
FROM rrf(
    vector_search(wiki_a_potion, 'fire'),
    text_search(wiki_a_potion, 'noise'),
    k => 10.0,
    join_key => 'id'
);
```

Unfortunately, we have to express columns as strings because column references do not have metadata like literals do. Well, there's a table reference facility, but it would not make much sense to use to bind parameters. In both the existing and new implementation we lift the name out of the Column expr to obtain a qualified reference, so there is no loss of functionality or correctness -- just cosmetic.

#### Rank weighting

This can now be expressed as a named argument in your `vector_search` and `text_search` calls!

```sql
SELECT id, title, fused_score
FROM rrf(
    vector_search(wiki_a_potion, 'fire', rank_weight => 100),
    text_search(wiki_a_potion, 'noise', rank_weight => 10)
 );
```

#### Recency boosting

This one is fun, and very configurable! Out of the box, recency is configured with an exponential decay function to be sensitive to _days_ with a correspondingly appropriate alpha constant. Users opt in to recency boosting by specifying a `time_column`.

##### Math

I haven't written LaTeX since school.

$\text{decay}(t) = e^{-\alpha \cdot t}$
| Age (t) in Days | Decay Multiplier |
|------------------|------------------|
| 0                | 1.000            |
| 10               | 0.905            |
| 20               | 0.819            |

Linear decay is also available:

$\text{decay}(t) = \max\left(0,\ 1 - \frac{t}{T} \right)$

##### With defaults

```sql
SELECT id, name, city, fused_score
FROM rrf(
    vector_search(people, 'northeast'),
    text_search(people, 'california'),
    join_key => 'id',
    time_column => 'ts'
);
```

##### With overrides (exponential)

```sql
SELECT id, name, city, fused_score
FROM rrf(
    vector_search(people, 'northeast', rank_weight => 10),
    text_search(people, 'california'),
    join_key => 'id',
    time_column => 'ts',
    decay_constant => 0.01, -- less decay
    decay_scale_secs => 31536000 -- 1 year
 );
```

##### With overrides (linear, 48 hour window)

```sql
SELECT id, name, city, fused_score
FROM rrf(
    vector_search(people, 'northeast', rank_weight => 10),
    text_search(people, 'california'),
    time_column => 'ts',
    recency_decay => 'linear',
    decay_window_secs => 172800 -- 2 days
 );
```

## 🔗 Related

https://github.com/spiceai/datafusion/pull/104
https://github.com/apache/datafusion/issues/17379

Resolves https://github.com/spiceai/spiceai/issues/7058

## 🚨 Breaking Changes

n/a

## 📚 Docs

TODO with a nice dataset. Will circle back.

## 👀 Notes for Reviewers

See PR comments

### CODE REVIEW

File: crates/runtime/src/search/rrf.rs [hunk 1]
```diff
@@ -54,11 +66,107 @@ pub static DOCUMENTATION: LazyLock<Documentation> = LazyLock::new(|| {
...
+    }
+}
+
+#[derive(Debug, Default)]
+struct ReciprocalRankFusionSubqueryArgs {
+    pub rank_weight: Option<f64>,
+}
+
+impl ReciprocalRankFusionSubqueryArgs {
+    pub fn from_scalar_function_expr(
```
Comment (mach-kernel) [inline crates/runtime/src/search/rrf.rs:125]: This makes the RRF subquery args struct, and removes "our" params from `vector_search` and `text_search` call exprs.

File: crates/runtime/src/search/rrf.rs [hunk 2]
```diff
@@ -159,14 +279,21 @@ impl ReciprocalRankFusion {
         }
     }
 
-    // Given arguments to n search calls: execute searches, generate row IDs, rank by score, JOIN,
-    // then finally re-rank and sort fused results
-    fn rerank_and_fuse_df(&self, args: &ReciprocalRankFusionArgs) -> Result<DataFrame> {
-        let subquery_dfs = self.prepare_and_execute_subqueries(args)?;
-
+    fn compute_score_expr(
```
Comment (mach-kernel) [inline crates/runtime/src/search/rrf.rs:272]: Lifted `score_expr` building into a new function that will apply the relevant boosting params if they're defined

File: crates/runtime/src/search/rrf.rs [hunk 3]
```diff
@@ -178,6 +305,50 @@ impl ReciprocalRankFusion {
...
+        // Lots of casting annoyances are avoided by treating everything as `long`
+        let today_epoch = to_unixtime(vec![now()]);
+        let recency_col_epoch = to_unixtime(vec![col(qualified_recency_col)]);
+        let age_in_units = (today_epoch - recency_col_epoch) / lit(decay_scale_secs);
+
+        let recency_expr = match recency_decay {
+            // e^(-alpha * age units)
+            RecencyDecay::Exponential => {
+                let decay_constant = args.decay_constant.unwrap_or(0.01);
+                #[allow(clippy::neg_multiply)]
```
Comment (mach-kernel) [inline crates/runtime/src/search/rrf.rs:322]: I know. Why is this guy always disabling the linting rules. 

For this one: I am too inattentive to notice a little dash, and so the explicit multiply by `-1` makes it clearer to me that it's there vs `-decay_constant`.

File: Cargo.toml [hunk 4]
```diff
@@ -226,11 +226,11 @@ inherits = "dev"
 lto = "off"
 
 [patch.crates-io]
-datafusion = { git = "https://github.com/spiceai/datafusion.git", rev = "912eebec159e037c7c233aae35c090071675d5a9" }            # spiceai/spiceai-49
-datafusion-common = { git = "https://github.com/spiceai/datafusion.git", rev = "912eebec159e037c7c233aae35c090071675d5a9" }     # spiceai/spiceai-49
-datafusion-datasource = { git = "https://github.com/spiceai/datafusion.git", rev = "912eebec159e037c7c233aae35c090071675d5a9" } # spiceai/spiceai-49
-datafusion-execution = { git = "https://github.com/spiceai/datafusion.git", rev = "912eebec159e037c7c233aae35c090071675d5a9" }  # spiceai/spiceai-49
-datafusion-expr = { git = "https://github.com/spiceai/datafusion.git", rev = "912eebec159e037c7c233aae35c090071675d5a9" }       # spiceai/spiceai-49
+datafusion = { git = "https://github.com/spiceai/datafusion.git", rev = "1d9c68089a3a4ed41988492b33357069c6bf0713" }            # spiceai/spiceai-49
```
Comment (mach-kernel) [inline Cargo.toml]: TODO: bump ref once datafusion PR is merged

File: crates/runtime/src/search/rrf.rs [hunk 5]
```diff
@@ -484,113 +671,203 @@ mod tests {
...
+
+        let picked_at_expr = fruit_df.parse_sql_expr("to_timestamp(cast(picked_at as bigint))")?;
 
-        let query =
-            "select * from rrf(vector_search(foo, 'crispy'), vector_search(foo, 'red'), id, 600.0)";
+        let fruit_df = fruit_df
+            .with_column("picked_at", picked_at_expr)?
+            .sort(vec![col("picked_at").sort(false, false)])?;
+
+        let fruit_embedding_table = df_as_embedding_table(&runtime, fruit_df.clone())?;
```
Comment (mach-kernel) [inline crates/runtime/src/search/rrf.rs]: Thanks @kczimm for showing me `DataFrame::into_view`. This is something that I missed a lot from writing tests in Spark. It is _so much easier_ to set up test data with a DataFrame (imagine all of the record batch building + coercing to do the equivalent of what we do to build `fruit_df`).

File: crates/runtime/src/search/rrf.rs [hunk 6]
```diff
@@ -54,11 +66,107 @@ pub static DOCUMENTATION: LazyLock<Documentation> = LazyLock::new(|| {
...
+
+impl ReciprocalRankFusionSubqueryArgs {
+    pub fn from_scalar_function_expr(
+        expr: &Expr,
+    ) -> Result<(Expr, ReciprocalRankFusionSubqueryArgs)> {
+        if let Expr::ScalarFunction(ScalarFunction { args, func }) = expr {
+            let mut args = args.clone();
+            let rrf_args = args
+                .extract_if(.., |arg| {
+                    matches!(arg, Expr::Literal(_, Some(meta)) if meta.inner().contains_key("spice.parameter_name"))
```
Comment (phillipleblanc) [inline crates/runtime/src/search/rrf.rs:132]: Shouldn't this also be only if it matches `rank_weight`?

**Review by phillipleblanc — APPROVED** [review]
Thanks @mach-kernel! This PR is very nice

File: crates/runtime/src/search/rrf.rs (hunk 6 above)
Comment (mach-kernel) [reply crates/runtime/src/search/rrf.rs:132]: The intent is to pull the values out by key after zipping up the map, in case we wanted to add another parameter in the future.

EDIT: Also those UDTFs do not use any named arguments, so we likely do not want to pass them along.

File: crates/runtime/src/search/rrf.rs [hunk 7]
```diff
@@ -168,6 +295,50 @@ impl ReciprocalRankFusion {
...
+        let today_epoch = to_unixtime(vec![now()]);
+        let recency_col_epoch = to_unixtime(vec![col(qualified_recency_col)]);
+        let age_in_units = (today_epoch - recency_col_epoch) / lit(decay_scale_secs);
+
+        let recency_expr = match recency_decay {
+            // e^(-alpha * age units)
+            RecencyDecay::Exponential => {
+                let decay_constant = args.decay_constant.unwrap_or(0.01);
+                #[allow(clippy::neg_multiply)]
+                exp(lit(-1.0f64 * decay_constant) * age_in_units)
```
[the remark this answers is not in the document]
Comment (mach-kernel) [reply crates/runtime/src/search/rrf.rs:323]: I disagree and you're not even a person

File: crates/runtime/src/search/rrf.rs [hunk 8]
```diff
@@ -416,43 +587,44 @@ mod tests {
...
     use datafusion::logical_expr::{ColumnarValue, Volatility, create_udf};
+    use datafusion::prelude::{DataFrame, now, to_unixtime};
     use datafusion::scalar::ScalarValue;
     use datafusion_expr::expr::ScalarFunction;
-    use llms::embeddings::Embed;
+    use datafusion_expr::{ExprFunctionExt, lit};
     use llms::model2vec::Model2Vec;
+    use std::collections::BTreeMap;
     use std::collections::HashMap;
+    use std::process::ExitCode;
```
[the remark this answers is not in the document]
Comment (mach-kernel) [reply crates/runtime/src/search/rrf.rs:609]: It's used in the Result types

File: Cargo.toml (hunk 4 above)
Comment (mach-kernel) [reply Cargo.toml]: Complete
