### PR TITLE
fix: Include FTS search column if it is the PK

### LINKED ISSUE #6784: Full text search fails using the same column as the row ID
## Describe the bug

_A clear and concise description of what the bug is._

I have a dataset of files from GitHub that I want to search against the `path`. The `path` field for file entries is the primary key, so is also defined as the `row_id` like:

```yaml
- name: path
        full_text_search:
          enabled: true
          row_id: path
```

Trying to text search with this configuration results in an error:

```
sql> explain select name, path, score from text_search(spiceai.docs, 'duckdb') order by score desc;
+---------------------+----------------------------------------------------------------------+
| plan_type           | plan                                                                 |
+---------------------+----------------------------------------------------------------------+
| logical_plan        | Sort: text_search().score DESC NULLS FIRST                           |
|                     |   BytesProcessedNode                                                 |
|                     |     TableScan: text_search() projection=[name, path, score]          |
| physical_plan_error | type_coercion                                                        |
|                     | caused by                                                            |
|                     | Schema error: No field named path. Valid fields are base_table.name. |
+---------------------+----------------------------------------------------------------------+
```

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by peasee**
## 📝 Summary

* Ensures that text searches via the UDTF include the search column in the projection, if the search column is the `row_id`/index primary key - as the column is used to later join the table.

## 🔗 Related

* Closes #6784

### CODE REVIEW

File: crates/search/src/generation/text_search/index.rs [hunk 1]
```diff
@@ -327,6 +327,11 @@ impl FullTextDatabaseIndex {
         let schema = schema_builder.build();
         Ok(Arc::new(RwLock::new(tantivy::Index::create_in_ram(schema))))
     }
+
+    #[must_use]
+    pub fn column_is_pk(&self, column: &str) -> bool {
+        self.primary_key.len() == 1 && self.primary_key.first().map(String::as_str) == Some(column)
```
Comment (Jeadie) [inline crates/search/src/generation/text_search/index.rs]: Why `self.primary_key.len() == 1`?

Comment (peasee) [reply crates/search/src/generation/text_search/index.rs]: `TextSearchIndexProvider.column` is a single string that cannot represent a composite key. `FullTextDatabase.primary_key` is a `Vec<String>` which could represent a composite key. `.contains()` is not sufficient, as it could match a part of a composite key, so we must check the length.

Comment (Jeadie) [reply crates/search/src/generation/text_search/index.rs]: But for the below change, if `TextSearchIndexProvider.column` is in `FullTextDatabase.primary_key`, it will be removed from the projection, and then we can't `retains the column for the later table join operations`?

Comment (peasee) [reply crates/search/src/generation/text_search/index.rs]: I think I misunderstood what the `column` of the `TextSearchIndexProvider` was. I thought it was part of the PK, but it is the search column - the correct solution is that if the search column appears as any part of the primary key, the column should be retained. That makes more sense now, I'll stick with `.contains()`.

**Review by Jeadie — APPROVED** [review]
