### PR TITLE
Enhancement: Add `spill_compression` to runtime config

### LINKED ISSUE #7256: Enhancement: Add Spill Compression Option to Runtime Config
## Goal-State/What/Result

Pipe through: https://github.com/apache/datafusion/pull/16268/files.

Make default: `zstd`

## Why/Purpose

To allow better control over performance tuning for the large queries:
* `lz4_frame` offers faster (de)compression, but typically results in larger spill files. 
* In contrast, `zstd` achieves higher compression ratios at the cost of slower (de)compression speed.

## By When

**Issue/Spec written and reviewed:** Oct 7, 2025
**Done-Done:** Oct 8, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Release Notes / PRFAQ
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Telemetry / Metrics / Task History
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

Proposed `spicepod.yaml` confuguration:
```yaml

runtime:
    query:
        spill_compression: `zstd (default)` | lz4_frame` | `uncompressed`
        memory_limit: <> # will be deprecated in runtime.memory_limit in favor of this location
```

### Security Review

N/A

## How/Implementation Plan

1. Add `SpillCompression` enum to `crates/spicepod/component/runtime.rs` + mapper to `spicepod::SpillCompression`
2. Add `with_spill_compression` to `RuntimeBuilder` and `DataFusionBuilder`
3. Use `spill_compression` in `DataFusionBuilder::build`:
```rust
let config = self.config
    .with_spill_compression(self.spill_compression); // new

// existing
let mut state = SessionStateBuilder::new()
    .with_config(self.config)
```

### IMPORTANT
This implementation means that following custom instance of `SessionContext` will not be using `spill_compression` defined in yaml config:
* [`RefreshTask::refresh_df_context`](https://github.com/spiceai/spiceai/blob/3177d5b2eaf1e1336ca0084d113321c988cb2964/crates/runtime/src/accelerated_table/refresh_task.rs#L697)

If we want to make this setting global, then we would need to refactor logic of instantiating `RefreshTask` to properly propagate `spill_compression` from yaml config. Options are:
* Pass `App` to `RefreshTask` and use it in `RefreshTask::refresh_df_context`
* Pass runtime's datafusion instance to `RefreshTask` and use it when performing refresh queries (need to make sure we won't introduce regression)

## QA Plan

Tests + manual testing

## Release Notes

**Spill Compression configuration**:  A new option is available in `spicepod.yaml` to configure spill file compression for large queries:
- Supported values: `zstd` (default), `lz4_frame`, `uncompressed`
- The default is now `zstd`, enabling higher compression ratios for spill files, which can help reduce disk usage during query execution.
- Users can opt for `lz4_frame` for faster (de)compression at the expense of larger spill files, or disable compression with `uncompressed`.
- To change, set `runtime.query.spill_compression` to your preferred value in `spicepod.yaml`.
- This change improves control over performance tuning and resource usage in large-scale analytics workloads.

### PR DESCRIPTION
**Pull request by krinart**
## 📝 Summary

Adds following config:
```
runtime:
  query:
    spill_compression: `zstd (default)` | lz4_frame` | `uncompressed`
````

Additionally:
* Deprecates `runtime.memory_limit` in favor of `runtime.query.memory_limit`. Both locations are supported for smooth migration.
* Deprecates `runtime.temp_directory` in favor of `runtime.query.temp_directory`. Both locations are supported for smooth migration.

## 🔗 Related

Closes https://github.com/spiceai/spiceai/issues/7256

## 🚨 Breaking Changes

N/A

## 📚 Docs
https://github.com/spiceai/docs/pull/1190

## 👀 Notes for Reviewers

N/A

### CODE REVIEW

File: crates/runtime/src/datafusion/builder.rs [hunk 1]
```diff
@@ -20,6 +20,15 @@ use std::{
...
 
+use super::{
+    DataFusion, SPICE_DEFAULT_CATALOG, SPICE_DEFAULT_SCHEMA, SPICE_METADATA_SCHEMA,
+    SPICE_RUNTIME_SCHEMA,
+    extension::{
+        SpiceQueryPlanner, bytes_processed::BytesProcessedOptimizerRule,
+        cache_invalidation::CacheInvalidationOptimizerRule,
+    },
+    schema::SpiceSchemaProvider,
+};
```
Comment (krinart) [inline crates/runtime/src/datafusion/builder.rs:31]: This was a lint change

**Review by lukekim — DISMISSED** [review]

**Review by lukekim — APPROVED** [review]
