### PR TITLE
Fix `content-type` header  in `v1/sql` response

### LINKED ISSUE #6216: The content type of the POST /v1/sql response is always `text/plain`, which does not match the actual body content type
## Describe the bug

JSON body:
```console
curl -i 'http://localhost:8090/v1/sql' \
        -H 'accept: application/json' \
        -H 'content-type: text/plain' \
        --data-raw 'SELECT * FROM taxi_trips_1 LIMIT 1;'
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
x-cache: Miss from spiceai
results-cache-status: MISS
vary: origin, access-control-request-method, access-control-request-headers
content-length: 414
date: Thu, 12 Jun 2025 06:29:18 GMT

[{"VendorID":2,"tpep_pickup_datetime":"2024-01-20T15:15:03","tpep_dropoff_datetime":"2024-01-20T15:18:21","passenger_count":1,"trip_distance":0.54,"RatecodeID":1,"store_and_fwd_flag":"N","PULocationID":75,"DOLocationID":236,"payment_type":2,"fare_amount":5.8,"extra":0.0,"mta_tax":0.5,"tip_amount":0.0,"tolls_amount":0.0,"improvement_surcharge":1.0,"total_amount":9.8,"congestion_surcharge":2.5,"Airport_fee":0.0}]⏎ 
```

CSV:
```console
➜ curl -i 'http://localhost:8090/v1/sql' \
        -H 'accept: text/csv' \
        -H 'content-type: text/plain' \
        --data-raw 'SELECT * FROM taxi_trips_1 LIMIT 1;'
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
x-cache: Miss from spiceai
results-cache-status: MISS
vary: origin, access-control-request-method, access-control-request-headers
content-length: 368
date: Thu, 12 Jun 2025 06:33:15 GMT

VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
1,2024-01-21T14:26:58,2024-01-21T14:32:05,1,0.6,1,N,236,237,1,5.8,2.5,0.5,3.0,0.0,1.0,12.8,2.5,0.0
```

## Expected behavior

Response content type header should match the type of the returned body

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by Jeadie**
## 📝 Summary
Resolves #6216

### CODE REVIEW

**Review by ewgenius — DISMISSED** [review]

**Review by phillipleblanc — DISMISSED** [review]

**Review by Sevenannn — DISMISSED** [review]

File: crates/runtime/src/http/v1/mod.rs [hunk 1]
```diff
@@ -129,6 +129,17 @@ pub(crate) fn accept_header_types(accept: &TypedHeader<Accept>) -> Vec<String> {
...
 
 impl ResponseMimeType {
+    pub fn to_accept_header(&self) -> Option<http::HeaderValue> {
+        let media_type = match self {
+            ResponseMimeType::Json => "application/json",
+            ResponseMimeType::Csv => "text/csv",
+            ResponseMimeType::Plain => "text/plain",
+            ResponseMimeType::VndNsqlJsonV1 => "application/vnd.spiceai.nsql.v1+json",
+            ResponseMimeType::VndSqlJsonV1 => "application/vnd.spiceai.sql.v1+json",
+        };
```
Comment (peasee) [inline crates/runtime/src/http/v1/mod.rs:139]:
```suggestion
        }
```

**Review by peasee — DISMISSED** [review]

File: crates/runtime/src/http/v1/mod.rs [hunk 2]
```diff
@@ -231,6 +242,10 @@ pub async fn to_http_response(
 
     let mut headers = HeaderMap::new();
 
+    if let Some(header_value) = format.to_accept_header() {
+        headers.insert(CONTENT_TYPE, header_value);
+    };
```
Comment (peasee) [inline crates/runtime/src/http/v1/mod.rs]:
```suggestion
    }
```

oops, wrong one earlier!

**Review by peasee — APPROVED** [review]
