### PR TITLE
Use Spice specific errors instead of OpenAIError in embedding module

### LINKED ISSUE #6412: Refactor `Embed` trait to return Spice specific errors, not OpenAIError
The Embed trait should return our own Snafu errors that we can downcast specific variants of, not the OpenAi Error: https://github.com/spiceai/spiceai/blob/trunk/crates/llms/src/bedrock/embed/mod.rs#L206C42-L206C53

### PR DESCRIPTION
**Pull request by kczimm**
## 📝 Summary
Use Spice specific errors instead of OpenAIError in embedding module.

## 🔗 Related

Closes:
- #6412 
- #6427

### CODE REVIEW

File: crates/llms/src/bedrock/embed/mod.rs [hunk 1]
```diff
@@ -221,10 +206,14 @@ where
...
-    ) -> Result<CreateEmbeddingResponse, OpenAIError> {
+    ) -> EmbedResult<CreateEmbeddingResponse> {
         let texts = Self::convert_input_to_texts(&req.input);
 
-        let (vectors, num_tokens) = self.embed_texts(texts).await?;
+        let (vectors, num_tokens) = self
+            .embed_texts(texts)
+            .await
+            .boxed()
+            .map_err(|e| EmbedError::FailedToCreateEmbedding { source: e })?;
```
Comment (Advayp) [inline crates/llms/src/bedrock/embed/mod.rs]: Can we use `.context` here?

File: crates/llms/src/databricks.rs [hunk 2]
```diff
@@ -307,7 +307,7 @@ impl Embed for Databricks {
             })
             .await
             .boxed()
-            .map_err(|e| crate::embeddings::Error::FailedToCreateEmbedding { source: e })?;
+            .map_err(|e| Error::FailedToCreateEmbedding { source: e })?;
```
Comment (Advayp) [inline crates/llms/src/databricks.rs]: Can we use `.context` here too?

**Comment by Advayp** [comment]
Seems like there are some linting errors @kczimm

File: crates/llms/src/embeddings/candle/tei.rs [hunk 3]
```diff
@@ -256,23 +253,18 @@ impl Embed for TeiEmbed {
...
-            OpenAIError::ApiError(ApiError {
-                message: e.to_string(),
-                r#type: None,
-                param: None,
-                code: None,
-            })
-        })?;
+        let results =
+            self.embed_futures(inputs)
+                .await
```
Comment (Jeadie) [inline crates/llms/src/embeddings/candle/tei.rs]: nit: Like advay said you can also do it here with `.boxed()`
```rust
let results = self
    .embed_futures(inputs)
    .await
    .boxed()
    .context(FailedToCreateEmbeddingSnafu);
```

**Review by phillipleblanc — DISMISSED** [review]

File: crates/llms/src/databricks.rs (hunk 2 above)
Comment (Advayp) [inline crates/llms/src/databricks.rs]: Does `.context` not work here?

File: crates/llms/src/databricks.rs [hunk 4]
```diff
@@ -280,23 +280,23 @@ impl Embed for Databricks {
...
-        &self,
-        req: CreateEmbeddingRequest,
-    ) -> Result<CreateEmbeddingResponse, OpenAIError> {
+    async fn embed_request(&self, req: CreateEmbeddingRequest) -> Result<CreateEmbeddingResponse> {
         // Must use `post` instead of `embeddings().create(...` to avoid concatenation of `/embeddings`.
-        self.client.post("", req).await
+        self.client
+            .post("", req)
+            .await
+            .map_err(|e| Error::FailedToCreateEmbedding { source: e.into() })
```
Comment (Advayp) [inline crates/llms/src/databricks.rs]: I think you can use `.context` here as well. IIRC it calls `.into()` on the source error

File: crates/llms/src/openai/embed.rs [hunk 5]
```diff
@@ -98,11 +98,17 @@ impl<C: Config + Sync + Send + Debug> Embed for OpenaiEmbed<C> {
...
         let mut inner_req = req.clone();
         inner_req.model.clone_from(&self.inner.model);
-        let mut resp = self.inner.client.embeddings().create(inner_req).await?;
+        let mut resp = self
+            .inner
+            .client
+            .embeddings()
+            .create(inner_req)
+            .await
+            .map_err(|e| EmbedError::FailedToCreateEmbedding { source: e.into() })?;
```
Comment (Advayp) [inline crates/llms/src/openai/embed.rs]: Try `.context`

**Review by Advayp — APPROVED** [review]

**Review by phillipleblanc — APPROVED** [review]
