### PR TITLE
fix: Warn about no configured datasets if no datasets and catalogs are present

### LINKED ISSUE #5982: Runtime warns about no datasets configured even when there are catalogs
## Describe the bug

Regardless of the configured catalogs in the spiecpod, the runtime will display a warning if there are no datasets.

```
2025-05-26T01:58:06.439526Z  INFO runtime::init::dataset: No datasets were configured. If this is unexpected, check the Spicepod configuration.
2025-05-26T01:58:06.440052Z  INFO runtime::init::catalog: Registering catalog 'db_uc' for databricks
2025-05-26T01:58:23.927907Z  INFO runtime::init::catalog: Registered catalog 'db_uc' with 2 schemas and 32 tables
2025-05-26T01:58:24.032010Z  INFO runtime: All components are loaded. Spice runtime is ready!
```

## To Reproduce

Spicepod with non empty catalog and 0 datasets

## Expected behavior

If Spicepod has no datasets but has configured catalog connectors, it should suppress the warning.

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by Advayp**
## 📝 Summary

- Warn about no configured datasets only when no datasets *and* no catalogs are present

## 🔗 Related

- Closes #5982 

## Output

`spicepod.yaml`:
```yaml
version: v1
kind: Spicepod
name: spice-catalog-demo
catalogs:
    - from: spice.ai/spiceai/tpch
      name: scp
      include:
          - tpch.part*
          - tpch.supplier
    - from: spice.ai/spiceai/quickstart
      name: quickstart
```

Before:
image

After:
image

### CODE REVIEW

File: crates/runtime/src/init/dataset.rs [hunk 1]
```diff
@@ -67,8 +67,9 @@ impl Runtime {
         };
 
         let valid_datasets = Arc::clone(&self).get_valid_datasets(app, LogErrors(true));
+        let valid_catalogs = Arc::clone(&self).get_valid_catalogs(app, LogErrors(true));
 
-        if valid_datasets.is_empty() {
+        if valid_datasets.is_empty() && valid_catalogs.is_empty() {
```
Comment (peasee) [inline crates/runtime/src/init/dataset.rs]: It might be a better pattern to move this check out of `load_datasets` and into [`load_components`](https://github.com/spiceai/spiceai/blob/trunk/crates/runtime/src/lib.rs#L733)? It seems weird that we check for valid catalogs inside `load_datasets()`

File: crates/runtime/src/init/dataset.rs [hunk 2]
```diff
@@ -67,8 +67,9 @@ impl Runtime {
...
             tracing::info!(
                 "No datasets were configured. If this is unexpected, check the Spicepod configuration."
```
Comment (peasee) [inline crates/runtime/src/init/dataset.rs]: This message probably needs to change if it is gated behind both empty datasets and catalogs.

File: crates/runtime/src/init/dataset.rs (hunk 1 above)
Comment (peasee) [reply crates/runtime/src/init/dataset.rs]: actually, we would still need the check just for datasets to exit early. But the check that generates a message could move out.

File: crates/runtime/src/lib.rs [hunk 3]
```diff
@@ -813,6 +813,16 @@ impl Runtime {
             }
         }
 
+        if let Some(app) = self.app.read().await.as_ref() {
```
Comment (Advayp) [inline crates/runtime/src/lib.rs]: I'm not sure if checking this in the middle of loading the components will limit concurrency or block for too long. I don't believe it should since all locks acquired by tasks in this method seem to be read locks, but again I'm not 100% sure.

Comment (peasee) [reply crates/runtime/src/lib.rs]: I would imagine the check would occur [here](https://github.com/spiceai/spiceai/pull/6296/files#diff-c6d4f276260e77036ce0adaf946b9ee6e55b1af1640342035121d4b254090df8L863). It could report the missing dataset/catalog message before Runtime reports ready. If the check occurs there, it should limit/avoid lock contention.

IIRC status will still `is_ready()` when there are no components loaded.

**Review by peasee — DISMISSED** [review]
Looks good, thanks! Could we get a before/after of the log output in the PR description?

**Comment by Advayp** [comment]
> Looks good, thanks! Could we get a before/after of the log output in the PR description?

Yup, I'll go and add that now.

**Comment by Advayp** [comment]
Done @peasee !

File: crates/runtime/src/lib.rs [hunk 4]
```diff
@@ -861,6 +861,17 @@ impl Runtime {
                             break;
                         }
                         if status.is_ready() {
+                            if let Some(app) = self.app.read().await.as_ref() {
+                                let valid_datasets =
+                                    Arc::clone(&self).get_valid_datasets(app, LogErrors(true));
```
Comment (phillipleblanc) [inline crates/runtime/src/lib.rs]: I don't think we need to log errors here?

Comment (Advayp) [reply crates/runtime/src/lib.rs]: You're right, I'll fix that.

File: crates/runtime/src/lib.rs [hunk 5]
```diff
@@ -861,6 +861,17 @@ impl Runtime {
...
                         }
                         if status.is_ready() {
+                            if let Some(app) = self.app.read().await.as_ref() {
+                                let valid_datasets =
+                                    Arc::clone(&self).get_valid_datasets(app, LogErrors(false));
+                                let valid_catalogs =
+                                    Arc::clone(&self).get_valid_catalogs(app, LogErrors(false));
+                                if valid_datasets.is_empty() && valid_catalogs.is_empty() {
+                                    tracing::info!(
+                                        "No datasets or catalogs were configured. If this is unexpected, please check the configuration of your Spicepod."
```
Comment (phillipleblanc) [inline crates/runtime/src/lib.rs]:
```suggestion
                                        "No datasets or catalogs were configured. If this is unexpected, check the Spicepod configuration."
```

**Review by phillipleblanc — DISMISSED** [review]

**Review by phillipleblanc — APPROVED** [review]
