### PR TITLE
Update data-components-contrib commit & fix e2e test reliability

### LINKED ISSUE #263: e2e tests are flaky

### PR DESCRIPTION
**Pull request by phillipleblanc**
Updating to the latest data-components-contrib commit

Also adds code to make the e2e tests more reliable

### CODE REVIEW

File: pkg/environment/environment.go [hunk 1]
```diff
@@ -9,6 +9,12 @@ import (
 	"golang.org/x/sync/errgroup"
 )
 
+var initCompleted bool = false
+
+func InitializationCompleted() bool {
```
Comment (lukekim) [inline pkg/environment/environment.go]:
```suggestion
func FirstInitComplete() bool {
```

File: pkg/environment/environment.go [hunk 2]
```diff
@@ -17,7 +23,9 @@ func InitDataConnectors() error {
 			return InitPodDataConnector(p)
 		})
 	}
-	return errGroup.Wait()
+	err := errGroup.Wait()
+	initCompleted = true
```
Comment (lukekim) [inline pkg/environment/environment.go]:
```suggestion
	if err != nil {
	    initCompleted = true
	}
```

**Review by lukekim — DISMISSED** [review]

**Review by lukekim — APPROVED** [review]
