### PR TITLE
fix: Ensure distributed Cayenne DML inserts are forwarded to executors

### LINKED ISSUE #9733: Distribute partitioned writes via DML to executors

### PR DESCRIPTION
**Pull request by peasee**
## 📝 Summary

* Ensures that Distributed Cayenne DML `INSERT` operations are forwarded to executors, similar to `UPDATE`/`DELETE` nodes
* Adds better error handling and identification around running Cayenne Catalog in non-distributed mode. Non-distributed Cayenne Catalog is not supported until https://github.com/spiceai/spiceai/issues/9942 is implemented

## 🔗 Related

* Closes #9733

### CODE REVIEW

File: crates/runtime/src/datafusion/mod.rs [hunk 1]
```diff
@@ -1006,6 +1006,57 @@ impl DataFusion {
...
+    /// and `ExecutorRegistry`, without requiring a full `DataFusion` reference.
+    ///
+    /// This is used by `DistributedCayenneInsertExec` which is constructed from the
+    /// extension planner and only has access to the session context.
+    pub async fn get_table_partition_expr_from_ctx(
+        ctx: &datafusion::prelude::SessionContext,
+        executor_registry: &ExecutorRegistry,
+        table_reference: &TableReference,
+    ) -> Result<Option<String>, DataFusionError> {
+        let catalog_name = match table_reference {
```
Comment (Jeadie) [inline crates/runtime/src/datafusion/mod.rs]: nit: `table_reference.catalog().unwrap_or(SPICE_DEFAULT_CATALOG)`?

File: crates/runtime/src/datafusion/mod.rs [hunk 2]
```diff
@@ -1006,6 +1006,57 @@ impl DataFusion {
         Ok(metadata.partition_expressions.get(idx).cloned())
     }
 
+    /// Returns the partition expression string for a table using only a `SessionContext`
+    /// and `ExecutorRegistry`, without requiring a full `DataFusion` reference.
+    ///
+    /// This is used by `DistributedCayenneInsertExec` which is constructed from the
+    /// extension planner and only has access to the session context.
+    pub async fn get_table_partition_expr_from_ctx(
```
Comment (Jeadie) [inline crates/runtime/src/datafusion/mod.rs:979]: We should standardise how we do this and `get_table_partition_expr`?.

**Review by lukekim — APPROVED** [review]

**Review by sgrebnov — APPROVED** [review]
