### PR TITLE
fix: Make S3 auth parameter validation more robust:

### LINKED ISSUE #3558: S3 UX: Specifying only an `s3_key` without an `s3_secret` does not return an error
## Describe the bug

When specifying only an `s3_key`, the S3 connector does not return an error.

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure an S3 dataset with only an `s3_key`
2. Observe no error

## Expected behavior

 Because `s3_key` is only valid in the presence of `s3_secret`, the Runtime should error when only one of either exists instead of both.

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: parquet
      s3_key: my-cool-key
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

### LINKED ISSUE #3559: Specifying `s3_auth: key` is not supported in the S3 connector
## Describe the bug

The S3 documentation states that `s3_auth: key` is a support parameter value, but the Runtime returns an error when specifying this parameter:

```
2024-11-18T23:45:12.001537Z  WARN runtime::init::dataset: Cannot connect to s3. Invalid or Unsupported Configuration: Unexpected S3 auth method: key
```

## To Reproduce

_Steps to reproduce the behavior:_

1. Create an S3 dataset with `s3_auth: key`
2. See error

## Expected behavior

The Runtime should support specifying `s3_auth: key`

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: parquet
      s3_auth: key
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by peasee**
## 🗣 Description

* Updates the S3 connector to properly validate for the existence of `s3_key` or `s3_secret`
* Updates the error messages to use clearer language, and a reference to the S3 parameter documentation

Example error:

```
2024-11-20T00:51:15.479542Z  WARN runtime::init::dataset: Error initializing dataset taxi_trips. The `s3_auth` was set to `key`, but no AWS access key was provided for credentials. Specify one with the `s3_key` parameter.
For futher information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth
```

Future error updates from #3506 will enhance the output of these errors into newlines better.

## 🔨 Related Issues

* Closes #3559 
* Closes #3558

### CODE REVIEW

File: crates/runtime/src/dataconnector/s3.rs [hunk 1]
```diff
@@ -33,10 +33,10 @@ use url::Url;
 
 #[derive(Debug, Snafu)]
 pub enum Error {
-    #[snafu(display("No AWS access secret provided for credentials"))]
+    #[snafu(display("The S3 authentication method was set to `key`, but no AWS access secret was provided for credentials.\nSpecify an access secret with the `s3_secret` parameter.\nFor futher information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"))]
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/s3.rs]:
```suggestion
    #[snafu(display("The S3 authentication method was set to `key`, but no AWS access secret was provided for credentials.\nSpecify an access secret with the `s3_secret` parameter.\nFor further information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"))]
```

File: crates/runtime/src/dataconnector/s3.rs [hunk 2]
```diff
@@ -33,10 +33,10 @@ use url::Url;
...
     NoAccessSecret,
 
-    #[snafu(display("No AWS access key provided for credentials"))]
+    #[snafu(display("The S3 authentication method was set to `key`, but no AWS access key was provided for credentials.\nSpecify an access key with the `s3_key` parameter.\nFor futher information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"))]
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/s3.rs]:
```suggestion
    #[snafu(display("The S3 authentication method was set to `key`, but no AWS access key was provided for credentials.\nSpecify an access key with the `s3_key` parameter.\nFor further information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"))]
```

File: crates/runtime/src/dataconnector/s3.rs [hunk 3]
```diff
@@ -45,16 +45,16 @@ pub enum Error {
         source: url::ParseError,
     },
 
-    #[snafu(display("Unsupported S3 authentication method '{method}', supported methods are: 'public' (i.e. no auth), 'iam_role', and 'key'."))]
+    #[snafu(display("The S3 authentication method '{method}' is not supported.\nUpdate the `s3_auth` parameter to use the supported `s3_auth` modes of 'public' (i.e. no auth), 'iam_role', or 'key'.\nFor futher information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"))]
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/s3.rs]:
```suggestion
    #[snafu(display("The S3 authentication method '{method}' is not supported.\nUpdate the `s3_auth` parameter to use the supported `s3_auth` modes of 'public' (i.e. no auth), 'iam_role', or 'key'.\nFor further information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"))]
```

File: crates/runtime/src/dataconnector/s3.rs [hunk 4]
```diff
@@ -45,16 +45,16 @@ pub enum Error {
...
     UnsupportedAuthenticationMethod { method: String },
 
     #[snafu(display(
-        "The 's3_key' parameter cannot be set unless the `s3_auth` parameter is set to 'key'."
+        "The '{parameter}' parameter cannot be set unless the `s3_auth` parameter is set to '{auth}'.\nFor futher information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/s3.rs]:
```suggestion
        "The '{parameter}' parameter cannot be set unless the `s3_auth` parameter is set to '{auth}'.\nFor further information, visit: https://docs.spiceai.org/components/data-connectors/s3#auth"
```

**Review by phillipleblanc — DISMISSED** [review]

**Review by lukekim — APPROVED** [review]
