### PR TITLE
Promote Iceberg Catalog Connector to Beta

### LINKED ISSUE #4110: Enhancement: Iceberg Catalog Connector Beta
## Goal-State/What/Result

The Iceberg Catalog Connector is at the Beta quality level.

## Why/Purpose

Part of our Roadmap for v1.0 Stable

## By When

**Issue/Spec written and reviewed:** Jan 7, 2025
**Done-Done:** Thu, Jan 16, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

The Beta release criteria expand on and require that all [Alpha release criteria](./alpha.md) continue to pass for the connector.

- [x] All [Alpha release criteria](./alpha.md) pass for this connector.
- [x] [Core Connector Data Types](../definitions.md) are supported.

#### Documentation

Documentation criteria should be re-checked on every release, to ensure the documentation is still accurate for the connector.

- [x] Documentation includes all information and steps for a user to set up the connector.
- [x] Documentation includes all known issues/limitations for the connector.
- [x] Documentation includes any exceptions made to allow this connector to reach Beta quality (e.g. if a particular data type cannot be supported by the connector).
- [x] The connector has an easy to follow cookbook recipe.
- [x] The connector status is updated in the table of connectors in [spiceai/docs](https://github.com/spiceai/docs).

#### UX

- [x] All of the connector's error messages follow the [error handling guidelines](../../dev/error_handling.md)

#### Testing

- [x] Integration tests to cover simple use cases based on the connector type, e.g. a Spicepod sourcing a file from an FTP server, reading latest GitHub issues, etc.

### Conditional Criteria

The following features/tests are dependent on the required features/tests for the specified connector, from the [Connector criteria table](#beta-release-criteria)

#### Streaming

- [x] Data is streamed when reading/performing queries from this connector.

#### Schema Inference

Support for schema inference in a connector is classified as:

- ☑️: Inferred schema. The source does not support natively detecting schema, and schema is inferred from the first row of results.
- ➖: Inferred schema. The connector does not support natively detecting schema, and schema is inferred from the first row of results.

#### Federation

Support for federation in a connector is classified as:

- ☑️: Partial filter push-down. The connector supports partial filter push-down in queries.
- ➖: No federation. The connector does not support federation or query push down.

##### Partial Filter Push-down

- [x] The connector supports filter push-down within a single dataset for common use case columns (e.g. `select * from my_dataset where id = 1`)
  - Common use case should be determined at the discretion of the DRI for the connector.
  - For example, the GitHub connector should support filter push-down for the author, state and title of issues.

#### Test Coverage

Indexes are not required for test coverage, but can be introduced if required for tests to pass (e.g. due to performance characteristics, etc).

##### TPC-H

- [x] End-to-end test to cover connecting to TPC-H SF1 for the connector type and benchmarking TPC-H queries (official and simple).
  - [x] Connectors should run all queries with no [Major Bugs](../definitions.md).
- [x] A test script exists that can load TPC-H data at the [designated scale factor](#beta-release-criteria) into this connector.
- [x] The connector can load TPC-H at the [designated scale factor](#beta-release-criteria), and can run all queries with no [Major Bugs](../definitions.md).
- [x] All [Minor Bugs](../definitions.md) for TPC-H are raised as issues.
- [x] TPC-H queries pass with a success rate equal or greater than TPC-H execution on Datafusion.

#### Data Correctness

Data Correctness is not tested using an automated method as part of Beta release criteria.

The Beta release criteria expand on and require that all [Alpha release criteria](./alpha.md) continue to pass for the Catalog.

- [x] All [Alpha release criteria](./alpha.md) pass for this Catalog.

Catalogs that use existing Data Connectors requires that the Data Connector must first be at Beta.

Catalogs without an existing Data Connector must perform the Beta Data Connector criteria in addition to the Catalog criteria.

### Existing Data Connector

This section is required if the Catalog uses an existing Data Connector.

- [x] The associated Data Connector for this Catalog is currently of Beta quality or higher.

### No Data Connector

This section is required if the Catalog does not use an existing Data Connector.

- [x] The Catalog passes the [Beta Data Connector release criteria](../connectors/beta.md)

### All Catalogs

- [x] An end-to-end test is created that loads the TPC-DS dataset at scale factor 1 using a Catalog, instead of specifying individual datasets.
  - [x] TPC-DS queries pass with a success rate equal to the native connector. For Catalogs without an existing Data Connector, queries pass with a success rate equal or greater than TPC-DS execution on Datafusion.
- [x] The Catalog can load the schema of a dataset without performing a data query at dataset registration time.
- [x] Known [Major](../definitions.md) bugs are resolved for the Catalog.
- [x] Known [Minor](../definitions.md) bugs are logged, but not required to be fixed unless needed to achieve TPC-H success.

### Documentation

- [x] Documentation includes all information and steps for a user to set up the Catalog.
- [x] Documentation includes all known issues/limitations for the Catalog.
- [x] The Catalog has an easy to follow cookbook recipe.
- [x] The Catalog status is updated in the table of Catalogs in [spiceai/docs](https://github.com/spiceai/docs).

### PR DESCRIPTION
**Pull request by phillipleblanc**
# 🗣 Description

Promotes the Iceberg Catalog Connector (and inherently the Data Connector) as beta.

## 🔨 Related Issues

Closes #4110

## 📄 Documentation Updates

https://github.com/spiceai/docs/pull/762

### CODE REVIEW

File: tools/testoperator/src/commands/mod.rs [hunk 1]
```diff
@@ -92,6 +92,7 @@ pub enum QueryOverridesArg {
     ODBCAthena,
     Duckdb,
     Snowflake,
+    IcebergSF1,
```
Comment (peasee) [inline tools/testoperator/src/commands/mod.rs:95]: Why IcebergSF1? do different overrides apply at higher scales?

Comment (phillipleblanc) [reply tools/testoperator/src/commands/mod.rs:95]: Due to how the tables are registered in the catalog, there will be different schemas for each scale factor. So we can't reference just `lineitem`, but `ice.tpch_sf1.lineitem`

**Review by peasee — DISMISSED** [review]

**Review by ewgenius — DISMISSED** [review]
