### PR TITLE
fix: Use SPICED_COMMIT for spiced_commit_sha

### LINKED ISSUE #5360: Update testoperator commit SHA to use spiced commit
The testoperator currently uses the SHA of the head of the branch it is running on - this is usually the same as the spiced commit, but not always.

### PR DESCRIPTION
**Pull request by peasee**
## 📝 Summary

* Updates testoperator benchmark metrics to omit the actual spiced commit for `spiced_commit_sha` instead of the current HEAD commit SHA. The HEAD commit SHA is renamed to `testoperator_commit_sha`.

## 🔗 Related

* Closes #5360

### CODE REVIEW

File: tools/testoperator/src/commands/bench/mod.rs [hunk 1]
```diff
@@ -75,6 +75,7 @@ pub(crate) async fn run(args: &DatasetTestArgs) -> anyhow::Result<RowCounts> {
     let (max_memory, median_memory) = observe_memory(memory_token, memory_readings).await?;
 
     let commit_sha = metrics.commit_sha.clone();
+    let spiced_commit_sha = std::env::var("SPICED_COMMIT")?;
```
Comment (phillipleblanc) [inline tools/testoperator/src/commands/bench/mod.rs]: If not set, this should just use `unknown`

**Review by phillipleblanc — DISMISSED** [review]

**Review by phillipleblanc — APPROVED** [review]

**Review by sgrebnov — APPROVED** [review]
