### PR TITLE
Only check for latest version once every 24 hours

### LINKED ISSUE #449: The automatic upgrade check uses the free GitHub API limits
**Describe the bug**
The automatic upgrade check for the CLI introduced in #425 has an unintended side effect that it consumes GitHub API requests on each call to check the version. Too many of these calls will result in this message:

`Error calling GitHub: {"message":"API rate limit exceeded for {ip address}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`

**To Reproduce**
Run the e2e tests a few times.

```bash
cd test/e2e
go test -v -e2e -context metal ./...
```

**Expected behavior**
I don't see an error message.

### PR DESCRIPTION
**Pull request by lukekim**
Closes #449 

We now store a file at `.spice/cli_version.txt` with the latest version and use that for the check. The file is only updated if it's last mod time is > 24 hours (once a day).

### CODE REVIEW

File: pkg/cli/cmd/run.go [hunk 1]
```diff
@@ -17,17 +16,15 @@ spice run
...
+		if err != nil && IsDebug() {
+			cmd.PrintErrf("failed to check for latest CLI release version: %s\n", err.Error())
 		}
 
 		err = runtime.Run(contextFlag, "")
-
 		if err != nil {
-			log.Println(err.Error())
+			cmd.PrintErrln(err.Error())
 			os.Exit(1)
```
Comment (phillipleblanc) [inline pkg/cli/cmd/run.go:28]:
```suggestion
```

**Review by phillipleblanc — APPROVED** [review]
