### PR TITLE
fix: Explicitly error for duplicate duckdb file accelerators

### LINKED ISSUE #2531: Validation that gracefully handles accelerating multiple datasets into the same DuckDB file
Currently this results in a hard crash:

```console
2024-09-05T03:51:48.557076Z  INFO runtime: Initialized results cache; max size: 128.00 MiB, item ttl: 1s
Assertion failed: (pointer.index < METADATA_BLOCK_COUNT), function Pin, file metadata_manager.cpp, line 54.
os: process already finished
```

Spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: tpch-sf1.db
datasets:
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpch-sf1.db
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
      params:
        duckdb_file: tpch-sf1-accelerated.db # Same as lineitem below
  - from: duckdb:lineitem
    name: lineitem
    params:
      duckdb_open: tpch-sf1.db
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
      params:
        duckdb_file: tpch-sf1-accelerated.db # Same as customer above
```

### PR DESCRIPTION
**Pull request by peasee**
## 🗣 Description

* Adds an additional check during accelerator creation to ensure that `duckdb_file` is unique across all DuckDB accelerated datasets.

## 🔨 Related Issues

* Closes #2531

### CODE REVIEW

File: crates/runtime/src/dataaccelerator/duckdb.rs [hunk 1]
```diff
@@ -65,6 +65,11 @@ pub enum Error {
 
     #[snafu(display("The \"duckdb_file\" acceleration parameter is a directory."))]
     InvalidFileIsDirectory,
+
+    #[snafu(display(
+        "The \"duckdb_file\" acceleration parameter \"{path}\" is not unique and in use by another dataset."
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/duckdb.rs]:
```suggestion
        r#"The "duckdb_file" acceleration parameter "{path}" is not unique and in use by another dataset."#
```

Slightly nicer

**Review by phillipleblanc — DISMISSED** [review]

**Review by phillipleblanc — APPROVED** [review]
