### PR TITLE
Parse postgres table schema from prepare statement, to support empty tables

### LINKED ISSUE #1351: The PostgreSQL connection is unable to retrieve the schema from empty tables
**Describe the bug**

Postgress connection adapter expects to get at least 1 row from table, to infer a table schema.

https://github.com/spiceai/spiceai/blob/4de4bfe70a1546ca51a9ef9b113234cf9d0fb8ef/crates/arrow_sql_gen/src/postgres.rs#L152-L158

https://github.com/spiceai/spiceai/blob/f09af0308f2eb89425ca7de24a6fc4856beb8be7/crates/db_connection_pool/src/dbconnection/postgresconn.rs#L102-L116

**Expected behavior**

Instead it should use [`Client::prepare`](https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Client.html#method.prepare) which will return table schema even on empty table.

### PR DESCRIPTION
**Pull request by ewgenius**
closes #1351 

Postgres data connector will parse schema from prepare statement, for proper empty table support.

Before - dataset from empty postgres table is registered, but schema is empty:

CleanShot 2024-05-21 at 11 03 55@2x

After:

https://github.com/spiceai/spiceai/assets/827338/73fad196-328b-469a-b12c-d84a7a6b2ff1

### CODE REVIEW

File: crates/arrow_sql_gen/src/postgres.rs [hunk 1]
```diff
@@ -142,6 +142,31 @@ macro_rules! handle_primitive_array_type {
...
+        let data_type = map_column_type_to_data_type(column_type);
+        match &data_type {
+            Some(data_type) => {
+                arrow_fields.push(Some(Field::new(column_name, data_type.clone(), true)));
+            }
+            None => arrow_fields.push(None),
+        }
+    }
+
+    let arrow_fields = arrow_fields.into_iter().flatten().collect::<Vec<Field>>();
```
Comment (ewgenius) [inline crates/arrow_sql_gen/src/postgres.rs:165]: that needs to validate the schema first

Comment (ewgenius) [reply crates/arrow_sql_gen/src/postgres.rs:165]: that is actually validated in `map_column_type_to_data_type`

**Review by lukekim — APPROVED** [review]
