### PR TITLE
Handle Snowflake Timestamp NTZ with seconds precision

### LINKED ISSUE #6083: Bug: Snowflake `Failed to cast snowflake timestamp to arrow timestamp: value is not a struct` error
## Describe the bug

Fetching Snowflake TIMESTAMP_NTZ(0) column results in `Failed to cast snowflake timestamp to arrow timestamp: value is not a struct` error

```
CREATE OR REPLACE TABLE TEST_TABLE_DATA_TYPES (
    id              INT AUTOINCREMENT,
    ts_ntz9         TIMESTAMP_NTZ,  -- nanoseconds precision - WORKS
    ts_ntz0         TIMESTAMP_NTZ(0),  -- seconds precision - Failed to cast snowflake timestamp to arrow timestamp: 
    ts_tz           TIMESTAMP_TZ
);
```

## To Reproduce

Create the following Snowflake table

``` sql
CREATE OR REPLACE TABLE TEST_TABLE_DATA_TYPES (
    id              INT AUTOINCREMENT,
    ts_ntz9         TIMESTAMP_NTZ,  -- nanoseconds precision - WORKS
    ts_ntz0         TIMESTAMP_NTZ(0),  -- seconds precision - Failed to cast snowflake timestamp to arrow timestamp: 
    ts_tz           TIMESTAMP_TZ
);

INSERT INTO TEST_TABLE_DATA_TYPES (ts_ntz9, ts_ntz0, ts_tz) VALUES
    ('2024-06-02 10:00:00.123456789', '2024-06-02 10:00:00', '2024-06-02 10:00:00.123456789 +00:00'),
    ('2024-06-02 03:00:00.987654321', '2024-06-02 03:00:00', '2024-06-02 03:00:00.987654321 -07:00'),
    ('2024-06-02 20:00:00.000000000', '2024-06-02 20:00:00', '2024-06-02 22:00:00.111111111 +02:00'),
    ('2024-12-31 23:59:59.000000000', '2024-12-31 23:59:59', '2024-12-31 23:59:59.999999999 +09:00'),
    (NULL, NULL, NULL);
```

```
sql> describe test;
+-------------+------------------------------------+-------------+
| column_name | data_type                          | is_nullable |
+-------------+------------------------------------+-------------+
| ID          | Decimal128(38, 0)                  | YES         |
| TS_NTZ9     | Timestamp(Nanosecond, None)        | YES         |
| TS_NTZ0     | Timestamp(Nanosecond, None)        | YES         |
| TS_TZ       | Timestamp(Nanosecond, Some("UTC")) | YES         |
+-------------+------------------------------------+-------------+

Time: 0.005828291 seconds. 4 rows.
```

```
sql> select TS_NTZ9 from test;
+-------------------------------+
| TS_NTZ9                       |
+-------------------------------+
| 2024-06-02T10:00:00.123456789 |
| 2024-06-02T03:00:00.987654321 |
| 2024-06-02T20:00:00           |
| 2024-12-31T23:59:59           |
|                               |
+-------------------------------+
```

```
sql> select TS_NTZ0 from test;
Query Error: Failed to execute query.
Error executing query: External error: Failed to cast snowflake timestamp to arrow timestamp: value is not a struct
```

### PR DESCRIPTION
**Pull request by kczimm**
## 📝 Summary

Appropriately handles the case where a Snowflake Timestamp NTZ uses seconds precision. `TIMESTAMP_NTZ(0)`

## 🔗 Related

Closes #6083

### CODE REVIEW

**Review by sgrebnov — DISMISSED** [review]

**Review by sgrebnov — APPROVED** [review]

File: crates/db_connection_pool/src/dbconnection/snowflakeconn.rs [hunk 1]
```diff
@@ -255,58 +256,72 @@ pub fn snowflake_schema_cast(record_batch: &RecordBatch) -> Result<RecordBatch,
...
-        UnableToCastSnowflakeTimestampSnafu {
-            reason: "value is not a struct",
-        },
-    )?;
-
-    let expected_fields = if is_tz { 3 } else { 2 };
-    if struct_array.columns().len() < expected_fields {
-        return UnableToCastSnowflakeTimestampSnafu {
-            reason: format!("value is not a struct with {expected_fields} columns"),
+    // Try to downcast to StructArray first
```
Comment (Sevenannn) [inline crates/db_connection_pool/src/dbconnection/snowflakeconn.rs:259]: Does the `column` input always guaranteed to contain timestamps with second precision?

Comment (kczimm) [reply crates/db_connection_pool/src/dbconnection/snowflakeconn.rs:259]: If the `column` input is a struct array, it should contain fields epoch and fraction. If it is a primitive array, that means it just has seconds precision (i.e. the epoch field only).
