### PR TITLE
Queries that cannot be planned show up in task history

### LINKED ISSUE #2742: Task: Queries with missing tables appear in `task_history`
Running a query in REPL for a table that doesn't exist is not populated in `task_history` as a failed query.

Part of  #2639

### PR DESCRIPTION
**Pull request by phillipleblanc**
## 🗣 Description

Queries that cannot be planned (i.e. due to referencing tables that don't exist) will now show up in the task_history table as an error.

Performing a query over Flight is a two-stage process, the first stage is calling `GetFlightInfo` which returns the schema of the query. The second stage is calling `DoGet` which performs the actual query. If the schema couldn't get retrieved because the query couldn't be planned, then the error should still be logged to task_history properly.

## 🔨 Related Issues

Closes #2742
Part of #2639

### CODE REVIEW

File: crates/runtime/src/datafusion/query/tracker.rs [hunk 1]
```diff
@@ -130,6 +130,11 @@ fn trace_query(query_tracker: &QueryTracker, truncated_output: &str) {
     if let Some(error_code) = &query_tracker.error_code {
         tracing::info!(target: "task_history", error_code = %error_code, "labels");
     }
+
+    if let Some(error_message) = &query_tracker.error_message {
+        tracing::error!(target: "task_history", "{error_message}");
+    }
```
Comment (peasee) [inline crates/runtime/src/datafusion/query/tracker.rs:136]: What does this look like in the task history? does it have an associated column?

**Review by peasee — APPROVED** [review]

File: crates/runtime/src/datafusion/query/tracker.rs (hunk 1 above)
Comment (phillipleblanc) [reply crates/runtime/src/datafusion/query/tracker.rs:136]: It shows up in the `error_message` column
