### PR TITLE
fix: Use GitHub search for pull_requests

### LINKED ISSUE #2833: Update the `pull_requests` query to use search with no filter parameters

### PR DESCRIPTION
**Pull request by peasee**
## 🗣 Description

* Updates `pull_requests` to use GitHub search API with the `github_use_search` option.

## 🔨 Related Issues

* Closes #2833

### CODE REVIEW

File: crates/runtime/src/dataconnector/github/pull_requests.rs [hunk 1]
```diff
@@ -22,12 +22,54 @@ use std::sync::Arc;
 pub struct PullRequestTableArgs {
     pub owner: String,
     pub repo: String,
+    pub use_search: bool,
```
Comment (lukekim) [inline crates/runtime/src/dataconnector/github/pull_requests.rs]: Let's make this: `query_mode`

Default: `github_query_mode: auto` (GraphQL + REST for blobs)

Option: `github_query_mode: search`

**Review by phillipleblanc — APPROVED** [review]
