### PR TITLE
Fix bug Changes in catalog.yaml would require saving in spicepod.yaml to apply

### LINKED ISSUE #2080: Bug: Changes in catalog.yaml would require saving in spicepod.yaml to apply
**Describe the bug**
When making changes to catalog.yaml for spiceai catalog, the changes don't apply when saved in catalog.yaml, it only apply when saved in spicepod.yaml

**To Reproduce**
1. Create a spice project, and configure in the following directory of project:

**spicepod.yaml**
```
version: v1beta1
kind: Spicepod
name: duckdb
catalogs:
  - ref: catalogs/sample
```
**catalogs/sample/catalog.yaml**
```
from: spiceai
name: spiceai
include:
  - "tpch.*" # Include only the "tpch" tables.
```

2. Start the spice runtime, and observe the catalog is successfully retrieving all tpch tables
3. Update **catalogs/sample/catalog.yaml** to the following, and save in catalog.yaml, notice that nothing is updated in runtime log
```
from: spiceai
name: spiceai
include:
  - "tpch.*" # Include only the "tpch" tables.
  - '*.*' # Include all "tpch" tables.

```
4. Go to spicepod.yaml, and save. Only at this time the catalog is updated and the update is displayed in runtime log

**Expected behavior**
Changes to catalog should be applied after saving in catalog.yaml

**spice, spiced, OS info**
- spice version:
CLI version:     v0.17.0-beta-rc.bbec0ff6
Runtime version: v0.17.0-beta-rc.bbec0ff6
- spiced version: 
v0.17.0-beta-rc.bbec0ff6
- OS info: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

**Have you tried this on the latest `trunk` branch?**

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by sgrebnov**
# 🗣 Description

1. Include catalog references to watch paths.
2. Add warning  when catalog is dynamically removed as this scenarios is not currently supported (DataFusion limitation)

## 🔨 Related Issues

Fixes https://github.com/spiceai/spiceai/issues/2080

## ⛓️‍💥 Breaking Change

* [ ] "Breaking Change" label added if this PR is a breaking change

### CODE REVIEW

File: crates/runtime/src/podswatcher.rs [hunk 1]
```diff
@@ -91,6 +90,19 @@ impl PodsWatcher {
     }
 }
 
+macro_rules! enable_watch_for_component {
```
Comment (sgrebnov) [inline crates/runtime/src/podswatcher.rs:93]: Also considered the following approach but chaining is not possible as ComponentOrReference items are of different types.

```
let all_components = chain!(
    spicepod.datasets.iter(),
    spicepod.models.iter(),
    spicepod.catalogs.iter(),
    spicepod.views.iter(),
    spicepod.embeddings.iter(),
    spicepod.evals.iter(),
    spicepod.tools.iter(),
);

for component in all_components {
    match component {
        ComponentOrReference::Reference(reference) => {
            let ref_path = root_dir.join(&reference.r#ref);
            dirs.push(root_dir.join(ref_path));
        }
        ComponentOrReference::Component(_) => { /* ignore component */ }
    }
}
```

**Review by phillipleblanc — DISMISSED** [review]

**Review by phillipleblanc — APPROVED** [review]
