### PR TITLE
Remove the memo when installing the runtime

### LINKED ISSUE #750: Runtime errors out on clean install
**Describe the bug**
On a clean install of the released binaries, performing a `spice run` will trigger a download of the runtime - but will fail on this step:

```bash
$ spice run
Spice.ai runtime starting...
The Spice.ai runtime has not yet been installed.
Checking for latest Spice runtime release...
Downloading and installing Spice.ai Runtime v0.7-alpha ...
Error downloading Spice runtime binaries.
chmod /Users/phillip/.spice/bin/spiced: no such file or directory
```

**To Reproduce**
Remove `~/.spice`, follow the instructions in the README

**Expected behavior**
The spice runtime is installed and runs.

### PR DESCRIPTION
**Pull request by phillipleblanc**
Fixes https://github.com/spiceai/spiceai/issues/750

### CODE REVIEW

File: bin/spice/pkg/github/runtime_release.go [hunk 1]
```diff
@@ -39,6 +38,7 @@ func GetLatestCliRelease() (*RepoRelease, error) {
 
 func DownloadRuntimeAsset(release *RepoRelease, downloadPath string) error {
 	assetName := GetRuntimeAssetName()
+	fmt.Println("Downloading Spice runtime...", assetName)
```
Comment (lukekim) [inline bin/spice/pkg/github/runtime_release.go]:
```suggestion
	fmt.Println("Downloading the Spice runtime...", assetName)
```

**Review by lukekim — DISMISSED** [review]

**Review by lukekim — APPROVED** [review]
