### PR TITLE
Make web search params engine-specific

### LINKED ISSUE #7003: Bug: Perplexity web search sometimes uses incorrect query schema (limit)
## Describe the bug

Image

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by Advayp**
## 📝 Summary
- See title

## 🔗 Related
- Closes #7003

### CODE REVIEW

File: crates/runtime/src/tools/builtin/web_search/mod.rs [hunk 1]
```diff
@@ -101,13 +102,15 @@ impl SearchEngine {
     }
 }
 
+#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
+#[serde(untagged)]
+pub enum WebSearchParamsType {
```
Comment (Jeadie) [inline crates/runtime/src/tools/builtin/web_search/mod.rs]:
```suggestion
pub enum WebSearchParams {
```
This should become `WebSearchParams` otherwise we will have a level of nesting in the tool interface.

i.e.
```shell
curl -XPOST http://localhost:8090/v1/tools/websearch -d '{
  "params": {
    "query": "my query"
  }
}'
```

**Review by sgrebnov — APPROVED** [review]
