### PR TITLE
Adjust DuckDB connection pool size based on DuckDB accelerator instances usage 

### LINKED ISSUE #5074: DuckDB connector time out waiting on connection when accelerating multiple datasets
## Describe the bug

DuckDB time out waiting on connection when accelerating multiple datasets (30+), either causing failure of creating accelerator or failure in writing data.

Example errors:
```
2025-03-17T10:20:22.821943Z  WARN runtime::init::dataset: Failed to setup the dataset testdb_001_iceberg_table_012 (iceberg).
Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: DbConnectionError: DuckDB connection failed.
timed out waiting for connection
Adjust the DuckDB connection pool parameters for sufficient capacity.
```

```
Failed to load data for dataset customer_demographics (s3): Failed to get data from the connector.
External error: DbConnectionError: DuckDB connection failed.
timed out waiting for connection
Adjust the DuckDB connection pool parameters for sufficient capacity.
Ensure the dataset configuration is valid, and try again.
```

## To Reproduce

Use the following spicepod, run spice run and observe the `timeout waiting for connection` error from duckdb.

```yaml
version: v1beta1
kind: Spicepod
name: structured-output-sample

datasets:
  - from: s3://spiceai-public-datasets/tpch/customer/
    name: customer_tpch
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/lineitem/
    name: lineitem
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/nation/
    name: nation
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/orders/
    name: orders
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/part/
    name: part
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/partsupp/
    name: partsupp
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/region/
    name: region
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/supplier/
    name: supplier
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/call_center/
    name: call_center
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/catalog_page/
    name: catalog_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/catalog_returns/
    name: catalog_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/catalog_sales/
    name: catalog_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/customer/
    name: customer
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/customer_address/
    name: customer_address
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/customer_demographics/
    name: customer_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/date_dim/
    name: date_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/household_demographics/
    name: household_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/income_band/
    name: income_band
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/inventory/
    name: inventory
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/item/
    name: item
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/promotion/
    name: promotion
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/reason/
    name: reason
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/ship_mode/
    name: ship_mode
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/store/
    name: store
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/store_returns/
    name: store_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/store_sales/
    name: store_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/time_dim/
    name: time_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/warehouse/
    name: warehouse
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_page/
    name: web_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_returns/
    name: web_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_sales/
    name: web_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_site/
    name: web_site
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
```

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by Sevenannn**
Pending on the merge and update of datafusion-table-provieder fork: https://github.com/datafusion-contrib/datafusion-table-providers/pull/275

# 🗣 Description

Detect the number of datasets accelerated into the same DuckDB file / memory accelerator instance, and adjust the duckdb connection pool size based on the number of datasets accelated into the same instance.

This is important because by default all duckdb accelerators accelerate data into same duckdb instance with a shared duckdb connection pool, without pool size adjustment acceleration will fail due to failure to obtain a connection to DuckDB from the shared connection pool

Calculate the max_size of DuckDB Connection Pool based on max(DEFAULT_MIN_IDLE_SIZE, num_datasets_accelerated). Where DEFAULT_MIN_IDLE_SIZE = 10

## 🔨 Related Issues

- Close: https://github.com/spiceai/spiceai/issues/5074
- Related: https://github.com/spiceai/spiceai/issues/5037
- Also fix the failed test: https://github.com/spiceai/spiceai/pull/5072

## ⛓️‍💥 Breaking Change

* [ ] "Breaking Change" label added if this PR is a breaking change

### CODE REVIEW

File: crates/runtime/src/dataaccelerator/duckdb.rs [hunk 1]
```diff
@@ -159,6 +182,8 @@ const PARAMETERS: &[ParameterSpec] = &[
     ParameterSpec::component("file"),
     ParameterSpec::runtime("file_watcher"),
     ParameterSpec::component("memory_limit"),
+    ParameterSpec::runtime("connection_pool_size")
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/duckdb.rs]: This shouldn't be a parameter that the user configures - Spice should know what value to set here based on how many datasets are attempting to accelerate into the same instance.

Comment (Sevenannn) [reply crates/runtime/src/dataaccelerator/duckdb.rs]: The` r2d2 connection pool doesn't allow dynamic resizing, we will need to know the duckdb instance information before initializing the duckdb accelerators / connection pool.

I can do a round of scan on duckdb dataset accelerator info when initializing accelerators, and pass the duckdb instance result when calling the `init` for duckdb accelerator. Would that be a good solution in this scenario?

File: crates/runtime/src/dataaccelerator.rs [hunk 2]
```diff
@@ -181,6 +196,14 @@ pub trait DataAccelerator: Send + Sync {
             false
         }
     }
+
+    /// For file based accelerator, update instance - datasets information
+    fn update_stats(
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator.rs]: I'm not sure what this is for - why do we need this?

Comment (Sevenannn) [reply crates/runtime/src/dataaccelerator.rs]: It is for a generic way to retain & update the acceleration instance usage information for accelerator, so that the accelerator can make use of it when calling `init`.

Comment (Sevenannn) [reply crates/runtime/src/dataaccelerator.rs]: The rationale beind this is that the `accelerator.init` need to know the instance usage information when being called in `initialize_accelerators`. 

One option is to retrieve / update instance information in the accelerator, which is what I'm implementing.

Another alternative could be getting the duckdb instance usage in `initialize_accelerators`, and directly passing through the instance usage information through `init` by adding an additional field, but I'm not sure if it's good practice to do a duckdb specific thing in the `initialize_accelerators` and modify the `init` function signature just for duckdb accelerator. 

Would you provide some feedback on what would be a better way to achieve the goal of getting the accelerator instance usage information for the usage in `accelerator.init`? Thanks!

File: crates/runtime/src/dataaccelerator/duckdb.rs [hunk 3]
```diff
@@ -72,6 +71,12 @@ pub enum Error {
 
     #[snafu(display("Invalid DuckDB acceleration configuration: {detail}"))]
     InvalidConfiguration { detail: Arc<str> },
+
+    #[snafu(display("Failed to retrieve DuckDB instance usage statistics. This is an internal error, please report it at github.com/spiceai/spiceai/issues"))]
+    UnableToGetInstanceUsage {},
+
+    #[snafu(display("Failed to update DuckDB instance usage statistics. This is an internal error, please report it at github.com/spiceai/spiceai/issues"))]
+    UnableToUpdateInstanceUsage {},
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/duckdb.rs]:
```suggestion
```

These aren't needed anymore right?

File: crates/runtime/src/dataaccelerator/duckdb.rs [hunk 4]
```diff
@@ -147,6 +157,54 @@ impl DuckDBAccelerator {
...
+                                    Some(file_instance_usage.map_or(1, |count| count + 1));
+                            }
+                        }
+                    }
+                }
+            }
+        }
+
+        file_instance_usage
+    }
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/duckdb.rs]: There is no point returning an `Option<u32>` - this method is trying to determine how many datasets are accelerating into the same file. It should always be at least 1 - at least the current dataset.

I would rename this to `get_num_accelerating_datasets` to indicate we're finding the number of datasets that are accelerating into this instance.

Also I don't see why we need two separate functions - we can just have one for both file/memory.

File: crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/duckdb.rs [hunk 5]
```diff
@@ -207,7 +208,8 @@ mod tests {
     #[tokio::test]
     async fn test_duckdb_migration() {
         let pool = Arc::new(
-            DuckDbConnectionPool::new_memory().expect("Failed to create in-memory DuckDB database"),
+            DuckDbConnectionPool::new_memory(None)
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/duckdb.rs]: This is a breaking change of the DuckDbConnectionPool method - let's create a builder struct `DuckDbConnectionPool` that allows you to set the various parameters, i.e.:

```rust
// Memory
let memory_pool = DuckDbConnectionPool::builder().memory().connection_pool_size(40).build()?;
// FIle
let file_pool = DuckDbConnectionPool::builder().file(path).access_mode(AccessMode::ReadOnly).connection_pool_size(40).build()?;
```

We can leave the existing methods for people that are already using these methods.

Also, if the connection pool size is explicitly specified, we shouldn't override it to 10 in the library function. The library should respect what the user gives us (principle of least surprise - I would be surprised if I told a library to set 5 connections and it set 10). So we should do the min idle connection calculation in Spice, not in the table providers repo.

**Review by phillipleblanc — CHANGES_REQUESTED** [review]

File: crates/runtime/src/dataaccelerator/duckdb.rs [hunk 6]
```diff
@@ -126,18 +127,32 @@ impl DuckDBAccelerator {
...
-                .get_or_init_memory_instance()
-                .await
-                .boxed()
-                .context(AccelerationCreationFailedSnafu)?,
+            (Ok(duckdb_file), Mode::File) => {
+                let num_accelerating_datasets =
+                    self.get_num_accelerating_datasets(Some(duckdb_file.as_str()), dataset.app());
+                let max_size = Self::get_max_size(num_accelerating_datasets);
+                self.duckdb_factory
+                    .get_or_init_file_instance_with_size_config(
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/duckdb.rs]: This should just use the builder

Comment (phillipleblanc) [reply crates/runtime/src/dataaccelerator/duckdb.rs]: I would create a new `get_or_init_instance_with_builder` and construct the builder that would be used to create the pool if it didn't already exist. Otherwise as we add method to the builder, we'll need to keep adding options to this method.

**Review by peasee — APPROVED** [review]

**Review by phillipleblanc — APPROVED** [review]
