### PR TITLE
Use proper federation in `max_timestamp_df` during acceleration refresh

### LINKED ISSUE #6908: max_timestamp_df query on accelerator table: top-k not pushed down and thus O(n)
## Describe the bug

The max timestamp is sorted and filtered in datafusion, not in the sqlite accelerator engine.
This leads to > 40 sec refresh times on tables with a couple of million rows.

## To Reproduce

1. Provide a dataset with `time_column`, and `time_format` `unix_millis` or `timestamptz` (probably all other formats too) and have it refresh for appends. See below for snippet.

2. Insert such debug info:

```diff
diff --git a/crates/runtime/src/accelerated_table/refresh_task.rs b/crates/runtime/src/accelerated_table/refresh_task.rs
index 0121b3a7a..a46b4c1ec 100644
--- a/crates/runtime/src/accelerated_table/refresh_task.rs
+++ b/crates/runtime/src/accelerated_table/refresh_task.rs
@@ -739,6 +739,7 @@ impl RefreshTask {
             .max_timestamp_df(ctx, &column)
             .map_err(find_datafusion_root)
             .context(super::UnableToScanTableProviderSnafu)?;
+        df.clone().limit(0, Some(100)).unwrap().explain(false, false).unwrap().show().await.unwrap();
         let result = &df
             .collect()
             .await
```

3. Observe the problematic plan:

```
+---------------+-------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                |
+---------------+-------------------------------------------------------------------------------------+
| logical_plan  | Sort: a DESC NULLS LAST, fetch=1                                                    |
|               |   Projection: CAST(?table?.create_time AS Timestamp(Nanosecond, None)) AS a         |
|               |     TableScan: ?table? projection=[create_time]                                     |
| physical_plan | SortPreservingMergeExec: [a@0 DESC NULLS LAST], fetch=1                             |
|               |   SortExec: TopK(fetch=1), expr=[a@0 DESC NULLS LAST], preserve_partitioning=[true] |
|               |     ProjectionExec: expr=[CAST(create_time@0 AS Timestamp(Nanosecond, None)) as a]  |
|               |       SchemaCastScanExec                                                            |
|               |         RepartitionExec: partitioning=RoundRobinBatch(8), input_partitions=1        |
|               |           SQLiteSqlExec sql=SELECT "create_time" FROM entity                        |
|               |                                                                                     |
```

Removing `EnsureSchema` in `fn accelerator_df` doesn't change to virtual exec either.

## Expected behavior

The plan for `max_timestamp_df` results in a `VirtualExecutionPlan` as it does in the flightsql context:

```
explain select create_time a from entity order by a limit 1;
...
VirtualExecutionPlan name=sqlite compute_context=.sqlite.xyz.db initial_sql=SELECT `entity`.`create_time` AS `a` FROM `entity` ORDER BY `a` ASC NULLS LAST LIMIT 1
````

### Spicepod

```yaml
  - name: entity
    from: postgres:olap.entity
    time_column: create_time
    time_format: timestamptz
    # equivalent outcome:
    #time_column: id
    #time_format: unix_millis
    acceleration:
      enabled: true
      mode: file
      engine: sqlite
      refresh_mode: append
      refresh_sql: select * from entity where create_time > now() - INTERVAL '1 year'
      refresh_check_interval: 2s
      primary_key: id
      on_conflict:
        id: upsert
      indexes:
        id: unique
        create_time: enabled
```

### Output of `describe table`

`describe entity;` (abbreviated)
```
+---------------+--------------------------------------------------------------------------------------------------------------------+-------------+
| column_name   | data_type                                                                                                          | is_nullable |
+---------------+--------------------------------------------------------------------------------------------------------------------+-------------+
| label         | Utf8                                                                                                               | YES         |
| id            | Int32                                                                                                              | YES         |
| create_time   | Timestamp(Nanosecond, Some("UTC"))                                                                                 | YES         |
+---------------+--------------------------------------------------------------------------------------------------------------------+-------------+
```

### Output of `explain query`

See debug info above.

### spice, spiced, OS info

- spiced version: `spiced --version`: v1.6.0-unstable
- OS info: `uname -a`: Darwin speyside 25.0.0 Darwin Kernel Version 25.0.0: Thu Aug 14 22:02:20 PDT 2025; root:xnu-12377.1.8~5/RELEASE_X86_64 x86_64 i386 Darwin

**Have you tried this on the latest `trunk` branch?**

- [x] Yes: `--no-default-features --features sqlite,postgres,flightsql,release`
- [ ] No

It's the same for some rc-1.5 version.

### PR DESCRIPTION
**Pull request by krinart**
Closes #6908 

The way we currently initilize dataframe in `max_timestamp_df` results in a full `TableScan` (see original ticket for more details)

In order to fix this we can downcast `accelerator` to `PolyTableProvider`, and then extract federated table source.

After doing this I ran into an issue with casting timestamp to `TIMESTAMP` in sqlite, which was addressed here https://github.com/spiceai/datafusion/pull/99 - hence updated datafusion dependencies

### CODE REVIEW

File: crates/runtime/src/accelerated_table/refresh_task.rs [hunk 1]
```diff
@@ -666,8 +667,30 @@ impl RefreshTask {
...
+
+        let table_source = Arc::new(DefaultTableSource::new(Arc::clone(&accelerator)));
+
+        // Get the columns so we can add projection to the plan. This
+        // converts the plan to federated where the correct dialect is applied
+        let schema = accelerator.schema();
+        let columns: Vec<Expr> = schema.fields().iter().map(|f| ident(f.name())).collect();
+
         // Records in the accelerator table are already filtered so we don't need to apply refresh SQL
-        ctx.read_table(Arc::new(EnsureSchema::new(Arc::clone(&self.accelerator))))
```
Comment (phillipleblanc) [inline crates/runtime/src/accelerated_table/refresh_task.rs:670]: We don't need the EnsureSchema anymore?

File: crates/runtime/src/accelerated_table/refresh_task.rs [hunk 2]
```diff
@@ -666,8 +667,30 @@ impl RefreshTask {
     }
 
     fn accelerator_df(&self, ctx: &SessionContext) -> Result<DataFrame, DataFusionError> {
```
Comment (phillipleblanc) [inline crates/runtime/src/accelerated_table/refresh_task.rs]: Let's add tests for this change

File: crates/runtime/src/accelerated_table/refresh_task.rs (hunk 1 above)
Comment (krinart) [reply crates/runtime/src/accelerated_table/refresh_task.rs:670]: Thanks, fixed!

File: crates/runtime/src/accelerated_table/refresh_task.rs (hunk 2 above)
Comment (krinart) [reply crates/runtime/src/accelerated_table/refresh_task.rs]: Done!

**Review by sgrebnov — DISMISSED** [review]

File: crates/runtime/src/accelerated_table/refresh_task.rs [hunk 3]
```diff
@@ -978,6 +958,75 @@ impl DataLoadTracing {
     }
 }
 
+// This function is moved from RefreshTask for the testing.
```
Comment (phillipleblanc) [inline crates/runtime/src/accelerated_table/refresh_task.rs]:
```suggestion
```

This could just be a comment in the PR, no need to keep it as a permanent comment in the code.

**Review by phillipleblanc — DISMISSED** [review]

**Review by sgrebnov — APPROVED** [review]
