### PR TITLE
fix(bedrock): return specific error messages for auth and stream failures

### LINKED ISSUE #6771: Bedrock outputs an unhandled error instead of an invalid authentication error
## Describe the bug

When invalid credentials are supplied to either a bedrock model or embedding, it outputs an `unhandled error` message:

```console
2025-08-15T07:27:40.278973Z  WARN runtime::init::model: Failed to load LLM: novash.
Failed to check the status of the model.
An error occurred: unhandled error (UnrecognizedClientException)
Verify the model configuration
```

However, `UnrecognizedClientException` is typically returned from smithy when an issue with authentication is encountered (like invalid access key, IAM role, etc).

## To Reproduce

_Steps to reproduce the behavior:_

1. Setup a Bedrock embedding or model with an invalid access key
2. Run spiced
3. See error

## Expected behavior

An informative error about invalid credentials should be presented.

### Spicepod

_Add the relevant `spicepod.yml` section._

```yaml
embeddings:
- from: bedrock:amazon.titan-embed-text-v2:0
    name: titan-embeddings
    params:
      dimensions: "256"
      aws_region: us-east-1
      aws_access_key_id: ${ secrets:AWS_ACCESS_KEY_ID }
      aws_secret_access_key: ${ secrets:AWS_SECRET_ACCESS_KEY }
      aws_session_token: ${ secrets:AWS_SESSION_TOKEN }
```

### PR DESCRIPTION
**Pull request by mvanhorn**
## 📝 Summary

When invalid credentials are supplied to a Bedrock model, the runtime outputs a generic "unhandled error" message. This replaces the catch-all error handler in the streaming path (`crates/llms/src/bedrock/chat/mod.rs:626-634`) with specific error matching for each `ConverseStreamOutputError` variant, and adds authentication failure detection for SDK-level errors.

The `// TODO specialise` comment at the catch-all branch indicated this was planned work.

**Before:** `An error occurred: unhandled error`
**After:** `Bedrock authentication failed. Check that your AWS credentials are valid and have permission to access Bedrock. Details: UnrecognizedClientException: ...`

## 🔗 Related

Closes #6771

## 👀 Notes for Reviewers

The change adds explicit match arms for `ThrottlingException`, `ValidationException`, `ModelStreamErrorException` in the streaming error handler. For non-`ServiceError` SDK errors (where auth failures surface), it checks the error string for known AWS auth error types (`UnrecognizedClientException`, `AccessDeniedException`, `InvalidSignatureException`, `ExpiredTokenException`, `IncompleteSignature`) to produce a targeted message.

This contribution was developed with AI assistance (Claude Code).

### CODE REVIEW

File: crates/llms/src/bedrock/chat/mod.rs [hunk 1]
```diff
@@ -624,18 +624,37 @@ impl BedrockConverse {
...
                             ee => {
-                                // TODO specialise
-                                Some(Err(to_api_error(ee.to_string())))
+                                Some(Err(to_api_error(format!("Bedrock error: {ee}"))))
                             }
                         }
                     }
                     Err(e) => {
-                        Some(Err(to_api_error(e.to_string())))
+                        let err_str = e.to_string();
```
Comment (Jeadie) [inline crates/llms/src/bedrock/chat/mod.rs:646]: nit: I think you can use `e.into_service_error() -> ConverseStreamOutputError`, and then match like above

```rust
 match e.err() {
  ConverseStreamOutputError::InternalServerException(e) => {
    Some(Err(to_api_error(format!("Bedrock internal server error: {e}"))))
  }                          
  // and more...
```

Comment (mvanhorn) [reply crates/llms/src/bedrock/chat/mod.rs:646]: Fixed in ca94c07 - switched to into_service_error().

Comment (Jeadie) [reply crates/llms/src/bedrock/chat/mod.rs:646]: No, sorry i mean to use it for this line
```diff
- let err_str = e.to_string();
+ e.into_service_error()
```

Comment (mvanhorn) [reply crates/llms/src/bedrock/chat/mod.rs:646]: Applied `into_service_error()` in f2f3582 - now the `Err(e)` arm tries to extract the typed service error first, falling back to string matching only for non-service SDK errors (timeouts, dispatch failures, etc.).

**Review by lukekim — APPROVED** [review]

**Comment by claudespice** [comment]
Hi @mvanhorn — the CI failures on this PR (Rust Lint + Build and Test) are caused by an infrastructure issue, not code problems. The self-hosted runners now require the updated sccache/spiceio setup from recent CI workflow changes on `develop` (PRs #10137, #10141, #10153), but re-running old workflow versions still uses the outdated config.

**To fix:** please merge `develop` into your branch to pick up the latest CI workflow files. This will trigger a fresh CI run with the correct configuration:

```bash
git fetch upstream develop
git merge upstream/develop
git push
```

The code itself merges cleanly with no conflicts. The PR has approvals and auto-merge enabled, so it should merge automatically once CI passes.

Also, could you enable "Allow edits from maintainers" on this PR so we can help with future updates if needed?

**Comment by mvanhorn** [comment]
Merged develop into both branches and pushed. Maintainer edits toggle didn't stick via API - I'll flip it on the web. Thanks for the heads up on the CI config change.
