### PR TITLE
Postgres login commands

### LINKED ISSUE #863: Bug: No way via CLI to login to a PostgreSQL server
**Describe the bug**
When attempting to use the PostgreSQL data connector with a secret stored in the file secret store - there is no CLI command to generate the correct secret structure, leaving a user unable to actually use the PostgreSQL connector.

**To Reproduce**
Navigate to the docs for PostgreSQL https://docs.spiceai.org/connectors/postgres/

Create a PostgreSQL dataset based on the example given:

```yaml
datasets:
  - from: postgres:path.to.my_dataset
    name: my_dataset
    params:
        pg_host: localhost
        pg_port: 5432
        pg_db: my_database
        pg_user: my_user
        pg_pass_key: my_secret
```

Start the runtime, get an error that `my_secret` doesn't exist.

### PR DESCRIPTION
**Pull request by mitchdevenport**
This PR adds support for `spice login postgres` and `spice login postgres engine` to login to postgres as a Data Connector and Acceleration Engine respectively.

This PR also adds a default engine secret name as `{engine_name}_engine` and a default for postgres secret keys as `{param}` to make logging in a more seamless experience.

Closes #863

### CODE REVIEW

File: bin/spice/cmd/login.go [hunk 1]
```diff
@@ -147,6 +147,36 @@ spice login s3 --access-key <key> --access-secret <secret>
...
+var postgresCmd = &cobra.Command{
+	Use:   "postgres",
+	Short: "Login to a Postgres instance",
+	Example: `
+spice login postgres --password <password>
+
+# See more at: https://docs.spiceai.org/
+`,
+	Run: CreateLoginRunFunc(api.AUTH_TYPE_POSTGRES, map[string]string{
+		passwordFlag: fmt.Sprintf("No password provided, use --%s or -p to provide a password", passwordFlag),
```
Comment (lukekim) [inline bin/spice/cmd/login.go:159]: If we support -p it seems we should also support -u for username?

Comment (mitchdevenport) [reply bin/spice/cmd/login.go:159]: We don't currently support postgres username in secrets, but we could add that and then add to the CLI. Though it's not entirely necessary since usernames aren't sensitive.

Comment (lukekim) [reply bin/spice/cmd/login.go:159]: Then, i think this is fine for this iteration/PR, but for consistency I would add it. Some organizations do consider usernames to be sensitive.

**Review by lukekim — APPROVED** [review]
