### PR TITLE
Scale support for Snowflake fixed-point numbers

### LINKED ISSUE #1537: Snowflake: accelerated query produces incorrect result
**Describe the bug**
When I follow [Snowflake quick start](https://github.com/spiceai/quickstarts/tree/trunk/snowflake) I see different results for the same query (non-accelerated and accelerated)

**To Reproduce**
1. Go to 'https://github.com/spiceai/quickstarts/tree/trunk/snowflake'
2. Run sample TPCH query for non accelerated dataset
```
version: v1beta1
kind: Spicepod
name: snowflake-app
datasets:
- from: snowflake:SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
  name: lineitem
```
Result:
```
+--------------+--------------+----------+----------------+----------------+--------------+--------------------+--------------------+----------------------+-------------+
| L_RETURNFLAG | L_LINESTATUS | SUM_QTY  | SUM_BASE_PRICE | SUM_DISC_PRICE | SUM_CHARGE   | AVG_QTY            | AVG_PRICE          | AVG_DISC             | COUNT_ORDER |
+--------------+--------------+----------+----------------+----------------+--------------+--------------------+--------------------+----------------------+-------------+
| A            | F            | 37734107 | 56586577106    | 56586577106    | 56586577106  | 25.522005853257337 | 38273.12973462167  | 0.049985295838397614 | 1478493     |
| N            | F            | 991417   | 1487505208     | 1487505208     | 1487505208   | 25.516471920522985 | 38284.4677608483   | 0.0500934266742163   | 38854       |
| N            | O            | 76633518 | 114935258407   | 114935258407   | 114935258407 | 25.50201963528761  | 38248.015609058646 | 0.05000025956756044  | 3004998     |
| R            | F            | 37719753 | 56568064200    | 56568064200    | 56568064200  | 25.50579361269077  | 38250.85462609966  | 0.05000940583012707  | 1478870     |
+--------------+--------------+----------+----------------+----------------+--------------+--------------------+--------------------+----------------------+-------------+
```
4. Add table acceleration and run the same query
```
version: v1beta1
kind: Spicepod
name: snowflake-app
datasets:
- from: snowflake:SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
  name: lineitem
  acceleration:
    enabled: true
    refresh_sql: |
      SELECT * FROM lineitem WHERE "L_SHIPDATE" <= DATE '1998-09-02'
```
Result
```
+--------------+--------------+------------+----------------+-----------------+------------------+--------------------+--------------------+-------------------+-------------+
| L_RETURNFLAG | L_LINESTATUS | SUM_QTY    | SUM_BASE_PRICE | SUM_DISC_PRICE  | SUM_CHARGE       | AVG_QTY            | AVG_PRICE          | AVG_DISC          | COUNT_ORDER |
+--------------+--------------+------------+----------------+-----------------+------------------+--------------------+--------------------+-------------------+-------------+
| A            | F            | 3773410700 | 5658655440073  | -22624317218527 | -113179099334294 | 2552.2005853257338 | 3827312.973462167  | 4.998529583839761 | 1478493     |
| N            | F            | 99141700   | 148750471038   | -595474952221   | -2994727549668   | 2551.647192052298  | 3828446.7760848305 | 5.009342667421629 | 38854       |
| N            | O            | 7447604000 | 11170172969774 | -44664820931570 | -223422983383122 | 2550.222676958499  | 3824911.798890827  | 4.999658605370408 | 2920374     |
| R            | F            | 3771975300 | 5656804138090  | -22610682824870 | -112931255676827 | 2550.5793612690773 | 3825085.462609966  | 5.000940583012706 | 1478870     |
+--------------+--------------+------------+----------------+-----------------+------------------+--------------------+--------------------+-------------------+-------------+
```

### PR DESCRIPTION
**Pull request by sgrebnov**
## ❓ What type of PR is this?
- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## 🗣 Description

Fixes https://github.com/spiceai/spiceai/issues/1537

Implement correct translation from Snowflake [Numeric data type](https://docs.snowflake.com/en/sql-reference/data-types-numeric) (Numbers up to 38 digits, with an optional precision and scale) with scale defined.

### CODE REVIEW

File: crates/db_connection_pool/src/dbconnection/snowflakeconn.rs [hunk 1]
```diff
@@ -191,6 +195,34 @@ pub fn snowflake_schema_cast(record_batch: &RecordBatch) -> Result<RecordBatch,
...
+                field.data_type(),
+                DataType::Decimal128(_, _) | DataType::Decimal256(_, _)
+            );
+
+            if !is_decimal_type && sf_logical_type.to_lowercase().as_str() == "fixed" {
+                if let (Some(precision_str), Some(scale_str)) =
+                    (field_metadata.get("precision"), field_metadata.get("scale"))
+                {
+                    if let (Ok(precision), Ok(scale)) =
+                        (precision_str.parse::<u8>(), scale_str.parse::<i8>())
```
Comment (peasee) [inline crates/db_connection_pool/src/dbconnection/snowflakeconn.rs:209]: **question:** What other arrow `DataType`s do we expect to receive here?

Comment (sgrebnov) [reply crates/db_connection_pool/src/dbconnection/snowflakeconn.rs:209]: Possible DataTypes here are Int8, 16, 32, etc.

**Review by peasee — APPROVED** [review]

**Review by phillipleblanc — APPROVED** [review]
