### PR TITLE
fix: Remove unused Cayenne parameters

### LINKED ISSUE #8039: Cayenne tuning parameters have no affect
## Describe the bug

_A clear and concise description of what the bug is._

For example, `cayenne_dict` or `cayenne_alp`. The only place these configuration parameters are used is in logging, and are unused for any actual accelerator behavior changes.

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by peasee**
## 📝 Summary

* Removes Cayenne parameters that have no actual effect.
* Removes vortex dependencies that are unused.
* Aligns the footer and segment cache defaults with the actual defaults from `VortexConfig`.
* Makes the data accelerator refresh plan output a `Level::TRACE` output instead of `Level::DEBUG`, as it is quite verbose.

## 🔗 Related

* Closes #8039

### CODE REVIEW

**Review by phillipleblanc — APPROVED** [review]

File: crates/runtime/src/dataaccelerator/cayenne.rs [hunk 1]
```diff
@@ -226,6 +226,14 @@ impl Default for CayenneAccelerator {
     }
 }
 
+fn parse_usize(acceleration: &Acceleration, key: &str, default: usize) -> usize {
+    acceleration
+        .params
+        .get(key)
+        .and_then(|v| v.parse::<usize>().ok())
```
Comment (Jeadie) [inline crates/runtime/src/dataaccelerator/cayenne.rs:233]: nit: Don't think you need `.ok()` because you can `.unwrap_or()` a Result.


```suggestion
        .and_then(|v| v.parse::<usize>())
```

File: crates/runtime/src/dataaccelerator/cayenne.rs [hunk 2]
```diff
@@ -507,37 +488,12 @@ const PARAMETERS: &[ParameterSpec] = &[
     ParameterSpec::component("unsupported_type_action")
         .description("How to handle data types not natively supported by Cayenne (internally using Vortex format) (Time32, Time64, Duration, Interval, Map, etc.). Options: 'string' (convert schema to Utf8, default - requires data source to provide string data), 'error' (fail on unsupported types), 'warn' (include in schema, may fail on insert), 'ignore' (skip unsupported fields)")
         .default("string"),
-    // Vortex encoding configuration for hardware acceleration
```
Comment (Jeadie) [inline crates/runtime/src/dataaccelerator/cayenne.rs:510]: If this is user configuration we want to add, should we have a tracking issue added whilst removing these?

**Review by Jeadie — APPROVED** [review]

File: crates/runtime/src/dataaccelerator/cayenne.rs (hunk 2 above)
Comment (peasee) [reply crates/runtime/src/dataaccelerator/cayenne.rs:510]: I don't think there is a need to control these for now.

File: crates/runtime/src/dataaccelerator/cayenne.rs (hunk 1 above)
Comment (peasee) [reply crates/runtime/src/dataaccelerator/cayenne.rs:233]: `.and_then()` must return an `Option<U>`
