### PR TITLE
Use binary data transfer for ftp

### LINKED ISSUE #1464: Unable to connect to FTP server vsftpd
**Describe the bug**
When trying to connect using the FTP Data Connector to an FTP server hosted by [vsftpd](https://security.appspot.com/vsftpd.html), it fails with the following error:

> 2024-05-22T00:00:31.278761Z  WARN runtime: Cannot connect to FTP. Object Store error: Generic FTP error: Invalid response: [550] 550 No support for resume of ASCII transfer.

**To Reproduce**
Create an Ubuntu VM/container and install vsftpd. This guide can be used: https://www.geeksforgeeks.org/how-to-setup-and-configure-an-ftp-server-in-linux/

```bash
sudo apt install vsftpd
sudo systemctl status vsftpd
sudo adduser ftpuser
sudo mkdir /ftp
sudo chown ftpuser /ftp
sudo nano /etc/vsftpd.conf # Use the contents of the below vsftpd.conf
```

`/etc/vsftpd.conf`
```conf
listen=NO
listen_ipv6=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
secure_chroot_dir=/var/run/vsftpd/empty
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO

pasv_min_port=5000
pasv_max_port=10000
local_root=/ftp
```

Spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: ftp

datasets:
- from: ftp:[IP of VM/Container]/demo.parquet
  name: demo
  params:
    file_format: parquet
    ftp_user: ftpuser
    ftp_pass: ftppass
```

**Expected behavior**
The FTP connection works. Using a separate FTP client (Transmit 5) works.

**Screenshots**
Screenshot 2024-05-22 at 9 15 30 AM

### PR DESCRIPTION
**Pull request by gloomweaver**
Sets the transfer type to binary

Before:
CleanShot 2024-05-27 at 3  14 49@2x
After:

CleanShot 2024-05-27 at 3  15 44@2x

closes #1464

### CODE REVIEW

File: crates/runtime/src/objectstore/ftp.rs [hunk 1]
```diff
@@ -122,6 +123,13 @@ fn pipe_stream(
         let mut total = 0;
         let mut buf = vec![0; 4096];
 
+        client
+            .transfer_type(FileType::Binary)
```
Comment (y-f-u) [inline crates/runtime/src/objectstore/ftp.rs:127]: should this be configurable in params?

Comment (gloomweaver) [reply crates/runtime/src/objectstore/ftp.rs:127]: No, we need to use binary to be able to use resume_transfer

**Review by phillipleblanc — APPROVED** [review]
