### PR TITLE
fix: Add explicit message for ODBC connector when not installed

### LINKED ISSUE #3560: Improve ODBC error when using the default Runtime
## Describe the bug

When attempting to load an ODBC source with the default Runtime binary (which ships without ODBC) returns an error that is not actionable:

```
2024-11-19T00:18:47.009026Z  WARN runtime::init::dataset: customer Invalid configuration for odbc. No source found for data connector
```

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure an ODBC dataset using the default Runtime binary
2. See error

## Expected behavior

User's should be directed to either the ODBC binary/docker image, or ODBC documentation for how to build with ODBC support.

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: odbc:table
    name: my_table
    params:
      odbc_connection_string: odbc_connection_string
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by peasee**
## 🗣 Description

* Updates the error message for when a data connector isn't valid to to explicitly check for ODBC and return a message about installing with ODBC support.

Before:
```bash
2024-12-02T03:57:24.187884Z  WARN runtime::init::dataset: test Cannot setup the dataset test (odbc).
The connector 'odbc' is not a valid connector.
For details, visit: https://docs.spiceai.org/components/data-connectors
```

After:
```bash
2024-12-02T04:04:44.851287Z  WARN runtime::init::dataset: test Cannot setup the dataset test (odbc).
The Runtime is running without ODBC support.
Build Spice with the `odbc` feature, or use the docker image with ODBC support.
For details, visit: https://docs.spiceai.org/components/data-connectors/odbc
```

## 🔨 Related Issues

* Closes #3560

### CODE REVIEW

File: crates/runtime/src/dataconnector.rs [hunk 1]
```diff
@@ -225,6 +227,12 @@ pub enum DataConnectorError {
         dataconnector: String,
         connector_component: ConnectorComponent,
     },
+
+    #[snafu(display("Cannot setup the {connector_component} ({dataconnector}).\nThe Runtime is running without ODBC support.\nBuild Spice with the `odbc` feature, or use the docker image with ODBC support.\nFor details, visit: https://docs.spiceai.org/components/data-connectors/odbc"))]
+    OdbcNotInstalled {
+        dataconnector: String,
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector.rs]: This is always ODBC right?

**Review by phillipleblanc — DISMISSED** [review]

File: crates/runtime/src/dataconnector.rs [hunk 2]
```diff
@@ -225,6 +227,11 @@ pub enum DataConnectorError {
         dataconnector: String,
         connector_component: ConnectorComponent,
     },
+
+    #[snafu(display("Cannot setup the {connector_component} (odbc).\nThe Runtime is running without ODBC support.\nBuild Spice with the `odbc` feature, or use the docker image with ODBC support.\nFor details, visit: https://docs.spiceai.org/components/data-connectors/odbc"))]
```
Comment (lukekim) [inline crates/runtime/src/dataconnector.rs]:
```suggestion
    #[snafu(display("Failed to initialize the {connector_component} (ODBC).\nThe runtime is built without ODBC support.\nBuild Spice.ai OSS with the `odbc` feature enabled or use the Docker image that includes ODBC support.\nFor details, visit: https://docs.spiceai.org/components/data-connectors/odbc"))]
```

File: crates/runtime/src/lib.rs [hunk 3]
```diff
@@ -134,6 +134,9 @@ pub enum Error {
     #[snafu(display("Unknown data connector: {data_connector}"))]
     UnknownDataConnector { data_connector: String },
 
+    #[snafu(display("The Runtime is running without ODBC support.\nBuild Spice with the `odbc` feature, or use the docker image with ODBC support.\nFor details, visit: https://docs.spiceai.org/components/data-connectors/odbc"))]
```
Comment (lukekim) [inline crates/runtime/src/lib.rs]:
```suggestion
    #[snafu(display("The runtime is built without ODBC support.\nBuild Spice.ai OSS with the `odbc` feature enabled or use the Docker image that includes ODBC support.\nFor details, visit: https://docs.spiceai.org/components/data-connectors/odbc"))]
```

**Review by lukekim — DISMISSED** [review]

**Review by phillipleblanc — APPROVED** [review]
