### PR TITLE
fix: Re-enable search integration tests

### LINKED ISSUE #6817: test `models::search::test_search_with_cache` is disabled
## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### LINKED ISSUE #6818: test `models::search::test_search_with_cache_bypass` is disabled
## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by peasee**
## 📝 Summary

* Re-enables ignored search integration tests
* Updates the catalog page dataset for search to use a pre-created parquet file which contains an ordered limited set of 20 rows from scale factor 1 (`order by cp_catalog_page_sk`) - this is a workaround due to https://github.com/spiceai/spiceai/issues/6876

## 🔗 Related

* Closes #6817
* Closes #6818

### CODE REVIEW

File: crates/runtime/tests/models/search.rs [hunk 1]
```diff
@@ -974,7 +988,7 @@ async fn test_text_search_multiple_columns() -> Result<(), anyhow::Error> {
 
 #[cfg(feature = "flightsql")]
 #[tokio::test]
-#[ignore] // https://github.com/spiceai/spiceai/issues/6816
+#[ignore]
```
Comment (phillipleblanc) [inline crates/runtime/tests/models/search.rs]:
```suggestion
```

File: crates/runtime/tests/models/search.rs [hunk 2]
```diff
@@ -318,7 +332,7 @@ pub(crate) async fn run_search(
 }
 
 #[tokio::test]
-#[ignore] // https://github.com/spiceai/spiceai/issues/6815
+#[ignore]
```
Comment (phillipleblanc) [inline crates/runtime/tests/models/search.rs]:
```suggestion
```
Did you mean to remove this ignore flag?

Comment (peasee) [reply crates/runtime/tests/models/search.rs]: No, these should still be ignored. I accidentally removed the comment while I was testing them.

**Review by phillipleblanc — APPROVED** [review]
