### PR TITLE
Handle OpenAI API Errors

### LINKED ISSUE #4413: Using structured outputs without having `json` in the prompt causes a 500 in Spice
## Describe the bug

Making a request to `http://localhost:8090/v1/chat/completions` and asking for structured output via the `response_format` parameter will return a 500 if the prompt does not contain the word "json". An error is logged in the runtime with the following:

`ERROR runtime::http::v1::chat: Error from v1/chat: invalid_request_error: 'messages' must contain the word 'json' in some form, to use 'response_format' of type 'json_object'. (param: messages)`

Spice should handle this and return the 400 to the user, not a 500

## To Reproduce

Configure a Spicepod with an openai model that supports structured outputs:

```yaml
models:
  - from: openai:gpt-4o-mini
    name: mini
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
      tools: auto
```

Make a request to the model and ask for a structured output without including the word JSON:

```bash
curl -v -L 'http://localhost:8090/v1/chat/completions' \
             -H 'Content-Type: application/json' \
             -H 'Accept: application/json' \
             -d '{
                     "messages": [
                       {
                         "content": "You only talk like a pirate",
                         "role": "system"
                       },
                       {
                         "content": "What can you do?",
                         "role": "user"
                       }
                     ],
                     "model": "mini",
                     "response_format": { "type": "json_object" }
                   }' 
```

## Expected behavior

The 400 is returned to the user, not a 500 with an error logged in the runtime

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

### PR DESCRIPTION
**Pull request by ewgenius**
# 🗣 Description

Handles OpenAI API errors, and pass error details and status in v1/chat/completions response

CleanShot 2025-01-20 at 16 03 36@2x
CleanShot 2025-01-20 at 16 58 46@2x
CleanShot 2025-01-20 at 16 58 58@2x

## 🔨 Related Issues

closes #4413

### CODE REVIEW

File: crates/runtime/src/http/v1/chat.rs [hunk 1]
```diff
@@ -221,3 +226,29 @@ impl OpenaiErrorEvent {
         }
     }
 }
+
+#[must_use]
+pub fn openai_error_to_response(e: OpenAIError) -> Response {
+    match e {
+        OpenAIError::InvalidArgument(_) => (StatusCode::BAD_REQUEST, e.to_string()).into_response(),
+        OpenAIError::ApiError(api_error) => {
+            let error_response = serde_json::json!({
```
Comment (Jeadie) [inline crates/runtime/src/http/v1/chat.rs:237]: Why doesn't `error_response` doesn't naturally serialise as this `json!` does

**Review by Jeadie — DISMISSED** [review]

File: crates/runtime/src/http/v1/chat.rs [hunk 2]
```diff
@@ -221,3 +226,29 @@ impl OpenaiErrorEvent {
         }
     }
 }
+
+#[must_use]
+pub fn openai_error_to_response(e: OpenAIError) -> Response {
```
Comment (Jeadie) [inline crates/runtime/src/http/v1/chat.rs:233]: Worth making a note that we should keep the error body untouched for OpenAI, so that users can use OpenAI error documentation

**Review by phillipleblanc — DISMISSED** [review]

File: crates/runtime/src/http/v1/chat.rs (hunk 1 above)
Comment (ewgenius) [reply crates/runtime/src/http/v1/chat.rs:237]: It can be serialized, but the type will be `Json<ApiError>` and there is no `into_response` implementation for this.
So have to construct json value directly.

File: crates/runtime/src/http/v1/chat.rs (hunk 2 above)
Comment (ewgenius) [reply crates/runtime/src/http/v1/chat.rs:233]: Done

**Review by sgrebnov — APPROVED** [review]
