### PR TITLE
Fix for idle DynamoDB Stream

### LINKED ISSUE #8493: DynamoDB streams is often encountering `ThrottlingException` from AWS
## Describe the bug

Run Spice with DynamoDB streams for a while and observe the following errors in logs:

> 2025-12-09T06:23:36.279689Z  INFO runtime: All components are loaded. Spice runtime is ready!
2025-12-09T06:26:47.869061Z  WARN dynamodb_streams::stream: Failed to discover new shards. Will retry on next iteration: Request has been throttled. Try again later
2025-12-09T06:29:27.767565Z  WARN dynamodb_streams::stream: Failed to discover new shards. Will retry on next iteration: Request has been throttled. Try again later
2025-12-09T06:33:17.465302Z  WARN dynamodb_streams::stream: Failed to discover new shards. Will retry on next iteration: Request has been throttled. Try again later

Review limits to see why we are getting this error - are we sending too many requests? Should we send fewer requests to stay under this limit?

This assumes the following PR is merged: https://github.com/spiceai/spiceai/pull/8492 - otherwise this is a hard error and the stream stops.

### PR DESCRIPTION
**Pull request by krinart**
## 📝 Summary

In presence of idle stream:
* Properly report watermark metric
* Default to 500 millisecond sleep to prevent throttling
* Produce batch even if it's empty which allows to report watermark, which in turn allows to report table as Ready

(Minor) - show following info log only when snapshots are enabled:
```rust
tracing::info!(
    "Snapshots for dataset {dataset_name} will be created every {threshold} batch updates"
);
```
## 🔗 Related

https://github.com/spiceai/spiceai/issues/7880
Closes https://github.com/spiceai/spiceai/issues/8493

## 🚨 Breaking Changes

N/A

## 📚 Docs

No user-facing changes

## 👀 Notes for Reviewers

N/A

### CODE REVIEW

File: crates/dynamodb-streams/src/lib.rs [hunk 1]
```diff
@@ -43,7 +43,7 @@ pub enum Error {
     #[snafu(display("Table not found"))]
     TableNotFound,
 
-    #[snafu(display("Stream not found"))]
+    #[snafu(display("Stream not found. Make sure the table is configured for streams"))]
```
Comment (phillipleblanc) [inline crates/dynamodb-streams/src/lib.rs]:
```suggestion
    #[snafu(display("DynamoDB Streams are not enabled on this table. Enable DynamoDB Streams and retry: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html#Streams.Enabling"))]
```

File: crates/runtime/src/dataconnector/dynamodb.rs [hunk 2]
```diff
@@ -293,6 +294,10 @@ impl DataConnector for DynamoDB {
                     load_or_initialize_checkpoint(&dynamodb, &dynamodb_sys, &dataset_name).await?;
 
                 if should_bootstrap {
+                    tracing::info!(
+                        "No existing checkpoint found for table {}, starting from bootstrap",
+                        dataset_name
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/dynamodb.rs]:
```suggestion
                        "No existing checkpoint found for table {dataset_name}, starting from bootstrap"
```

File: crates/runtime/src/dataconnector/dynamodb.rs [hunk 3]
```diff
@@ -342,6 +347,11 @@ impl DataConnector for DynamoDB {
                     )
                 } else {
                     // Resume reading from a checkpoint
+                    tracing::info!(
+                        "Found existing checkpoint for DynamoDB table {}, resuming from checkpoint. Table will be marked as Ready once stream lag reaches < '{}'",
+                        dataset_name,
+                        humantime::format_duration(acceptable_lag),
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/dynamodb.rs]:
```suggestion
                        "Found existing checkpoint for DynamoDB table {dataset_name}, resuming from checkpoint. Table will be marked as Ready once stream lag reaches < '{}'",
                        humantime::format_duration(acceptable_lag),
```

**Review by phillipleblanc — DISMISSED** [review]

**Review by phillipleblanc — DISMISSED** [review]

**Review by lukekim — APPROVED** [review]
