### PR TITLE
Record batch casting to fix SQLite data type issues

### LINKED ISSUE #1028: SQLite Data backend issue with Timestamp(microseconds) (needed in `taxi_trips` dataset).
**Describe the bug**
When loading the example taxi_trips data form S3 using the SQLite accelerator, the spice runtime fails and crashes.

**To Reproduce**
1. Edit spicepod.yaml with this configuration:

```yaml
version: v1beta1
kind: Spicepod
name: my_test
datasets:
- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  description: taxi trips in s3
  acceleration:
    enabled: true
    engine: sqlite
```
2. Open the sql repl
3. query the taxi_trips table
4. Observe the type conversion error in the spice runtime output:
```bash
thread '<unnamed>' panicked at crates/arrow_sql_gen/src/statement.rs:331:14:
not implemented: Data type mapping not implemented for Date32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-04-03T05:21:34.784751Z ERROR runtime::datafusion: Error adding data: Failed to update sqlite table: ConnectionClosed
```

**Expected behavior**
A successful query on the taxi_trips data

### LINKED ISSUE #1181: Unable to select timestamp field from Sqlite Data Accelerator
**Describe the bug**

There is the following error when query Timestamp field from Sqlite Data Accelerator

>Error receiving data: Decode error: Error decoding ipc RecordBatch: Invalid argument error: Need at least 80 bytes in buffers[0] in array of type Timestamp(Microsecond, None), but got 44

**To Reproduce**

1. Create the following pod
```yaml
version: v1beta1
kind: Spicepod
name: retention-quickstart
datasets:
- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  description: taxi trips in s3
  acceleration:
    enabled: true
    refresh_interval: 30s
    refresh_mode: full
    engine: sqlite
```
3. Run Spice REPL using `spice sql`
4. Perform query `select tpep_pickup_datetime from taxi_trips limit 10;`
7. See error
>Error receiving data: Decode error: Error decoding ipc RecordBatch: Invalid argument error: Need at least 80 bytes in buffers[0] in array of type Timestamp(Microsecond, None), but got 44

**Additional context**
Can query other fields
```bash
sql> select total_amount from taxi_trips limit 10
+--------------+
| total_amount |
+--------------+
| 27.5         |
| 18.37        |
| 35.28        |
| 15.96        |
| 26.88        |
| 90.94        |
| 51.3         |
| 62.89        |
| 39.85        |
| 12.9         |
+--------------+
```

taxi_trips format
```bash
sql> describe taxi_trips
+-----------------------+------------------------------+-------------+
| column_name           | data_type                    | is_nullable |
+-----------------------+------------------------------+-------------+
| VendorID              | Int32                        | YES         |
| tpep_pickup_datetime  | Timestamp(Microsecond, None) | YES         |
| tpep_dropoff_datetime | Timestamp(Microsecond, None) | YES         |
| passenger_count       | Int64                        | YES         |
| trip_distance         | Float64                      | YES         |
| RatecodeID            | Int64                        | YES         |
| store_and_fwd_flag    | LargeUtf8                    | YES         |
| PULocationID          | Int32                        | YES         |
| DOLocationID          | Int32                        | YES         |
| payment_type          | Int64                        | YES         |
| fare_amount           | Float64                      | YES         |
| extra                 | Float64                      | YES         |
| mta_tax               | Float64                      | YES         |
| tip_amount            | Float64                      | YES         |
| tolls_amount          | Float64                      | YES         |
| improvement_surcharge | Float64                      | YES         |
| total_amount          | Float64                      | YES         |
| congestion_surcharge  | Float64                      | YES         |
| Airport_fee           | Float64                      | YES         |
+-----------------------+------------------------------+-------------+
```

### LINKED ISSUE #1236: Enhancement: Convert accelerated schema to source schema
## Goal-State/What/Result

A mechanism can cast record from accelerator schema into the schema consumed by user.

## Why/Purpose

Databases(accelerator) have different types to Arrow data types; in order to serve records via flights, the record comes from accelerator needs to have the same arrow schema as the one registered in accelerated table provider. Or it will break on any mismatch which is very common now.

## By When

**Done-Done:** May 1st, 2024 AEST

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] ~~UX Review~~
- [x] ~~Threat Model / Security Review~~
- [x] Tests
- [x] ~~Documentation~~
- [x] ~~Samples/Quickstarts/Tutorials~~
- [x] Release Notes

## How/MAP

- A record batch utility to help cast the data from 1 schema to another schema with best effort.

- A datafusion idiomatic way to embed above function in the execution flow.

### PR DESCRIPTION
**Pull request by y-f-u**
fixes #1181 
fixes #1028 

fixes #1236

This introduces a RecordBatch helper that `try_cast_to` given schema for an existing record batch.

Also introduce a execution plan that casts the records in more engine primitive type schema to the schema defined in accelerated table.

Note, this is not trying to exhaust all possible casts, all casts need to be implemented on demand.

### CODE REVIEW

File: crates/arrow_tools/src/record_batch.rs [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+    datatypes::{DataType, Field, SchemaRef, TimeUnit},
+};
+use snafu::prelude::*;
+use std::{num::TryFromIntError, sync::Arc};
+
+pub type Result<T, E = Error> = std::result::Result<T, E>;
+
+#[derive(Debug, Snafu)]
+pub enum Error {
+    #[snafu(display("Error converting record batch: {}", source))]
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs]:
```suggestion
    #[snafu(display("Error converting record batch: {source}"))]
```

File: crates/arrow_tools/src/record_batch.rs [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+    ConvertRecordBatch { source: arrow::error::ArrowError },
+
+    #[snafu(display("Unable to convert array: {}", source))]
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs]:
```suggestion
    #[snafu(display("Unable to convert array: {source}"))]
```

File: crates/arrow_tools/src/record_batch.rs [hunk 3]
```diff
@@ -0,0 +1,267 @@
...
+    ParseTimestampFromString { source: chrono::ParseError },
+
+    #[snafu(display("Unable to convert {} array from {:?} to {:?}", name, from, to))]
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs]:
```suggestion
    #[snafu(display("Unable to convert {name} array from {from:?} to {to:?}"))]
```

File: crates/arrow_tools/src/record_batch.rs [hunk 4]
```diff
@@ -0,0 +1,267 @@
...
+    ConvertArrowArray {
+        from: DataType,
+        to: DataType,
+        name: String,
+    },
+
+    #[snafu(display("Unable to try from int: {}", source))]
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs]:
```suggestion
    #[snafu(display("Unable to try from int: {source}"))]
```

File: crates/arrow_tools/src/record_batch.rs [hunk 5]
```diff
@@ -0,0 +1,267 @@
...
+    ConvertInt { source: TryFromIntError },
+
+    #[snafu(display("Unable to use null for field {field}"))]
+    UnableToUseNullForField { field: String },
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs]:
```suggestion
    #[snafu(display("Field is not nullable: {field}"))]
    FieldNotNullable { field: String },
```

File: crates/arrow_tools/src/record_batch.rs [hunk 6]
```diff
@@ -0,0 +1,267 @@
...
+
+    #[snafu(display("Unable to downcast array {field} to {downcast_to}"))]
+    UnableToDowncast { field: String, downcast_to: String },
+}
+
+/// Cast a given record batch into a new record batch with the given schema.
+///
+/// # Errors
+///
+/// This function will return an error if the record batch cannot be casted.
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs]:
```suggestion
/// This function will return an error if the record batch cannot be cast.
```

File: crates/arrow_tools/src/record_batch.rs [hunk 7]
```diff
@@ -0,0 +1,267 @@
...
+#[allow(clippy::needless_pass_by_value)]
+pub fn try_cast_to(record_batch: RecordBatch, schema: SchemaRef) -> Result<RecordBatch> {
+    let existing_schema = record_batch.schema();
+
+    if schema.contains(&existing_schema) {
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs:47]: What are the semantics for `.contains()` and why we're returning a new record batch with the passed in schema instead of just returning it directly? It would be good to add this as a comment given its not obvious.

File: crates/arrow_tools/src/record_batch.rs [hunk 8]
```diff
@@ -0,0 +1,267 @@
...
+            if let (Ok(existing_field), Some(column)) = (
+                record_batch.schema().field_with_name(field.name()),
+                record_batch.column_by_name(field.name()),
+            ) {
+                if field.contains(existing_field) {
+                    Ok(Arc::clone(column))
+                } else {
+                    try_cast_array(Arc::clone(column), existing_field, field)
+                }
+            } else if field.is_nullable() {
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs:69]: What are the scenarios in which we want to do this vs just erroring? This basically means the requested schema has a column that doesn't exist in the source schema - which I would expect to be an error case.

File: crates/arrow_tools/src/record_batch.rs [hunk 9]
```diff
@@ -0,0 +1,267 @@
...
+                        .map(|f| f.map(i64::from))
+                        .collect::<Vec<Option<i64>>>(),
+                ))
+            } else {
+                UnableToDowncastSnafu {
+                    field: field.name(),
+                    downcast_to: "Int32Array".to_string(),
+                }
+                .fail()?
+            }
```
Comment (phillipleblanc) [inline crates/arrow_tools/src/record_batch.rs]:
```suggestion
            let array = array.as_any().downcast_ref::<Int32Array>().context(
                  UnableToDowncastSnafu {
                      field: field.name(),
                      downcast_to: "Int32Array".to_string(),
                  },
              )?;
              Arc::new(Int64Array::from(
                  array
                      .into_iter()
                      .map(|f| f.map(i64::from))
                      .collect::<Vec<Option<i64>>>(),
              ))
```

I find this a bit nicer.

**Review by phillipleblanc — COMMENTED** [review]
I think we may be able to use https://github.com/apache/arrow-rs/tree/master/arrow-cast for this instead of writing our own.

File: crates/arrow_tools/src/record_batch.rs (hunk 8 above)
Comment (y-f-u) [reply crates/arrow_tools/src/record_batch.rs:69]: Technically you can cast a record batch from less columns to more columns if the  new fields are nullable. Which can support schema expansion.

File: crates/arrow_tools/src/record_batch.rs [hunk 10]
```diff
@@ -0,0 +1,267 @@
...
+};
+use snafu::prelude::*;
+use std::{num::TryFromIntError, sync::Arc};
+
+pub type Result<T, E = Error> = std::result::Result<T, E>;
+
+#[derive(Debug, Snafu)]
+pub enum Error {
+    #[snafu(display("Error converting record batch: {}", source))]
+    ConvertRecordBatch { source: arrow::error::ArrowError },
```
Comment (ewgenius) [inline crates/arrow_tools/src/record_batch.rs]: Nitpick: I think error names should represent the failure
```suggestion
    UnableToConvertRecordBatch { source: arrow::error::ArrowError },
```

File: crates/arrow_tools/src/record_batch.rs (hunk 7 above)
Comment (y-f-u) [reply crates/arrow_tools/src/record_batch.rs:47]: Is about each field is a superset of the original one. Mostly it’s about nullable, when casting from a non-nullable to a nullable one, the change on schema needs to be considered.

Comment (y-f-u) [reply crates/arrow_tools/src/record_batch.rs:47]: Will add a comment in.

File: crates/arrow_tools/src/record_batch.rs (hunk 9 above)
Comment (y-f-u) [reply crates/arrow_tools/src/record_batch.rs]: good to know.

File: crates/arrow_tools/src/record_batch.rs (hunk 10 above)
Comment (y-f-u) [reply crates/arrow_tools/src/record_batch.rs]: Yeah, rust-analyzer suggested a common prefix is not preferred but I guess I can override the linter rule in this case.

File: crates/runtime/src/execution_plan/schema_cast.rs [hunk 11]
```diff
@@ -0,0 +1,138 @@
...
+    properties: PlanProperties,
+}
+
+impl SchemaCastScanExec {
+    pub fn new(input: Arc<dyn ExecutionPlan>, schema: SchemaRef) -> Self {
+        let eq_properties = input.equivalence_properties().clone();
+        let execution_mode = input.execution_mode();
+        let properties = PlanProperties::new(
+            eq_properties,
+            Partitioning::UnknownPartitioning(1),
```
Comment (phillipleblanc) [inline crates/runtime/src/execution_plan/schema_cast.rs]: This can match the input's Partitioning scheme

**Review by phillipleblanc — DISMISSED** [review]

**Review by digadeesh — DISMISSED** [review]

**Review by sgrebnov — APPROVED** [review]
