### PR TITLE
Make `file_format` parameter required

### LINKED ISSUE #1454: FTP/SFTP Connector - `file_format` should be required param, without default value
**Describe the bug**

When spicepod has configured csv file over FTP, without `file_format` - it is loaded as parquet (which is default) and fails

**Expected behavior**

User should specify desired file format, and get an error if `file_format` not provided

### PR DESCRIPTION
**Pull request by ewgenius**
closes #1454 

Require `file_format` parameter for listing table based connectors

### CODE REVIEW

File: crates/runtime/src/dataconnector.rs [hunk 1]
```diff
@@ -331,17 +331,22 @@ pub trait ListingTableConnector: DataConnector {
...
-            None | Some("parquet") => Ok((
+            Some("parquet") => Ok((
                 Arc::new(ParquetFormat::default()),
                 extension.unwrap_or(".parquet".to_string()),
             )),
             Some(format) => Err(DataConnectorError::InvalidConfiguration {
                 dataconnector: format!("{self}"),
                 message: format!(
-                    "Invalid file_format: {format}. Supported formats are: csv, parquet"
+                    "Invalid file_format: {format}. Supported formats are: csv, parquet."
```
Comment (lukekim) [inline crates/runtime/src/dataconnector.rs]:
```suggestion
                    "Unsupported file format '{format}'. Use csv or parquet."
```

**Review by lukekim — DISMISSED** [review]

**Review by sgrebnov — APPROVED** [review]
