### PR TITLE
Fix Iceberg predicates not matching the Arrow type of columns read from parquet files

### LINKED ISSUE #5707: Bug: Iceberg Data Connector fails when refresh_sql is set
## Describe the bug

When loading an Iceberg dataset using refresh_sql, the following error is observed:

```bash
2025-05-05T14:20:42.049428Z  WARN runtime::accelerated_table::refresh_task: Failed to load data for dataset audit_log (iceberg): Failed to get data from the connector.
External error: External error: External error: Unexpected => Failed to read a Parquet file, source: External: Invalid argument error: Invalid comparison operation: LargeUtf8 == Utf8
Ensure the dataset configuration is valid, and try again.
```

## To Reproduce

```yaml
version: v1
kind: Spicepod
name: iceberg-ai-demo

datasets:
  - from: iceberg:https://glue.ap-northeast-2.amazonaws.com/iceberg/v1/catalogs/211125479522/namespaces/security_logs/tables/audit_log
    name: audit_log
    params:
      iceberg_s3_region: ap-northeast-2
      iceberg_s3_access_key_id: ${ secrets:AWS_ACCESS_KEY_ID }
      iceberg_s3_secret_access_key: ${ secrets:AWS_SECRET_ACCESS_KEY }
      iceberg_s3_role_arn: ${ secrets:AWS_ROLE_ARN }
    time_column: timestamp
    time_format: timestamp
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

      # Refresh settings
      refresh_sql: |
        SELECT * FROM audit_log WHERE audit_log_type = 'sql_query'
      refresh_mode: append
      refresh_append_overlap: 30m
      refresh_check_interval: 10s

      # Retention settings
      retention_check_enabled: true
      retention_check_interval: 10m
      retention_period: 3d
```

### PR DESCRIPTION
**Pull request by phillipleblanc**
## 📝 Summary

Brings in an Iceberg change to fix predicates not matching the Arrow type of columns read from parquet files.

Also adds an integration test to validate the change works.

I also changed the test-framework to add a method that allows construction of an App from a spicepod yaml.

## 🔗 Related

- https://github.com/apache/iceberg-rust/pull/1308
- Closes: #5707

### CODE REVIEW

File: crates/test-framework/src/app_utils/mod.rs [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+};
+
+struct SpicepodString {
+    spicepod_str: String,
+}
+
+impl SpicepodString {
+    pub fn new(spicepod_str: Cow<'_, str>) -> Self {
+        Self {
+            spicepod_str: spicepod_str.into_owned(),
```
Comment (kczimm) [inline crates/test-framework/src/app_utils/mod.rs:35]: Super nit: I'm curious why the `Cow`? It's fairly specific for the caller.

```suggestion
    pub fn new<S: ToString>(spicepod_str: S) -> Self {
        Self {
            spicepod_str: spicepod_str.to_string(),
```

**Review by kczimm — APPROVED** [review]

File: crates/test-framework/src/app_utils/mod.rs (hunk 1 above)
Comment (phillipleblanc) [reply crates/test-framework/src/app_utils/mod.rs:35]: Ah yeah, this doesn't need to be a Cow anymore. My first implementation had tried to use the reference
