### PR TITLE
Fix `spice upgrade` command

### LINKED ISSUE #4656: Windows: `spice upgrade` prompts to restart the upgrade, but proceeds anyway
## Describe the bug

On Windows, when `spice upgrade` is run on a lower version than the latest released version, it will download the new CLI and prompt to restart the upgrade, but then proceeds with the runtime upgrade anyway:

```bash
PS C:\Users\phillip\code\llama> spice upgrade
2025/02/04 17:00:29 INFO Checking for latest Spice CLI release...
2025/02/04 17:00:30 INFO Upgrading the Spice.ai CLI ...
2025/02/04 17:00:33 INFO Spice.ai CLI upgraded to v1.0.2 successfully.
2025/02/04 17:00:33 INFO Please rerun the `spice upgrade` command to finish the runtime upgrade.
2025/02/04 17:00:33 INFO Downloading and installing Spice.ai Runtime v1.0.2 ...
2025/02/04 17:00:33 INFO Downloading the Spice runtime..., spiced.exe_models_cuda_86_windows_x86_64.tar.gz
2025/02/04 17:02:24 INFO Spice runtime installed into C:\Users\phillip\.spice\bin successfully.
2025/02/04 17:02:24 INFO Spice runtime upgraded to v1.0.2 successfully.
```

## To Reproduce

Download v1.0.1 of `spice` and `spiced`. Run `spice upgrade` on a Windows machine.

### LINKED ISSUE #4657: macOS: Running `spice upgrade` returns an error if the spice runtime isn't installed
## Describe the bug

When only the CLI is installed, it will print an error that the runtime isn't available when running `spice upgrade`. This likely affects Linux/Windows as well.

```bash
~/c/s/empty ❯❯❯ curl https://install.spiceai.org | /bin/bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7411    0  7411    0     0  10739      0 --:--:-- --:--:-- --:--:-- 10740
Getting the latest Spice.ai CLI...
Installing Spice CLI v1.0.1 ...
Downloading https://github.com/spiceai/spiceai/releases/download/v1.0.1/spice_darwin_aarch64.tar.gz ...
spice installed into /Users/phillip/.spice/bin successfully.
The Spice CLI is already in your PATH!

To get started with Spice.ai, visit https://spiceai.org/docs
~/c/s/empty ❯❯❯ spice version
CLI version:     v1.0.1
Runtime version: not installed
2025/02/04 17:35:20 INFO
CLI version v1.0.2 is now available!
To upgrade, run "spice upgrade".
~/c/s/empty ❯❯❯ spice upgrade
2025/02/04 17:35:25 INFO Checking for latest Spice CLI release...
2025/02/04 17:35:27 INFO Upgrading the Spice.ai CLI ...
2025/02/04 17:35:29 INFO Spice.ai CLI upgraded to v1.0.2 successfully.
2025/02/04 17:35:30 ERROR checking for runtime upgrade error="fork/exec /Users/phillip/.spice/bin/spiced: no such file or directory"
```

## To Reproduce

Download a previous CLI and ensure no runtime is installed.

## Expected behavior

No error should be printed and only the CLI is upgraded.

### LINKED ISSUE #4677: [CLI] `spice upgrade` should also upgrade the runtime, if it is detected
## Describe the bug

`spice upgrade` will only upgrade the CLI and relies on `spice run` to upgrade the runtime.

## To Reproduce

Ensure an older version of both CLI and runtime are installed.

Run `spice upgrade`

## Expected behavior

Both CLI and runtime are upgraded to the latest detected version.

### PR DESCRIPTION
**Pull request by Sevenannn**
# 🗣 Description

Fixes to spice upgrade command

- For https://github.com/spiceai/spiceai/issues/4677. The runtime will not be upgraded when it's a newer dev version / rc version/ local version. include messages to show user this fact

```
2025/02/07 16:25:00 INFO Checking for latest Spice CLI release...
2025/02/07 16:25:01 INFO Using the latest version v1.0.2. No upgrade required.
2025/02/07 16:25:01 INFO Checking for latest Spice Runtime release...
2025/02/07 16:25:03 INFO Using version v1.1.0-build.720ee3b7. No upgrade required.
```

- For https://github.com/spiceai/spiceai/issues/4657. Detect the runtime version first before upgrading. Show information of not upgrading runtime when runtime is not installed.

```
2025/02/07 16:29:35 INFO Checking for latest Spice CLI release...
2025/02/07 16:29:36 INFO Using the latest version v1.0.2. No upgrade required.
2025/02/07 16:29:36 INFO Checking for latest Spice Runtime release...
2025/02/07 16:29:36 INFO Spice runtime is not installed and won't be upgraded. Run `spice install` to install the runtime.
```

- For https://github.com/spiceai/spiceai/issues/4656. Fixed the upgrade logic so that the runtime upgrade for windows correctly pause after cli upgrade.

## 🔨 Related Issues

- Close https://github.com/spiceai/spiceai/issues/4677
- Close https://github.com/spiceai/spiceai/issues/4656
- Close https://github.com/spiceai/spiceai/issues/4657

## ⛓️‍💥 Breaking Change

* [ ] "Breaking Change" label added if this PR is a breaking change

### CODE REVIEW

File: bin/spice/cmd/upgrade.go [hunk 1]
```diff
@@ -68,14 +68,21 @@ spice upgrade
 			cleanupOldBinaries()
 		}
 
+		slog.Info("Checking for latest Spice Runtime release...")
```
Comment (sgrebnov) [inline bin/spice/cmd/upgrade.go]:
```suggestion
		slog.Info("Checking for the latest Spice Runtime release...")
```

**Review by sgrebnov — APPROVED** [review]

File: bin/spice/cmd/upgrade.go [hunk 2]
```diff
@@ -68,14 +68,21 @@ spice upgrade
...
+		currentVersion, err := rtcontext.Version()
+		if err != nil {
+			slog.Info("Spice runtime is not installed and won't be upgraded. Run `spice install` to install the runtime.")
```
Comment (sgrebnov) [inline bin/spice/cmd/upgrade.go:74]: Should we install runtime automatically in this case?

File: bin/spice/cmd/upgrade.go [hunk 3]
```diff
@@ -68,14 +68,21 @@ spice upgrade
...
+			return
+		}
+
 		runtimeUpgradeRequired, err := rtcontext.IsRuntimeUpgradeAvailable()
 		if err != nil {
 			slog.Error("checking for runtime upgrade", "error", err)
```
Comment (sgrebnov) [inline bin/spice/cmd/upgrade.go:80]: It seems we have an issue to update this logic
https://github.com/spiceai/spiceai/issues/4657

**Review by sgrebnov — DISMISSED** [review]

**Review by sgrebnov — DISMISSED** [review]

File: bin/spice/cmd/upgrade.go [hunk 4]
```diff
@@ -232,7 +239,9 @@ func upgradeCli(force bool, rtcontext *context.RuntimeContext) bool {
 		slog.Error("restarting CLI", "error", err)
 	}
 
-	return true
+	// For unix, this is unreachable
+	// For windows, the CLI will be restarted with the new binary, return false to terminate old CLI
```
Comment (phillipleblanc) [inline bin/spice/cmd/upgrade.go:243]: Please also update this comment to be accurate:

```rust
// Upgrade CLI
// Returns true if the CLI was upgraded successfully / no upgrade was required
// Returns false if the upgrade failed
func upgradeCli(force bool, rtcontext *context.RuntimeContext) bool {
```

**Review by phillipleblanc — APPROVED** [review]
