### PR TITLE
show tables; return same as show table

### LINKED ISSUE #1013: `show tables` and `show tables;` show different content
**Describe the bug**
As title described

**To Reproduce**
Type in two commands separately and compare the output.

**Expected behavior**
Output should be same.

### PR DESCRIPTION
**Pull request by y-f-u**
fix #1013

Make show tables; return same as `show tables`

Could make it more complicated using regex, but instead adding another dependency, this will resolve 99% of the time

### CODE REVIEW

File: crates/flightrepl/src/lib.rs [hunk 1]
```diff
@@ -109,7 +109,7 @@ pub async fn run(repl_config: ReplConfig) -> Result<(), Box<dyn std::error::Erro
                 println!("\nAny other line will be interpreted as a SQL query");
                 continue;
             }
-            "show tables" => {
+            "show tables" | "show tables;" => {
```
Comment (lukekim) [inline crates/flightrepl/src/lib.rs:112]: Why not just trim space and ;

**Review by lukekim — APPROVED** [review]

File: crates/flightrepl/src/lib.rs (hunk 1 above)
Comment (y-f-u) [reply crates/flightrepl/src/lib.rs:112]: to escape from rust ownership check, you would need to do multiple lines to get rid of multiple suffix, etc. 

Which is not as nice as this one.
