### PR TITLE
Standardize model parameter handling & prioritize `<model-prefix>_<param>` for model default overrides

### LINKED ISSUE #4494: Model default overrides only work when prefixed with `openai_` even for xAI and Anthropic providers
## Describe the bug

Default parameter overrides recognized onyly with `openai_` prefix, which is not consistent (other params prefixed with provider name) and not intuitive

```yaml
models:
  - from: xai:grok-2-latest
    name: groq
    params:
      xai_api_key: ${ secrets:XAI_API_KEY }
      openai_tool_choice: "auto"

  - from: anthropic:claude-3-5-sonnet-latest
    name: claude
    params:
      anthropic_api_key: ${secrets:ANTHROPIC_API_KEY}
      openai_tool_choice: "auto"
```

### PR DESCRIPTION
**Pull request by Sevenannn**
## 📝 Summary

Standardize model parameter handling by constructing the `Parameters` for each model provider when constructing the models. Each model provider has a const `ParameterSpec` defining the parameters accepted for each model provider. Use the `ParameterSpec::component` and `ParameterSpec::runtime` to distinguish the prefixed / non-prefixed model parameters.
- Model providers apart from `openai` takes `COMMON_MODEL_PARAMETERS`, which includes (1) common runtime params (tools, system_prompt, parameterized_prompt) for all params. (2) `<model-prefix>_<param>` component params (3) backward compatible `openai_<param>` runtime param.
- `openai` model provider takes `MODEL_PARAMETERS`, which includes (1) common runtime params (tools, system_prompt, parameterized_prompt) for all params. (2) `<model-prefix>_<param>` component params, which is `openai_<param>` in this case

Allow the `openai_<param>` and `<model_prefix>_param` at the same time, whereas the `<model_prefix>_param` takes a higher priority than the `openai_<param>`, and the `openai_<param>` is marked as deprecated.

Implemented a `short_name` method on `ModelSource` as the display implementation of `ModelSource` would return `huggingface` instead of model prefix `hf` for huggingface model provider. This is required for passing in a `prefix` when constructing the `Parameters` of each model.

Update the `get_openai_request_overrides` to prioritize using `<model-prefix>_<param>` over `openai_param`. Also implemented unit test for testing `get_openai_request_overrides`

Before:
```yaml
models:
  - from: xai:grok-2-latest
    name: groq
    params:
      xai_api_key: ${ secrets:XAI_API_KEY }
      openai_tool_choice: "auto"

  - from: anthropic:claude-3-5-sonnet-latest
    name: claude
    params:
      anthropic_api_key: ${secrets:ANTHROPIC_API_KEY}
      openai_tool_choice: "auto"
```

After:
```yaml
models:
  - from: xai:grok-2-1212
    name: xai
    params:
      tools: auto
      xai_api_key: ${ env:XAI_API_KEY }
      openai_temperature: 1
```

`openai_temperature` param is still supported but warned as deprecated
```shell
2025-06-24T22:16:15.030404Z  INFO runtime::init::model: Loading model [xai] from xai:grok-2-1212...
2025-06-24T22:16:15.030984Z  WARN runtime::parameters: Parameter 'openai_temperature' is deprecated for model xai: The `openai_<param>` language model overrides parameter is deprecated and will be removed in a future release. Please use `<model_prefix>_<param>` parameter name instead.
```

When both `openai_<param>` and `<model_prefix>_<param>` are specified, the `<model_prefix>_<param>` takes a higher priority than the `openai_<param>`.
```yaml
models:
  - from: xai:grok-2-1212
    name: xai
    params:
      tools: auto
      xai_api_key: ${ env:XAI_API_KEY }
      xai_temperature: 0.1. #This is used as final override
      openai_temperature: 1
```

```yaml
models:
  - from: xai:grok-2-1212
    name: xai
    params:
      tools: auto
      xai_api_key: ${ env:XAI_API_KEY }
      xai_blah: 1
```
```shell
2025-06-24T22:17:28.230651Z  INFO runtime::init::model: Loading model [xai] from xai:grok-2-1212...
2025-06-24T22:17:28.231371Z  WARN runtime::parameters: Ignoring parameter xai_blah: not supported for model xai.
```

## 🔗 Related

- Close: https://github.com/spiceai/spiceai/issues/4494

## 🚨 Breaking Changes

This changes affects the model parameters for all model providers except openai. Previously model default override params are specified as `openai_<param>` for any model provider, after the change it becomes `<model-provider-prefix>_<param>`. The  `openai_<param>`  are kept for backward compatibility and marked as deprecated.

## 📚 Docs

- https://github.com/spiceai/docs/pull/1032

### CODE REVIEW

File: crates/spicepod/src/component/model.rs [hunk 1]
```diff
@@ -165,6 +165,23 @@ impl Display for ModelSource {
     }
 }
 
+impl ModelSource {
+    #[must_use]
+    pub fn short_name(&self) -> &'static str {
```
Comment (phillipleblanc) [inline crates/spicepod/src/component/model.rs:193]: This is basically re-implementing the Prefix paradigm that we have for parameters: https://github.com/spiceai/spiceai/blob/trunk/crates/runtime/src/parameters.rs#L230 - instead of inventing an entirely new way to get prefixes for components, we should integrate with the model we already have for datasets.

File: crates/runtime/src/model/params/mod.rs [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+        out[i] = a[i];
+        i += 1;
+    }
+    let mut j = 0;
+    while j < M {
+        out[N + j] = b[j];
+        j += 1;
+    }
+    out
+}
```
Comment (Sevenannn) [inline crates/runtime/src/model/params/mod.rs:63]: Use the const function to reduce the duplicated definition of model override parameters in each model provider param spec.

File: crates/runtime/src/model/params/mod.rs [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+
+pub(crate) const PARAM_LEN: usize = 21;
+pub(crate) const PARAM_WITH_DEPRE_LEN: usize = 42;
+
+// Default Override parameters start with `<model_prefix>` is deprecated.
+pub(crate) const DEFAULT_OVERRIDE_PARAMETERS: [ParameterSpec; PARAM_LEN] = [
```
Comment (Sevenannn) [inline crates/runtime/src/model/params/mod.rs:68]: This is used only for openai model provider

File: crates/runtime/src/model/params/mod.rs [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+    ParameterSpec::component("top_p"),
+    ParameterSpec::component("tools"),
+    ParameterSpec::component("tool_choice"),
+    ParameterSpec::component("parallel_tool_calls"),
+    ParameterSpec::component("user"),
+];
+
+// Default Override parameters start with `openai_` is deprecated and will be removed in a future release.
+// Keep the `openai_` for backward compatibility, but recommend user using `<model_prefix>_<param>` instead.
+pub(crate) const DEFAULT_OVERRIDE_PARAMETERS_WITH_DEPRECATED: [ParameterSpec;
```
Comment (Sevenannn) [inline crates/runtime/src/model/params/mod.rs:94]: This is used for all model provider except openai to take the `<model-prefix>_<param>` while maintaining the backward compatibility of `openai_<param>`. The `openai_<param>` is marked as deprecated and will show warning logs to user when they attempt to use it.

File: crates/runtime/src/model/chat.rs [hunk 5]
```diff
@@ -449,3 +461,32 @@ fn file(
...
 }
+
+pub fn get_openai_request_overrides(model: &Model, prefix: &str) -> Vec<(String, Value)> {
+    let prefix_str = format!("{prefix}_");
+    model
+        .params
+        .iter()
+        .filter_map(|(k, v)| {
+            if k.starts_with(&prefix_str) {
+                k.strip_prefix(&prefix_str).and_then(|new_k| {
```
Comment (Sevenannn) [inline crates/runtime/src/model/chat.rs:472]: The `<model-prefix>_<param>` takes a higher priority than `openai_<param>`

File: crates/spicepod/src/component/model.rs (hunk 1 above)
Comment (Sevenannn) [reply crates/spicepod/src/component/model.rs:193]: I kept this method to get the prefix since the model prefix is still needed when constructing the `Parameters` for the model. There wasn't `Parameters` defined for model providers before this PR, and I added changes so that the model providers are standardized to use `Parameters` for param spec definition and handling.

**Review by sgrebnov — DISMISSED** [review]

File: crates/runtime/src/model/chat.rs [hunk 6]
```diff
@@ -449,3 +461,112 @@ fn file(
         chat_template_literal,
     )
 }
+
+// Get OpenAI compatible request parameter overrides.
+// Prioritizes parameters with the model prefix (e.g., `hf_temperature`) over deprecated (e.g. `hf_temperature`) parameters.
```
Comment (sgrebnov) [inline crates/runtime/src/model/chat.rs]:
```suggestion
// Prioritizes parameters with the model prefix (e.g., `hf_temperature`) over deprecated (e.g. `openai_temperature`) parameters.
```

File: crates/runtime/src/model/params/mod.rs [hunk 7]
```diff
@@ -0,0 +1,155 @@
...
+        out[N + j] = b[j];
+        j += 1;
+    }
+    out
+}
+
+pub(crate) const PARAM_LEN: usize = 24;
+pub(crate) const PARAM_WITH_DEPRE_LEN: usize = 45;
+
+// Model parameters that are used for openai model provider.
```
Comment (sgrebnov) [inline crates/runtime/src/model/params/mod.rs]:
```suggestion
// Model parameters that are used for openai model provider. Those parameters are supported by other (non-openai) models as well.
```

**Review by sgrebnov — APPROVED** [review]

**Review by kczimm — APPROVED** [review]
