### PR TITLE
Fix nsql sampling for tables with embeddings

### LINKED ISSUE #3854: Bug: nsql 'Row format support not yet implemented for: [SortField' error
## Describe the bug

>QueryError invalid args: Failed to execute query: Arrow error: Not yet implemented: Row format support not yet implemented for: [SortField { options: SortOptions { descending: false, nulls_first: true }, data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 1536) }]
nsql> 

## To Reproduce

1. Use quickstart below to create test Spciepod

https://github.com/spiceai/quickstarts/tree/trunk/search_github_files

Note: ensure chunking is enabled ([fix](https://github.com/spiceai/quickstarts/pull/242)) otherwise you will see errors like below
    chunking:
              enabled: true

Input validation error: `inputs` must have less than 256 tokens. Given: 709

1. Do `spice nsql`
2. `>test`
3. Observe
>QueryError invalid args: Failed to execute query: Arrow error: Not yet implemented: Row format support not yet implemented for: [SortField { options: SortOptions { descending: false, nulls_first: true }, data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 1536) }]
nsql>

### PR DESCRIPTION
**Pull request by sgrebnov**
# 🗣 Description

Updates sampling to perform `sample_distinct_from_column` only if the underlying column supports the ordering required for distinct sampling; otherwise, falls back to general sampling

## 🔨 Related Issues

Closes https://github.com/spiceai/spiceai/issues/3854

## 🤔 Concerns

1. Sampling should be further improved to skip internal columns. This improvement is still necessary/valid to avoid nsql failures for datasets with complex data types.

### CODE REVIEW

File: crates/runtime/src/tools/builtin/sample/distinct.rs [hunk 1]
```diff
@@ -129,26 +130,40 @@ impl SampleFrom for DistinctColumnsParams {
...
+                        .cols
+                        .as_ref()
+                        .is_some_and(|cols| cols.contains(column.name())))
             {
-                Self::sample_distinct_from_column(Arc::clone(&df), &tbl, column, self.limit).await?
+                Self::sample_distinct_from_column(Arc::clone(&df), &tbl, column.name(), self.limit)
+                    .await?
             } else {
-                Self::sample_from_column(Arc::clone(&df), &tbl, column, self.limit).await?
+                Self::sample_from_column(Arc::clone(&df), &tbl, column.name(), self.limit).await?
```
Comment (Jeadie) [inline crates/runtime/src/tools/builtin/sample/distinct.rs:149]: I know this is from the prior PR #3108 , but I don't understand why we still sample the column even if we explicitly decide to not sample the column ?

**Review by Jeadie — APPROVED** [review]

File: crates/runtime/src/tools/builtin/sample/distinct.rs (hunk 1 above)
Comment (sgrebnov) [reply crates/runtime/src/tools/builtin/sample/distinct.rs:149]: Good catch this will be improved as incremental PR.
