### PR TITLE
fix: Check ODBC parameters are positive integers

### LINKED ISSUE #3561: ODBC errors when setting `odbc_max_num_rows_per_batch` to 0
## Describe the bug

ODBC errors or has returns no results when specifying some parameter values as `0`:

* `odbc_max_bytes_per_batch` - returns `No results.`
* `odbc_max_num_rows_per_batch` - Panics on the inner thread task
* `odbc_max_text_size` and `odbc_max_binary_size` when set to `0` makes no observable change in my testing

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure an odbc dataset with parameter values set to `0`
2. Observe behavior

## Expected behavior

The Runtime should return an invalid configuration error when setting parameter values to `0`, as they are not supported.

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: odbc:table
    name: my_table
    params:
      odbc_connection_string: odbc_connection_string
      odbc_max_bytes_per_batch: 0
      odbc_max_num_rows_per_batch: 0
      odbc_max_text_size: 0
      odbc_max_binary_size: 0
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by peasee**
# 🗣 Description

* Adds validation to some ODBC parameters that are expected to be positive integers.

## 🔨 Related Issues

* Closes #3561

### CODE REVIEW

File: crates/runtime/src/dataconnector/odbc.rs [hunk 1]
```diff
@@ -176,12 +176,54 @@ fn driver_is_file(driver: &str) -> bool {
...
+}
+
 impl DataConnectorFactory for ODBCFactory {
     fn create(
         &self,
         params: DataConnectorParams,
     ) -> Pin<Box<dyn Future<Output = super::NewDataConnectorResult> + Send>> {
         Box::pin(async move {
+            if let Some(binary_size) = params.parameters.get("max_binary_size").expose().ok() {
+                parameter_is_integer!(binary_size);
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/odbc.rs]: I'm not a big fan of macros that obscure the control flow - I would prefer the macro just evaluate to a Result that can be returned directly here.

File: crates/runtime/src/dataconnector/odbc.rs [hunk 2]
```diff
@@ -176,12 +177,37 @@ fn driver_is_file(driver: &str) -> bool {
         .is_some()
 }
 
+fn parameter_is_integer(parameters: &Parameters, param: &str) -> Result<()> {
+    if let Some(value) = parameters.get("max_binary_size").expose().ok() {
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/odbc.rs]:
```suggestion
    if let Some(value) = parameters.get(param).expose().ok() {
```

**Review by phillipleblanc — APPROVED** [review]

**Review by Sevenannn — APPROVED** [review]
