### PR TITLE
fix: use the query error message when queries fail

### LINKED ISSUE #6226: Databricks SQL Warehouse errors aren't properly propagated
## Describe the bug

Running a query that performs a correlated scalar subquery in Databricks using the SQL Warehouse will return the following error:

`[UNSUPPORTED_SUBQUERY_EXPRESSION_CATEGORY.UNSUPPORTED_CORRELATED_SCALAR_SUBQUERY] Unsupported subquery expression: Correlated scalar subqueries can only be used in filters, aggregations, projections, and UPDATE/MERGE/DELETE commands:`

The TPCH Q2 query is able to trigger this:

```sql
select
    s_acctbal,
    s_name,
    n_name,
    p_partkey,
    p_mfgr,
    s_address,
    s_phone,
    s_comment
from
    part,
    supplier,
    partsupp,
    nation,
    region
where
        p_partkey = ps_partkey
  and s_suppkey = ps_suppkey
  and p_size = 15
  and p_type like '%BRASS'
  and s_nationkey = n_nationkey
  and n_regionkey = r_regionkey
  and r_name = 'EUROPE'
  and ps_supplycost = (
    select
        min(ps_supplycost)
    from
        partsupp,
        supplier,
        nation,
        region
    where
            p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
)
order by
    s_acctbal desc,
    n_name,
    s_name,
    p_partkey
limit 100;
```

Running this query in Spice where all tables are federated to Databricks SQL Warehouse results in the following unhelpful error:

```bash
Query Error: Failed to execute query.
Missing JSON field: result
sql>
```

The SQL Warehouse code is expecting to get results, and it is throwing an error that the `result` field isn't there, when the return value likely has the proper error message we should return instead.

### PR DESCRIPTION
**Pull request by kczimm**
## 📝 Summary

When SQL Warehouse returns an error, we propogate the error message to the user. 
## 🔗 Related

Closes:
- #6226

### CODE REVIEW

File: crates/data_components/src/databricks/sql_warehouse.rs [hunk 1]
```diff
@@ -89,6 +89,9 @@ pub enum Error {
 
     #[snafu(display("Failed to parse Databricks datatype: {reason}"))]
     ParseError { reason: String },
+
+    #[snafu(display("Query failure: {message}"))]
```
Comment (peasee) [inline crates/data_components/src/databricks/sql_warehouse.rs]:
```suggestion
    #[snafu(display("Failed to execute the query.\n{message}\nVerify the query is valid, or report a bug at: https://github.com/spiceai/spiceai/issues"))]
```

Please review the [error handling guide](https://github.com/spiceai/spiceai/blob/trunk/docs/dev/error_handling.md).

**Review by peasee — DISMISSED** [review]

**Review by sgrebnov — APPROVED** [review]
