### PR TITLE
Make `BigQueryDialect` more robust and add BigQuery TPC-H benchmark support in CI

### LINKED ISSUE #9992: ADBC BigQuery `Syntax error: Expected \")\" but got \"(\"` error (`tpch_simple_q7`)
## Describe the bug

https://github.com/spiceai/spiceai/actions/runs/23618826978/job/68793036802

>tpch_simple_q7: Failed to process query stream: Tonic error: status: 'Client specified an invalid argument', self: "Failed to execute query.\nFailed to execute query.\nInvalidArguments: [bq] Could not complete job: invalidQuery: Syntax error: Expected \")\" but got \"(\" at [1:106] (query) (sqlstate: [0, 0, 0, 0, 0], vendor_code: -2147483648)"

### PR DESCRIPTION
**Pull request by sgrebnov**
## 📝 Summary

Example benchmark run: https://github.com/spiceai/spiceai/actions/runs/23638440099/job/68852937690

Make BigQuery unparsing more robust by bringing the following improvements:
 - https://github.com/spiceai/datafusion/pull/147
 - https://github.com/spiceai/datafusion/pull/148

And add BigQuery query overrides and testoperator dispatch configuration to enable TPC-H benchmarks for ADBC BigQuery in CI:
- Added BigQuery Q1 override (`CAST(sum(...) AS DOUBLE)` to avoid BIGNUMERIC overflow producing NULL in ADBC Decimal128(38,27) mapping; [#9971](https://github.com/spiceai/spiceai/issues/9971)
- Added BigQuery Q6 override (explicit `BETWEEN 0.05 AND 0.07` to avoid float arithmetic precision). Note - BigQuery returns the same result for (0.06+0.01) so no tracking issue is created; the change is added so we can use official results for Q6
- Excluded queries with unsupported subqueries in JOIN ON predicates ([#9954](https://github.com/spiceai/spiceai/issues/9954))

## 🔗 Related

Closes https://github.com/spiceai/spiceai/issues/9992

### CODE REVIEW

File: crates/test-framework/src/queries/tpch/bigquery/q6.sql [hunk 1]
```diff
@@ -0,0 +1,10 @@
+select
+    sum(l_extendedprice * l_discount) as revenue
+from
+    lineitem
+where
+        l_shipdate >= date '1994-01-01'
+  and l_shipdate < date '1995-01-01'
```
Comment (sgrebnov) [inline crates/test-framework/src/queries/tpch/bigquery/q6.sql:7]: Runnung the same query with `between 0.06 - 0.01 and 0.06 + 0.01` directly returns the same incorrect result due to float arithmetic precision; switching to `between 0.05 and 0.07` as we can use results validation

File: Cargo.toml [hunk 2]
```diff
@@ -354,43 +354,43 @@ inherits = "dev"
...
-datafusion-functions-window-common = { git = "https://github.com/spiceai/datafusion.git", rev = "33a231531cf5406a13ae3ec1236baa37deb22eef" }  # spiceai-52
-datafusion-macros = { git = "https://github.com/spiceai/datafusion.git", rev = "33a231531cf5406a13ae3ec1236baa37deb22eef" }                   # spiceai-52
-datafusion-optimizer = { git = "https://github.com/spiceai/datafusion.git", rev = "33a231531cf5406a13ae3ec1236baa37deb22eef" }                # spiceai-52
-datafusion-physical-optimizer = { git = "https://github.com/spiceai/datafusion.git", rev = "33a231531cf5406a13ae3ec1236baa37deb22eef" }       # spiceai-52
-datafusion-spark = { git = "https://github.com/spiceai/datafusion.git", rev = "33a231531cf5406a13ae3ec1236baa37deb22eef" }                    # spiceai-52
-datafusion-substrait = { git = "https://github.com/spiceai/datafusion.git", rev = "33a231531cf5406a13ae3ec1236baa37deb22eef" }                # spiceai-52
+datafusion = { git = "https://github.com/spiceai/datafusion.git", rev = "c21494b69d3172aa58f2caf6ea258a25f4b793b1" }                       # spiceai-52
```
Comment (sgrebnov) [inline Cargo.toml]: SHA must be updated after PR is merged
 - https://github.com/spiceai/datafusion/pull/147

**Review by phillipleblanc — APPROVED** [review]
