### PR TITLE
Fix for search field as metadata for chunked search indexes

### LINKED ISSUE #7406: For chunked search indexes, metadata columns on search column store chunk, not entire content
## Describe the bug
When adding chunking to a search index, if the searchable column is added as vector index metadata, indexing will write the associated chunk, and not the entire document as the metadata.
```shell
 aws s3vectors list-vectors --vector-bucket-name test-bucket --index-name test-index  --return-metadata
```
```json
{
    "vectors": [
        {
            "key": "{\"location\":\"Users/jeadie/Github/spiceai/data/docx/my.docx\",\"_spice.chunk_id\":47}",
            "metadata": {
                "content_offset": [
                    7629,
                    7692
                ],
                "content": "Figure 1.5: Some nice figure in my document"
            }
        },
```

```yaml
datasets:
  - from: file:./data/docx/
    name: docx
    acceleration:
      enabled: true
    params:
      file_format: docx
    vectors:
      enabled: true
      engine: s3_vectors
      params:
        s3_vectors_bucket: test-bucket
        s3_vectors_index: test-index
    columns:
      - name: content
        embeddings:
          - from: openai_embeddings
            row_id: location
            chunking:
              enabled: true
              target_chunk_size: 256
        metadata:
          vectors: non-filterable
```

Issue can be found when vector search on this table vs on base table.
```sql
select location, score, length(content) as len from vector_search(docx, 'hello') order by score desc limit 3;
```
```
+-------------------------------------------------+---------------------+-----+
| location                                        | score               | len |
+-------------------------------------------------+---------------------+-----+
| Users/jeadie/Github/spiceai/data/docx/my.docx   | 0.3262062072753906  | 13  |
| Users/jeadie/Github/spiceai/data/docx/your.docx | 0.3262062072753906  | 13  |
| Users/jeadie/Github/spiceai/data/docx/our.docx  | 0.20198482275009155 | 122 |
+-------------------------------------------------+---------------------+-----+
```
```sql
select location, length(content) from docx limit 3;
```
```
+-------------------------------------------------+--------------------------------+
| location                                        | character_length(docx.content) |
+-------------------------------------------------+--------------------------------+
| Users/jeadie/Github/spiceai/data/docx/my.docx   | 11789                          |
| Users/jeadie/Github/spiceai/data/docx/your.docx | 19922                          |
| Users/jeadie/Github/spiceai/data/docx/our.docx  | 8919                           |
+-------------------------------------------------+--------------------------------+
```

### PR DESCRIPTION
**Pull request by Jeadie**
## 📝 Summary
 - When a search index is chunked and is based on a column that is also provided as a metadata column, the full column is not returned by the search index, just the associated chunk (when we list over an index, the first approprate chunk is returned).
 - This PR writes the full column to metadata by writing is as an internal aliased name (`CHUNKED_INDEX_FULL_SEARCH_FIELD`), and then using this column (instead of the underlying chunk) where appropriate. 

## 🔗 Related
- Resolves #7406

### CODE REVIEW

File: crates/runtime/src/embeddings/connector.rs [hunk 1]
```diff
@@ -371,6 +393,58 @@ impl EmbeddingConnector {
 
         Ok(ChangeEnvelope::new(change_committer, new_change_batch))
     }
+
+    /// Provide updated columns and underlying [`SchemaRef`] for a [`SearchIndex`] to use based off the index being chunked.
+    fn updated_chunked_search_index_format(
```
Comment (Jeadie) [inline crates/runtime/src/embeddings/connector.rs:397]: we must provide the metadata column (for s3 vectors, at the very least non-filterable columns) to the underlying search index before it creates the index (otherwise S3vectors cannot designate it as non-filterable).

File: crates/runtime/src/embeddings/connector.rs [hunk 2]
```diff
@@ -231,14 +236,34 @@ impl EmbeddingConnector {
...
                 &dataset.name,
                 column,
                 config.clone(),
                 vector_store,
-                Arc::clone(&inner_table_provider),
+                // Primary key. Use override from spicepod, fallback to underlying [`TableProvider`].
+                get_primary_keys(&inner_table_provider)
+                    .await
+                    .boxed()
+                    .map_err(|e| DataConnectorError::UnableToConnectInternal {
```
Comment (phillipleblanc) [inline crates/runtime/src/embeddings/connector.rs:258]: This is the error message that @peasee said we should improve on.

**Review by phillipleblanc — DISMISSED** [review]

File: crates/runtime/src/embeddings/connector.rs (hunk 2 above)
Comment (Jeadie) [reply crates/runtime/src/embeddings/connector.rs:258]: Not here, but I can make that change separately

**Review by phillipleblanc — APPROVED** [review]
