### PR TITLE
Clear plan cache when dataset updates

### LINKED ISSUE #5698: Enabled acceleration not picked up by runtime, on dataset hot reload
## Describe the bug

After updating spicepod with loaded dataset to enable acceleration, but not restarting runtime acceleration doesn't seem to take effect, though in logs and in /v1/datasets updated dataset is shown as accelerated:

https://github.com/user-attachments/assets/6be491aa-4dc5-4ccc-92b9-cadb501a28a1

reproduced for duckdb, sqlite and arrow accelerators, in memory and file mode.

## To Reproduce

Following the cookbook https://github.com/spiceai/cookbook/blob/trunk/duckdb/accelerator/README.md

```yaml
version: v1
kind: Spicepod
name: duckdb-acceleration-qs
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    description: taxi trips in s3
    params:
      file_format: parquet
    # acceleration:
    #   enabled: true
```

1. start runtime, query dataset

```console
sql> select "VendorID", tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count from taxi_trips limit 10;
+----------+----------------------+-----------------------+-----------------+
| VendorID | tpep_pickup_datetime | tpep_dropoff_datetime | passenger_count |
+----------+----------------------+-----------------------+-----------------+
| 1        | 2024-01-02T18:04:31  | 2024-01-02T18:11:49   | 0               |
...
| 1        | 2024-01-02T18:05:25  | 2024-01-02T18:17:25   | 0               |
+----------+----------------------+-----------------------+-----------------+

Time: 1.8748850419999998 seconds. 10 rows.
```

2. uncomment acceleration, **without restartin runtime**, wait when dataset reloaded:

```console
2025-05-05T13:28:25.953090Z  INFO runtime::init::dataset: Updating accelerated dataset taxi_trips...
2025-05-05T13:28:28.339408Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset taxi_trips
2025-05-05T13:28:44.398956Z  INFO runtime::accelerated_table::refresh_task: Loaded 2,964,624 rows (399.41 MiB) for dataset taxi_trips in 16s 59ms.
2025-05-05T13:28:46.777973Z  INFO runtime::init::dataset: Dataset taxi_trips registered (s3://spiceai-demo-datasets/taxi_trips/2024/), acceleration (arrow), results cache enabled.
```

3. query again - still slow as not accelerated

```console
sql> select "VendorID", tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count from taxi_trips limit 10;
+----------+----------------------+-----------------------+-----------------+
| VendorID | tpep_pickup_datetime | tpep_dropoff_datetime | passenger_count |
+----------+----------------------+-----------------------+-----------------+
| 2        | 2024-01-14T18:31:43  | 2024-01-14T18:54:45   | 3               |
...
| 2        | 2024-01-14T18:03:22  | 2024-01-14T18:11:23   | 3               |
+----------+----------------------+-----------------------+-----------------+

Time: 1.844619875 seconds. 10 rows.
```

4. restart runtime and query again - fast as expected:

```console
sql> select "VendorID", tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count from taxi_trips limit 10;
+----------+----------------------+-----------------------+-----------------+
| VendorID | tpep_pickup_datetime | tpep_dropoff_datetime | passenger_count |
+----------+----------------------+-----------------------+-----------------+
| 1        | 2024-01-27T10:50:57  | 2024-01-27T11:06:17   | 1               |
...
| 2        | 2024-01-27T10:07:49  | 2024-01-27T10:27:41   | 1               |
+----------+----------------------+-----------------------+-----------------+

Time: 0.009452916 seconds. 10 rows.
```

## Expected behavior

dataset should be accelerated after reload

## Runtime Details

### Output of `explain query`

not accelerated dataset:

```console
sql> explain select "VendorID", tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count from taxi_trips limit 10;
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Limit: skip=0, fetch=10                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|               |   BytesProcessedNode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|               |     TableScan: taxi_trips projection=[VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count], fetch=10                                                                                                                                                                                                                                                                                                                                                                               |
| physical_plan | GlobalLimitExec: skip=0, fetch=10                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|               |   CoalescePartitionsExec                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|               |     BytesProcessedExec                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|               |       ParquetExec: file_groups={10 groups: [[taxi_trips/2024/yellow_tripdata_2024-01.parquet:0..9659769], [taxi_trips/2024/yellow_tripdata_2024-01.parquet:9659769..19319538], [taxi_trips/2024/yellow_tripdata_2024-01.parquet:19319538..28979307], [taxi_trips/2024/yellow_tripdata_2024-01.parquet:28979307..38639076], [taxi_trips/2024/yellow_tripdata_2024-01.parquet:38639076..48298845], ...]}, projection=[VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count], limit=10 |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

updated spicepod to enable acceleration:

```
sql> explain select "VendorID", tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count from taxi_trips limit 10;
+---------------+-------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                    |
+---------------+-------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Limit: skip=0, fetch=10                                                                                                 |
|               |   BytesProcessedNode                                                                                                    |
|               |     TableScan: taxi_trips projection=[VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count], fetch=10 |
| physical_plan | GlobalLimitExec: skip=0, fetch=10                                                                                       |
|               |   CoalescePartitionsExec                                                                                                |
|               |     BytesProcessedExec                                                                                                  |
|               |       SchemaCastScanExec                                                                                                |
|               |         RepartitionExec: partitioning=RoundRobinBatch(10), input_partitions=1                                           |
|               |           MemoryExec: partitions=1, partition_sizes=[362]                                                               |
|               |                                                                                                                         |
+---------------+-------------------------------------------------------------------------------------------------------------------------+
```

after restart:

```
sql> explain select "VendorID", tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count from taxi_trips limit 10;
+---------------+-------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                    |
+---------------+-------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Limit: skip=0, fetch=10                                                                                                 |
|               |   BytesProcessedNode                                                                                                    |
|               |     TableScan: taxi_trips projection=[VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count], fetch=10 |
| physical_plan | GlobalLimitExec: skip=0, fetch=10                                                                                       |
|               |   CoalescePartitionsExec                                                                                                |
|               |     BytesProcessedExec                                                                                                  |
|               |       SchemaCastScanExec                                                                                                |
|               |         RepartitionExec: partitioning=RoundRobinBatch(10), input_partitions=1                                           |
|               |           MemoryExec: partitions=1, partition_sizes=[362]                                                               |
|               |                                                                                                                         |
+---------------+-------------------------------------------------------------------------------------------------------------------------+
```



### spice, spiced, OS info

- CLI version:     v1.2.0
- Runtime version: v1.2.0+models.metal
- OS info: `Darwin Evgeniis-MacBook-Pro.local 24.4.0 Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:47 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6000 arm64`

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by kczimm**
## 📝 Summary

Clears the plan cache when a dataset is updated in the SpicePod in case the update causes the cached logical plans to be obsolete.

## 🔗 Related

- Closes https://github.com/spiceai/spiceai/issues/5698

### CODE REVIEW

**Review by lukekim — APPROVED** [review]

File: crates/runtime/src/init/dataset.rs [hunk 1]
```diff
@@ -453,6 +453,11 @@ impl Runtime {
     async fn update_dataset(&self, ds: Arc<Dataset>) {
         self.status
             .update_dataset(&ds.name, status::ComponentStatus::Refreshing);
+
+        // Updating a dataset may cause the cached LogicalPlans to be
+        // obsolete, so we remove them
+        self.df.clear_cached_plans();
```
Comment (Sevenannn) [inline crates/runtime/src/init/dataset.rs:459]: Is it possible to only clear the plan for dataset that's updated?

Comment (phillipleblanc) [reply crates/runtime/src/init/dataset.rs:459]: Given this is a dev-only scenario, clearing the entire plan cache is acceptable.

**Review by phillipleblanc — APPROVED** [review]
