### PR TITLE
clear message when invalid params configured for accelerator

### LINKED ISSUE #1255: Spice doesn't complain when spicepod has invalid params
**Describe the bug**
I accidentally put the wrong params in my spicepod and it didn't complain

```
version: v1beta1
kind: Spicepod
name: clickhouse_quickstart
datasets:
  - from: clickhouse:sample_table
    name: sample_table
    params:
      clickhouse_host: localhost
      clickhouse_db: default
      clickhouse_tcp_port: 9000
      clickhouse_user: <redacted>
      clickhouse_pass: <redacted>
      clickhouse_secure: false
    acceleration:
      engine: sqlite
      mode: file
      enabled: true
      refresh_mode: full
      refresh_interval: 10s
      refresh_sql: SELECT * FROM sample_table limit 100000;
      params:
        duckdb_file: /Users/aurashb/Development/demos/clickhouse/clickhouse.db:
```

**To Reproduce**
Note the spicepod above has a duckdb_file instead of sqlitefile.  

**Expected behavior**
An error indicating my configuration is wrong.

### PR DESCRIPTION
**Pull request by y-f-u**
This extends parameters support onto accelerator, so it gives same experience when configuring params in data connector.

Fix #1255

### CODE REVIEW

File: crates/runtime/src/parameters.rs [hunk 1]
```diff
@@ -0,0 +1,372 @@
...
+    pub async fn try_new(
+        component_name: &str,
+        params: Vec<(String, SecretString)>,
+        prefix: &'static str,
+        secrets: Arc<RwLock<Secrets>>,
+        all_params: &'static [ParameterSpec],
+    ) -> AnyErrorResult<Self> {
+        let full_prefix = format!("{prefix}_");
+
+        // Convert the user-provided parameters into the format expected by the data connector
```
Comment (phillipleblanc) [inline crates/runtime/src/parameters.rs]:
```suggestion
        // Convert the user-provided parameters into the format expected by the component
```

File: crates/runtime/src/dataaccelerator/sqlite.rs [hunk 2]
```diff
@@ -99,6 +105,16 @@ impl DataAccelerator for SqliteAccelerator {
         let deletion_adapter = DeletionTableProviderAdapter::new(sqlite_writer);
         Ok(Arc::new(deletion_adapter))
     }
+
+    /// .
+    fn prefix(&self) -> &'static str {
+        "sqlite"
+    }
+
+    /// .
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/sqlite.rs]:
```suggestion
```

File: crates/runtime/src/dataaccelerator/sqlite.rs [hunk 3]
```diff
@@ -99,6 +105,16 @@ impl DataAccelerator for SqliteAccelerator {
         let deletion_adapter = DeletionTableProviderAdapter::new(sqlite_writer);
         Ok(Arc::new(deletion_adapter))
     }
+
+    /// .
```
Comment (phillipleblanc) [inline crates/runtime/src/dataaccelerator/sqlite.rs]:
```suggestion
```

**Review by phillipleblanc — DISMISSED** [review]
