### PR TITLE
Make `tool_use::table_schema` output model-friendly

### LINKED ISSUE #7114: Make `tool_use::table_schema` more model-friendly
## Describe the bug

`tool_use::table_schema` Spice tool should be improved to be more efficient
 -  Should NOT include unnecessary fields such as `dict_id":0,"dict_is_ordered":false,"`, metadata
 -  Should use associated DataFusion SQL types instead of Arrow (we have similar logic for ADBC to provide SQL types)
 - use markdown instead of json

```
[{"table":"my_table","schema":{"fields":[
{"name":"CUSTOMERID","data_type":{"Decimal128":[38,0]},"nullable":false,"dict_id":0,"dict_is_ordered":false,"metadata":{}},
{"name":"TIMEPERIOD","data_type":"Utf8","nullable":false,"dict_id":0,"dict_is_ordered":false,"metadata":{}},
```

### PR DESCRIPTION
**Pull request by krinart**
## 📝 Summary

Make output of `tool_use::table_schema` more model-friendly by utilizing markdown tables. 

Example:
```
**Table: spice.public.customer**

Metadata:
* location: "Europe"
* description: All the customers of the world

| Column | Sql Type | Arrow Type | Nullable | Metadata |
| --- | --- | --- | --- | --- |
| c_custkey | BIGINT | Int64 | true |  |
| c_name | VARCHAR | Utf8 | true | * description: Customer name<br>* protected: "yes" |
```

Benchmarks:
Financebench: 0.2907 -> 0.328
NSQL: 0.62 -> 0.65

## 🔗 Related

Closes https://github.com/spiceai/spiceai/issues/7114

### CODE REVIEW

File: crates/arrow_tools/src/schema.rs [hunk 1]
```diff
@@ -206,6 +206,54 @@ pub fn schema_difference(expected: &Schema, actual: &Schema) -> Option<String> {
     }
 }
 
+/// Returns associated `DataFusion` SQL type name for provided Arrow `DataType`.
+/// `<https://datafusion.apache.org/user-guide/sql/data_types.html>`
+#[must_use]
+pub fn to_source_native_type_name(data_type: &DataType) -> &'static str {
```
Comment (krinart) [inline crates/arrow_tools/src/schema.rs:212]: This function was moved from `runtime/src/flight/flightsql/get_tables.rs` to make it more accessible

File: crates/arrow_tools/src/format.rs [hunk 2]
```diff
@@ -327,6 +328,64 @@ fn column_indices(batch: &RecordBatch, column_names: &[String]) -> Result<Vec<us
         .collect()
 }
 
+fn hashmap_to_string(map: &HashMap<String, String>, separator: &str) -> String {
+    let mut keys: Vec<_> = map.keys().collect();
+    keys.sort(); // To make this function reproducible
+    keys.iter()
+        .map(|k| format!("* {}: {}", k, map.get(*k).map_or("", String::as_str)))
```
Comment (kczimm) [inline crates/arrow_tools/src/format.rs]: I think this should be okay because you know the keys are present in the map.
```suggestion
        .map(|k| format!("* {}: {}", k, map[k]))
```

File: crates/arrow_tools/src/format.rs [hunk 3]
```diff
@@ -327,6 +328,64 @@ fn column_indices(batch: &RecordBatch, column_names: &[String]) -> Result<Vec<us
...
+/// | id | BIGINT | Int64 | false | * comment: autoincrement<br>* description: user id |
+/// | name | VARCHAR | Utf8 | true |  |
+#[must_use]
+pub fn table_schemas_to_markdown_table(table_schemas: Vec<(String, Schema)>) -> String {
+    let mut table_schemas_formatted = Vec::with_capacity(table_schemas.len());
+
+    for (table_name, table_schema) in table_schemas {
+        // Header row and separator for markdown
+        let header = ["Column", "Sql Type", "Arrow Type", "Nullable", "Metadata"];
+        let separator = ["---"; 5];
```
Comment (kczimm) [inline crates/arrow_tools/src/format.rs]: these can go outside of the loop and be made `static`.

File: crates/arrow_tools/src/format.rs [hunk 4]
```diff
@@ -327,6 +328,64 @@ fn column_indices(batch: &RecordBatch, column_names: &[String]) -> Result<Vec<us
...
+
+        let mut md_table = Vec::new();
+        md_table.push(format!("| {} |", header.join(" | ")));
+        md_table.push(format!("| {} |", separator.join(" | ")));
```
Comment (kczimm) [inline crates/arrow_tools/src/format.rs]:
```suggestion
        let mut md_table = vec![format!("| {} |", header.join(" | ")), format!("| {} |", separator.join(" | "))];
```

File: crates/arrow_tools/src/format.rs [hunk 5]
```diff
@@ -327,6 +328,64 @@ fn column_indices(batch: &RecordBatch, column_names: &[String]) -> Result<Vec<us
...
+                "| {} | {} | {} | {} | {} |",
+                field.name(),
+                to_source_native_type_name(field.data_type()),
+                field.data_type(),
+                field.is_nullable(),
+                hashmap_to_string(field.metadata(), "<br>"),
+            ));
+        }
+
+        let mut sections = vec![format!("**Table: {}**", table_name)];
```
Comment (kczimm) [inline crates/arrow_tools/src/format.rs]:
```suggestion
        let mut sections = vec![format!("**Table: {table_name}**")];
```

**Review by kczimm — DISMISSED** [review]
Just some nits for consideration.

**Review by Jeadie — APPROVED** [review]
