### PR TITLE
Fix datasets live update (Spice file watcher)

### LINKED ISSUE #1670: Spice filewatcher does not apply dataset acceleration changes
**Describe the bug**
When I change dataset acceleration parameters (for example, enable or disable) in yaml file while Spice runtime is running it does not automatically detect and apply the changes.

**To Reproduce**
Follow https://github.com/spiceai/quickstarts/edit/trunk/tpc-h/ guide. After enabling (saving) acceleration Spice runtime does not automatically detect and apply the changes

### PR DESCRIPTION
**Pull request by sgrebnov**
Fixes [Spice filewatcher does not apply dataset acceleration changes ](https://github.com/spiceai/spiceai/issues/1670)

### CODE REVIEW

File: crates/runtime/src/lib.rs [hunk 1]
```diff
@@ -996,13 +999,11 @@ impl Runtime {
 
                 // check for new and updated datasets
                 let valid_datasets = Self::get_valid_datasets(&new_app, true);
+                let existing_datasets = Runtime::get_valid_datasets(current_app, false);
```
Comment (phillipleblanc) [inline crates/runtime/src/lib.rs]:
```suggestion
                let existing_datasets = Self::get_valid_datasets(current_app, false);
```

**Review by phillipleblanc — DISMISSED** [review]

**Review by phillipleblanc — APPROVED** [review]
