### PR TITLE
Benchmark: include arrow acceleration and enable more tests (tpch_q22)

### LINKED ISSUE #2170: Bug: accelerated query fails with `Expression not supported c_acctbal > Decimal128(Some(0),38,2)`
The following error occurs when I run accelerated tpch_q22 query

>Status { code: InvalidArgument, message: "External error: Execution error: Unable to generate SQL: Expression not supported c_acctbal > Decimal128(Some(0),38,2) AS customer.c_acctbal > Decimal128(Some(0),38,15)", source: None }

### PR DESCRIPTION
**Pull request by sgrebnov**
## 🗣 Description

PR includes [Fix plan unparsing for filters with subqueries involved type coercion](https://github.com/datafusion-contrib/datafusion-table-providers/pull/26) fix and enables `tpch_q22` query test for acceleration.

This closes https://github.com/spiceai/spiceai/issues/2170

Also adds arrow acceleration engine for testing.

### CODE REVIEW

File: crates/runtime/benches/bench_s3/mod.rs [hunk 1]
```diff
@@ -98,9 +98,7 @@ fn make_dataset(path: &str, name: &str) -> Dataset {
     dataset
 }
 
-fn get_test_queries(acceleration: &Option<Acceleration>) -> Vec<(&'static str, &'static str)> {
-    let is_accelerated = acceleration.is_some();
-
+fn get_test_queries(_acceleration: &Option<Acceleration>) -> Vec<(&'static str, &'static str)> {
```
Comment (sgrebnov) [inline crates/runtime/benches/bench_s3/mod.rs:101]: Not removing this parameter so we can re-use it in the future when we have more tests, I expect at least few of them will require extra work for specific acceleration engine.

**Review by peasee — APPROVED** [review]
