### PR TITLE
Catch when an insecure (http) S3 and ABFS data connectors endpoint is used without specifying the `allow_http` parameter

### LINKED ISSUE #4358: S3 Data Connector - fix error message when connecting to custom `http` endpoint without `allow_http` enabled
## Describe the bug

```yaml
version: v1beta1
kind: Spicepod
name: tpcds-sf5
datasets:
  - from: s3://tpcds-sf5/call_center.parquet
    name: call_center
    params:
      client_timeout: 3h
      s3_endpoint: http://localhost:9000
      # allow_http: true
```

fails with bad error
```
2025-01-16T02:38:05.834529Z  WARN runtime::init::dataset: Cannot connect to the dataset call_center (s3).
Object Store error: Generic S3 error: Error after 10 retries in 1.786348042s, max_retries:10, retry_timeout:180s, source:error sending request for url (http://s3service.data.orb.local:9000/tpcds-sf5/call_center.parquet)
```

## Expected behavior

Error message should be clear. Inform user that s3 dataset with custom `http` endpoint can't be registered without explicit `allow_http` param

### PR DESCRIPTION
**Pull request by ewgenius**
# 🗣 Description

[breaking change] Rename `abfs_allow_http` to `allow_http` in ABFS connector.

Throw an error if http endpoint is used without `allow_http` parameter in S3 and ABFS data connectors

**Before**:

```
2025-01-16T06:08:43.619129Z  WARN runtime::init::dataset: Cannot connect to the dataset call_center (s3).
Object Store error: Generic S3 error: Error after 0 retries in 8.792µs, max_retries:10, retry_timeout:180s, source:builder error for url (http://localhost:9000/tpcds-sf5/call_center.parquet)
```

**After**:

```
2025-01-16T06:37:53.562020Z  WARN runtime::init::dataset: Error initializing dataset call_center. The 'http://localhost:9000' is an insecure HTTP URL, but `allow_http` is not enabled.
For details, visit: https://docs.spiceai.org/components/data-connectors/s3#params
```

## 🔨 Related Issues

closes #4358

## ⛓️‍💥 Breaking Change

* [x] "Breaking Change" label added if this PR is a breaking change

## 📄 Documentation Updates

- https://github.com/spiceai/docs/pull/766

### CODE REVIEW

File: crates/runtime/src/dataconnector/abfs.rs [hunk 1]
```diff
@@ -50,6 +50,9 @@ pub enum Error {
         "The 'abfs_endpoint' parameter must be a HTTP/S URL, but '{endpoint}' was provided.\nSpecify a valid HTTP/S URL."
     ))]
     InvalidEndpoint { endpoint: String },
+
+    #[snafu(display("The '{endpoint}' is an insecure HTTP URL, but `allow_http` is not enabled.\nFor details, visit: https://spiceai.org/docs/components/data-connectors/abfs#params"))]
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/abfs.rs]:
```suggestion
    #[snafu(display("The '{endpoint}' is a HTTP URL, but `allow_http` is not enabled. Set the parameter `allow_http: true` and retry.\nFor details, visit: https://spiceai.org/docs/components/data-connectors/abfs#params"))]
```

File: crates/runtime/src/dataconnector/s3.rs [hunk 2]
```diff
@@ -103,6 +103,9 @@ pub enum Error {
     InvalidIAMRoleAuthentication {
         source: Box<dyn std::error::Error + Send + Sync>,
     },
+
+    #[snafu(display("The '{endpoint}' is an insecure HTTP URL, but `allow_http` is not enabled.\nFor details, visit: https://docs.spiceai.org/components/data-connectors/s3#params"))]
```
Comment (phillipleblanc) [inline crates/runtime/src/dataconnector/s3.rs]:
```suggestion
    #[snafu(display("The '{endpoint}' is a HTTP URL, but `allow_http` is not enabled. Set the parameter `allow_http: true` and retry.\nFor details, visit: https://spiceai.org/docs/components/data-connectors/abfs#params"))]
```

**Review by phillipleblanc — APPROVED** [review]
