### PR TITLE
Cayenne: refactor write path to use insert_into() as single entry point (part 1)

### LINKED ISSUE #9087: Bug. Cayenne `insert_into` should be based on `insert`
## Describe the bug

Recent optimizations + tests use [insert](https://github.com/spiceai/spiceai/blob/trunk/crates/cayenne/src/provider/table.rs#L1006) method which is NOT used in actual `refresh` logic which is based on `insert_into` (separate code).

1. The code must be updated so all tests use `insert_into`
2. `insert_into` should include all recent optimizations/fixes added into `insert`
3. The following needs to be improved: `insert_into()` returns an `ExecutionPlan` that DataFusion executes later, but the actual catalog updates are performed immediately  BEFORE data is written: `update_current_snapshot_id/commit_compaction/cleanup_old_snapshots_blocking/etc`

### PR DESCRIPTION
**Pull request by sgrebnov**
## 📝 Summary

Migrate all Cayenne writes to use insert_into()` as the single entry point, routing through `CayenneDataSink`.

1. Route all write paths through `CayenneDataSink.insert_into`for all cases (overwrite, append, position-based deletions)
1. Migrate all tests to use `insert_into()` API which is used by refresh path

This improves the following:
1. `upload_concurrency` is now respected due to using `chunk_and_write_parallel` preventing unbound memory growth for `partition_by` scenarios
1. `Overwrite execution order` - fixed: Catalog updated before data written → data loss on crash
1. `merge_insert_with_compaction` execution order -> fixed: deletion caches cleared before plan executed → tests failures after switching to `insert_into`

Next refactoring steps planned (next PR):
- https://github.com/spiceai/spiceai/issues/9089

## 🔗 Related

Fixes https://github.com/spiceai/spiceai/issues/9087

### CODE REVIEW

File: crates/cayenne/src/provider/table.rs [hunk 1]
```diff
@@ -3253,253 +3354,6 @@ impl CayenneTableProvider {
...
-    /// * `new_input` - The execution plan for new data to insert
-    ///
-    /// # Returns
-    ///
-    /// An execution plan that writes the merged data to a new snapshot.
-    ///
-    /// # Errors
-    ///
-    /// Returns an error if the merge-insert operation fails.
-    async fn merge_insert_with_compaction(
```
Comment (sgrebnov) [inline crates/cayenne/src/provider/table.rs:3276]: Removed in favor of  `merge_insert_stream_with_compaction`

File: crates/cayenne/benches/deletion_strategies.rs [hunk 2]
```diff
@@ -162,11 +162,25 @@ fn generate_no_pk_batch(schema: Arc<Schema>, size: usize) -> RecordBatch {
...
-    let stream = futures::stream::once(async { Ok(batch) });
-    let boxed_stream: datafusion_execution::SendableRecordBatchStream =
-        Box::pin(datafusion::physical_plan::stream::RecordBatchStreamAdapter::new(schema, stream));
-    table.insert(boxed_stream).await.expect("insert");
+    let input_exec = datafusion::datasource::memory::MemorySourceConfig::try_new_exec(
+        &[vec![batch]],
+        schema,
+        None,
+    )
+    .expect("memory exec");
```
Comment (Jeadie) [inline crates/cayenne/benches/deletion_strategies.rs:172]: `.expect` in non-test code?

File: crates/cayenne/src/provider/sink.rs [hunk 3]
```diff
@@ -0,0 +1,236 @@
...
+    /// 2. Writes data to the new snapshot directory with memory bounds
+    /// 3. Syncs the directory for durability (local paths only)
+    /// 4. Atomically updates the catalog to point to the new snapshot
+    /// 5. Updates in-memory state (snapshot ID, listing table, deletion caches)
+    /// 6. Triggers cleanup of old snapshots
+    async fn write_all_overwrite(&self, data: SendableRecordBatchStream) -> DFResult<u64> {
+        // Generate a new UUIDv7 for the snapshot
+        let new_snapshot_id = uuid::Uuid::now_v7().to_string();
+
+        let is_s3 = self.table.table_path().starts_with("s3://");
```
Comment (Jeadie) [inline crates/cayenne/src/provider/sink.rs:149]: nit: this should be object_store dependent

File: crates/cayenne/src/provider/table.rs [hunk 4]
```diff
@@ -358,6 +360,95 @@ impl std::fmt::Debug for CayenneTableProvider {
...
+        *listing_table_guard = new_listing_table;
+        Ok(())
+    }
+
+    /// Trigger cleanup of old snapshot directories in the background.
+    ///
+    /// This is a non-blocking operation that logs warnings on failure but doesn't
+    /// propagate errors, as cleanup failures shouldn't fail the write operation.
+    pub(crate) async fn trigger_old_snapshot_cleanup(&self, current_snapshot: &str) {
+        if self.table_metadata.path.starts_with("s3://") {
```
Comment (Jeadie) [inline crates/cayenne/src/provider/table.rs:428]: same again about using `object_store`. Likely not much work, and will future proof any decisions we make (e.g. `object_store` config across scheduler/executor nodes).

**Review by Jeadie — APPROVED** [review]

File: crates/cayenne/src/provider/sink.rs (hunk 3 above)
Comment (phillipleblanc) [reply crates/cayenne/src/provider/sink.rs:149]: this is only supported for local paths or s3 one zone

**Review by phillipleblanc — APPROVED** [review]

File: crates/cayenne/src/provider/sink.rs (hunk 3 above)
Comment (sgrebnov) [reply crates/cayenne/src/provider/sink.rs:149]: Thanks, will review how to improve as part of next PR
