### PR TITLE
fix hanging spiced when odbc loading data and received a cancel signal

### LINKED ISSUE #2083: Bug: Runtime does not abort (Ctrl+C) while accelerating dataset
**Describe the bug**

While accelerating datasets, if you attempt to exit the runtime with a quit command (Ctrl+C) the runtime will not immediately exit.

The runtime will print `Goodbye!`, but will continue running until acceleration of the dataset that was in-progress completes before actually exiting.

This also happens when registering the federated datasets.

**To Reproduce**

1. Configure a large dataset with acceleration that takes some time to accelerate
2. Start the runtime
3. Try to quit the runtime (Ctrl+C)
4. Observe the runtime will not quit

**Expected behavior**

The runtime should correctly shutdown on kill commands, and quit regardless of in-progress operations.

**Have you tried this on the latest `trunk` branch?**

Yes

### PR DESCRIPTION
**Pull request by y-f-u**
## 🗣 Description

`spawn_blocking` will prevent the tokio runtime to shutdown as
> When you shut down the executor, it will wait indefinitely for all blocking operations to finish.

Alternatively, a force shutdown can be done however that will potential leave things in a bad state. Opt for using `CancellationToken` from tokio to coordinate between a dedicated ctrl-c listening task and the data fetch task.

## 🔨 Related Issues

Fixes #2083

### CODE REVIEW

File: crates/db_connection_pool/src/dbconnection/odbcconn.rs [hunk 1]
```diff
@@ -173,6 +174,26 @@ where
...
+
+        tokio::spawn(async move {
+            let ctrl_c = async {
+                let signal_result = signal::ctrl_c().await;
+                if let Err(err) = signal_result {
+                    tracing::error!(
+                        "Failed to listen to shutdown signal in ODBC data fetching: {err}"
+                    );
+                } else {
+                    cancellation_token.clone().cancel();
```
Comment (phillipleblanc) [inline crates/db_connection_pool/src/dbconnection/odbcconn.rs]: Move this cancel outside of the else - even if listening fails, we still want to cancel

File: crates/db_connection_pool/src/dbconnection/odbcconn.rs [hunk 2]
```diff
@@ -173,6 +174,26 @@ where
         let params = params.iter().map(dyn_clone::clone).collect::<Vec<_>>();
         let secrets = Arc::clone(&self.params);
 
+        let cancellation_token = tokio_util::sync::CancellationToken::new();
+        let cloned_token = cancellation_token.clone();
+
+        tokio::spawn(async move {
+            let ctrl_c = async {
+                let signal_result = signal::ctrl_c().await;
```
Comment (phillipleblanc) [inline crates/db_connection_pool/src/dbconnection/odbcconn.rs]: Does this also handle SIGTERM? That is the signal K8s sends for graceful shutdown

Comment (y-f-u) [reply crates/db_connection_pool/src/dbconnection/odbcconn.rs]: it seems spiced doesn't handle sigterm gracefully now. Created a separate issue to track this https://github.com/spiceai/spiceai/issues/2159

**Review by phillipleblanc — DISMISSED** [review]

**Review by sgrebnov — APPROVED** [review]
